### ISSUE TITLE
doesn't work with eleline statusline

### ISSUE THREAD

**Issue by GopherJ** [akinsho/toggleterm.nvim#100]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33961674/136683902-f23ed806-0427-417e-8497-fabee73d7ab1.png">

**Comment by akinsho** [comment]
@GopherJ this issue requires a bit more information than just a screen shot, I don't use `eleline` and don't want to install it for this issue. To be clear this plugin does not *at all* touch a user's statusline. It could be that the special characters in the terminal's name are causing some issue for eleline but I would see that as an issue with that plugin and not this one

**Comment by akinsho** [comment]
Going to close this out since I haven't had any more information and it's not clear to me how this plugin could be affecting a user's statusline since it doesn't touch that part of nvim at all.
