### ISSUE TITLE
Preserve state without long running process

### ISSUE THREAD

**Issue by krevativ** [akinsho/toggleterm.nvim#102]
I would like to be able to preserve the state even if I hide the terminal without long running process. For example, I would like to execute something like `eslint .` go to file, hide the terminal, do the work and return to the terminal without the necessity to run the command again. Is it somehow already possible or planed? Could not find anything in this direction.

**Comment by akinsho** [comment]
@krevativ if I understand correctly this should already work. You need to make sure your terminals are persisted by making sure you set the hidden option in vim please check the help docs for the hidden setting and see if it helps

**Comment by krevativ** [comment]
Hey, thanks for the quick response. If you mean `vim.opt.hidden = true` then I've already did that ([my dotfiles](https://github.com/krevativ/dotfiles/blob/main/nvim/lua/settings.lua#L41)). I've also inspected this setting at runtime and it is activated. But either way, it seems not to preserve the state anyway. Is there some other info I can provide you? I'm using the latest nvim dev build for example.

**Comment by krevativ** [comment]
I've did that but without the '--noplugin' argument, because the plugin must be loaded somehow. And it doesn't work.

Here is my minimal config:

```lua
vim.g.mapleader = " "
vim.opt.hidden = true

local Plug = vim.fn["plug#"]

vim.call("plug#begin", "~/.config/nvim/plugged")

Plug "akinsho/toggleterm.nvim"

vim.call("plug#end")

require("toggleterm").setup {
  shade_terminals = false,
  start_in_insert = true,
  close_on_exit = false,
  size = 30
}

local map = vim.api.nvim_set_keymap
local nores = {noremap = true, silent = true}

map("n", "<leader>t", '<Cmd>exe v:count1 . "ToggleTerm"<CR><C-L>', nores)
map("t", "<Esc>", "<C-\\><C-n>", nores)
```
I'm pressed `<space>t` (also tryed with `1<space>t`) to toggle the terminal. Run some command like `echo 'foo'` for example. Press <space>t twice and the state is lost.

It also works with the normal :terminal and the 'caenrique/nvim-toggle-terminal' plugin. But not with this plugin. 

`:checkhealth` is also almost completly green. Only the Python 2 provider is missing.

**Comment by akinsho** [comment]
@krevativ okay, I think I understand what is going wrong. The manual mapping you are creating doesn't actually work. If that's from the docs it shouldn't be there any more, although I think I advise against trying to use a manual mapping since it's easier for this plugin to work if you just specify the `open_mapping` configuration option.

can you instead set `open_mapping = '<leader>t` and see if that works
