### ISSUE TITLE
TermExec open=0 don't close terminal if it was already open. 

### ISSUE THREAD

**Issue by jakobkhansen** [akinsho/toggleterm.nvim#103]
Hi,

I'm using TermExec to run a command and would like the state of the terminal (open/closed) to stay the same. If i send the parameter `open=1`, it will open the terminal if its closed and `open=0` closes the terminal if it was open before. I would like the terminal to stay in the same state as it was before the command ran. Is that possible?

**Comment by akinsho** [comment]
@jakobkhansen I don't think so, the `open` option was added by a user who had that use case. I personally don't use it. I guess some sort of third option could be added but frankly as this was a user contributed feature that I didn't really have any particular attachment to I don't think I'd add it myself but will review and help guide a PR 🤷🏿‍♂️

**Comment by jakobkhansen** [comment]
Thank you, I was able to do what I wanted with that 😊
