### ISSUE TITLE
run command on toggleterm startup

### ISSUE THREAD

**Issue by molleweide** [akinsho/toggleterm.nvim#114]
Hi guys,

Is it possible to run command on term startup automatically. I need to run `zsh -il` in order to invoke interactive shell due to some external reasons. Is it possible to specify this in config, eg. `run = `zsh -il`?

**Comment by akinsho** [comment]
@molleweide you can probably change the shell argument of the plugin to use `zsh -il` instead of whatever your default is. The option should be documented in the README.

**Comment by molleweide** [comment]
Alright, thank you for replying!

**Comment by akinsho** [comment]
Can I close this out now? did that work?

**Comment by molleweide** [comment]
Oh sorry i should have closed. I havent had time to try yet but i am sure it will work. I just didn't understand at first.
