### ISSUE TITLE
cann't use gF in floating mode

### ISSUE THREAD

**Issue by antosha417** [akinsho/toggleterm.nvim#116]
When I run compiler in floating terminal I want to be able to press gF on filepath with an error and go to the file with terminal hidden. 
But if I press gF the file will open in floating window.
Is it possible to use gF with floating terminal?

**Comment by akinsho** [comment]
Hi @antosha417, what you describe is normal nvim behaviour the floating window is a window just like any other, so if  you press gF in the window it will attempt to switch to the buffer in the float. It isn't as far as I'm concerned the remit of this plugin to handle specific commands differently but can maybe be handled in your config with a custom mapping using the `on_open` handler to set a new mapping that closes the window then re-opens the file in the buffer underneath and finally executes the command. Alternatively and much more simply you can use `<c-w>gF` which will open the buffer in a new tab already

As I mention in the README the idea behind this plugin is quite simple, and I don't really want to go down the rabbit hole of adding very specific bespoke logic here.

**Comment by antosha417** [comment]
@akinsho, thanks a lot for your answer! 
I ended up writing this simple function 
```lua
M.gotofile = function ()
  local cursor = vim.api.nvim_win_get_cursor(0)
  local bufnr = vim.api.nvim_get_current_buf()
  require('toggleterm').toggle(0)
  vim.api.nvim_win_set_buf(0, bufnr)
  vim.api.nvim_win_set_cursor(0, cursor)
  vim.api.nvim_buf_del_keymap(0, 'n', 'gF')
  vim.cmd('norm gF')
end
```
and then setting a keymap for this
```lua
local opts = {noremap = true}
function _G.set_terminal_keymaps()
  ...
  ...
  vim.api.nvim_buf_set_keymap(0, 'n', 'gF', [[<cmd>lua require'settings.term'.gotofile()<cr>]], opts)
end

vim.cmd('autocmd! TermOpen term://*toggleterm#* lua set_terminal_keymaps()')
```
