### ISSUE TITLE
[feature request] capability to change the size of floating terminal

### ISSUE THREAD

**Issue by NikoKS** [akinsho/toggleterm.nvim#117]
Would it be possible to make the floating terminal respect the size setting?
Should be useful for a number of reasons.

**Comment by akinsho** [comment]
@NikoKS if you have a look at the README you can specify the `float_opts` and inside this table you can then specify the `height` and `width` although I don't use either of those options they should work for this case.

**Comment by NikoKS** [comment]
Thank you, that works! Any chance it can be changed as a percentage instead of character length?

**Comment by akinsho** [comment]
I'd be happy to take a PR to add that functionality, but probably won't do that myself. You can derive something like that on your end though, just `vim.o.lines * 0.30 -- 30% height` or `vim.o.columns * 0.5 -- 50% width`

**Comment by akinsho** [comment]
Going to close this out since there is a solution. As mentioned, if someone would like to implement the percentage behaviour, I will happily review or guide a PR.
