### ISSUE TITLE
ToggleTermCloseAll not working with last commit

### ISSUE THREAD

**Issue by grimgort** [akinsho/toggleterm.nvim#120]
hello,
ToggleTermCloseAll is no longer functional since the last commits

**Comment by akinsho** [comment]
@grimgort that command got deprecated in favour of just one command called `ToggleTermToggleAll` if you want to explicitly close terminals you can use `ToggleTermToggleAll!` please have a read of the updated README for more info

**Comment by akinsho** [comment]
I think this is answered by the above, so I'm going to close this out since it's informational and the answer has been provided
