### ISSUE TITLE
[ Question ] Is it possible to send <C-c> to a terminal?

### ISSUE THREAD

**Issue by tuxflo** [akinsho/toggleterm.nvim#124]
Is there a way to cancel the currently running process inside a ToggleTerm, which was previously started using `:TermExec cmd="my long running process"`? 
Currently I have to move the cursor into the ToggleTerm buffer, enter insert mode, hit `<C-c>` and switch back to my previous buffer.

**Comment by akinsho** [comment]
@tuxflo nope there is no built-in mechanism for that, and I'm not aware of anyway to do that I guess you could write a mapping that switched to the right terminal and used `vim.fn.feedkeys` to try and send that key, but that's too convoluted a thing for me to add to this plugin and I think should be fixed/implemented in a user's config.

**Comment by tuxflo** [comment]
OK, thanks for the clarification, I'll try to do your suggestion when I find some time.

**Comment by jZhangTk** [comment]
I had the same question, and I use this to send `<C-c>` as a command
```
nmap <leader>tc :execute v:count1.'TermExec cmd="<C-v><C-c>"'<CR>
```
It works most of the time. However, it sometimes just rings a bell without doing anything in the terminal.

@tuxflo did you come up with anything better?

**Comment by tuxflo** [comment]
No I did not do any research on how to deal with this after receiving the answer above, sorry.
