### ISSUE TITLE
Shell Swallows <Esc> Key

### ISSUE THREAD

**Issue by redxtech** [akinsho/toggleterm.nvim#125]
I use `zsh`, and I use its `vi`-mode bindings. As such, when I press `<Esc>` within the ToggleTerm, the shell captures the `<Esc>` keypress and puts me into edit mode in the shell, but leaving me in insert mode in the ToggleTerm vim window.

Is there an easy way to get around this? Or do I have to change my `.zshrc` to not use `bindkeys -v`?

Thanks!

**Comment by akinsho** [comment]
@redxtech as far as I know vi mode in terminal does not work in neovim regardless of using this plugin or not. The same functionality you describe would not work in the native terminal. I don't have  solution for this unfortunately. Happy to take a PR if you think of one.

**Comment by redxtech** [comment]
Oh that's good to know. I think the solution here is probably to find a way to selectively use vi mode only if not in a vim terminal.

**Comment by zeertzjq** [comment]
Have you read `:h terminal-input`?

**Comment by redxtech** [comment]
> @redxtech Have you read `:h terminal-input`?

No I hadn't, but I just did now. Looks useful. That seems like it should solve my issue, not that it's an issue anymore.
