### ISSUE TITLE
Question: Send code block in one input line.

### ISSUE THREAD

**Issue by mmazz** [akinsho/toggleterm.nvim#127]
Situation example: Python file + toggleterminal with ipython.
It's possible to send a block of code to only one line of the ipython terminal? How I try, each line of code it's one input for ipython, and that's a mess. Also there is a way to show only the output and not duplicate the input (one in each window). I don't know if this is a good thing, but may distract me a little less with less redundant info.
This it's a plug configure or I'm a noob and this it's not related to the plugin itself?

**Comment by akinsho** [comment]
@mmazz this seems like quite a specific and complex workflow. The general goal of this plugin is not to be a code runner there are quite a few plugins that already do that like https://github.com/michaelb/sniprun this might be a better option. You could probably work something out but I think it would be possibly quite complex/another plugin entirely tbh.
