### ISSUE TITLE
How can I check if a terminal created with toggleterm is still active?

### ISSUE THREAD

**Issue by jrafaaael** [akinsho/toggleterm.nvim#128]
I would like to check if at least one terminal created with toggleterm is still active, no matter it is hidden or not (due to toggle action). Thanks in advance!

**Comment by akinsho** [comment]
@jrafaaael this is an internal api so could possibly change but you could run `require('toggleterm.terminal').get_all()` to see if the list has any content.

**Comment by jrafaaael** [comment]
@akinsho thanks! Is what I needed! 

non related question: How can I create a conditional mapping?

I am trying to reproduce VSCode terminal behavior: If there are no active terminals, a new one is created. If there are active terminals, hide/show them all, this action is done with the same keyboard shortcut.

What I have tried so far is:
```lua
local map = vim.api.nvim_set_keymap

local already_exist_a_terminal_active = function()
  return #require("toggleterm.terminal").get_all() > 0
end

map(
  'n',
  '<C-m>',
  ':lua already_exist_a_terminal_active() ? ":ToggleTermToggleAll" : ":ToggleTerm"',
  {expr = true, noremap = false, silent = true}
)
```
and
```lua
local map = vim.api.nvim_set_keymap

local already_exist_a_terminal_active = function()
  return #require("toggleterm.terminal").get_all() > 0
end

map(
  'n',
  '<C-m>',
  'v:lua already_exist_a_terminal_active() ? ":ToggleTermToggleAll" : ":ToggleTerm"',
  {expr = true, noremap = false, silent = true}
)
```
but I get the errors:
```lua
E121: Undefined variable: :lua
```
and
```lua
E15: Invalid expression: v:lua already_exist_a_terminal_active() ? ":ToggleTermToggleAll" : ":ToggleTerm"
```
, respectively.

Thanks in advance!
