### ISSUE TITLE
Is there any way to force the closure of one of the terminals?

### ISSUE THREAD

**Issue by CleoMenezes** [akinsho/toggleterm.nvim#133]
I opened a program through the terminal, and basically it was in a waiting state while running the app. After closing the app, the terminal continued in the same state as before. That's fine with that, but I haven't found any way to force this instance to close. How could I do in these cases?

Thanks for the great job.
https://user-images.githubusercontent.com/54215258/147492400-10ebe5e7-e1b2-4c55-b5ef-c9e526d6746b.mp4

**Comment by akinsho** [comment]
@CleoMenezes normally `<C-c>` exits a running process for me but from your video it seems to not take this input which isn't something I can reproduce. Can you check on your side that this process actually responds to this signal? If it's a program you are writing yourself that maybe doesn't know to respond to the exit signal, this could happen. In either case, I don't think that not responding to `<c-c>` comes from this plugin. You could always try deleting the terminal with `:bdelete!`

**Comment by akinsho** [comment]
Going to close this out as 1) the terminal buffer can be killed using `:bdelete` 2) it appears to be an issue with the running program that it isn't responding to `<C-C>` 3) this is all about terminal behaviour, which this plugin doesn't change (it only changes the appearance and toggling visibility of terminals not how they run, that comes from nvim core).
