### ISSUE TITLE
using powershell

### ISSUE THREAD

**Issue by bryant-the-coder** [akinsho/toggleterm.nvim#135]
how can i change my cmd to powershell? cuz cmd is ugly

**Comment by akinsho** [comment]
@bryant-the-coder I'm not a Windows user, so I don't know the answer to this question this has been asked in other issues, so I believe if you just search this repo issues for the term `powershell` you should find how other users have done this

**Comment by akinsho** [comment]
See https://github.com/akinsho/toggleterm.nvim/issues/90 as an example

**Comment by akinsho** [comment]
closing this out as a duplicate that was answered in #90
