### ISSUE TITLE
Error on neovim HEAD

### ISSUE THREAD

**Issue by augustocdias** [akinsho/toggleterm.nvim#139]
Neovim introduced [a breaking change](https://github.com/neovim/neovim/issues/14090#issuecomment-1004318147) that passing `nil` is not converted to 0 for current buffer. 

This is causing toggleterm to break here:
https://github.com/akinsho/toggleterm.nvim/blob/master/lua/toggleterm/ui.lua#L289

**Comment by akinsho** [comment]
Thanks for the report 👍🏿 I don't use nightly so hadn't noticed. I just pushed 46c1eee which hopefully should have resolved this issue. Lemme know if it still recurs for you and I'll reopen this issue
