### ISSUE TITLE
Title customization for terminal

### ISSUE THREAD

**Issue by you-n-g** [akinsho/toggleterm.nvim#140]
Hi, 
Thanks for your great efforts to develop such a great plugin.

Currently, if open a terminal,  the title of the terminal is displayed at the bottom of the window. 
Like  ` /bin/zsh;#toggleterm#1` in my example.

I want to customize the title and add &channel into the title to get more information.

How could I achieve this with toggleterm?

Thanks for your help in advance :)

**Comment by akinsho** [comment]
@you-n-g by default the name of the buffer is the terminal command to which I append a toggle term ID which is required for this plugin to work. Depending on how you are showing the title of the terminal e.g. presumably using the statusline or the tabline you can add your own logic to the tabline or statusline to show the terminal name how you want. This isn't something that directly relates to this plugin though as it doesn't do anything to either a user's status or tabline.

If someone wanted to contribute a function for computing a string that a user can then use in their tabline I'd be open to it but I don't think it's something that *needs* to be in this plugin

**Comment by you-n-g** [comment]
Thanks for your reply :)

**Comment by karimtaylor1781** [comment]
😁🤔
