### ISSUE TITLE
question: could you provide a command to switch between terminal splits?

### ISSUE THREAD

**Issue by nyngwang** [akinsho/toggleterm.nvim#145]
As title. And it didn't open any split at all.

**Comment by akinsho** [comment]
@nyngwang I don't think this is necessary or rather I don't see why it would be needed. If you have setup mapping to easily move between windows as mentioned in the README it would be just as easy to press a window mapping to move into a terminal split. A separate command would just be clunky

**Comment by akinsho** [comment]
@nyngwang unfortunately you haven't provided me with any information at all I could use to help you debug this? what is your toggleterm configuration, have you actually setup `<C-\>` as your open mapping. What mode are you pressing `2<C-\>` from are you definitely in normal mode when you press it? What number is your current terminal? is it definitely one?

**Comment by akinsho** [comment]
@nyngwang did you figure out how to move between splits in the end?

**Comment by karimtaylor1781** [comment]
Ki
