### ISSUE TITLE
<count>TermExec doesn't send command to the specified term, but opens a new term everytime

### ISSUE THREAD

**Issue by Ciacconas** [akinsho/toggleterm.nvim#146]
Hi, first thanks for the great plugin.

The issue I encountered are very simple. As I understand, if I specify a term count (say 5), then no matter I use `5TermExec cmd="ls" direction="horizontal"` or `lua require"toggleterm".exec("ls", 5, nil, nil, "horizontal")`, I should be sending the `ls` command to the same terminal with a count of 5. But each time I issue any of the commands above, it will just open a new term for me.

Again, thanks for the good work.

**Comment by akinsho** [comment]
@Ciacconas so `<count>TermExec cmd` will only work if `<count>` terminal has already been created, the idea is that it sends a command to a running terminal, it won't work if you don't already have a terminal with that number. In that case it will just create a new one

**Comment by Ciacconas** [comment]
So I should always specify a ` Terminal:new({ count = <count> })` at the beginning right? Thanks for the info! 

One more questions about `<count>TermExec cmd`, you mentioned:
> In that case it will just create a new one

but after it creates the new one, If I send the `<count>TermExec cmd` again right after, shouldn't it be sending the command to the just created one? But instead I observed that there will be 2 terms in this case.
