### ISSUE TITLE
[Question] How can I set differents keymaps to open toggleterm in different directions?

### ISSUE THREAD

**Issue by LaBatata101** [akinsho/toggleterm.nvim#152]
I'm using this setup but it didn't worked as I expected. 
```lua
-- this open the terminal with float direction
require("toggleterm").setup({
  open_mapping = [[<C-t>]],
  direction = "float",
  float_opts = {
    border = "curved",
    winblend = 5,
  },
})

-- and this in the vertical direction
map("t", "<C-\\>", "<cmd>ToggleTerm direction=vertical size=55<CR>", { noremap = true })
map("n", "<C-\\>", "<cmd>ToggleTerm direction=vertical size=55<CR>", { noremap = true })
```
If I press `<C-t>` first it will open the terminal in the float window, then if I press `<C-\>` it will also open the float window.
How can this be fixed?

**Comment by akinsho** [comment]
@LaBatata101 if you are changing direction you need to refer to the *specific* terminal whose direction you are trying to change, the general toggle term command doesn't operate on a specific terminal it finds the last opened terminal and closes it or it opens the closed terminal. If you want to change direction on the fly you need to be specific about the terminal you are trying to target by specifying the terminal number in the command like `:2ToggleTerm` not just `ToggleTerm`
