### ISSUE TITLE
<Tab> jumps to previous buffer

### ISSUE THREAD

**Issue by venzen** [akinsho/toggleterm.nvim#154]
When attempting tab completion in the terminal, the cursor jumps back to the last edit-location in the previous buffer. Is this expected behavior for toggleterm?

When I run `:verbose map` there is no keybinding for the `<Tab>` key.

Assuming that the behavior is expected, is it possible to have the tab key simply perform tab completion in the terminal?

**Comment by akinsho** [comment]
@venzen toggle term does not set any bindings other than the `open_mapping` it doesn't do anything with `<tab>` and completion in the terminal. I just checked, and I'm able to use tab completion in my setup. maybe try running `:verbose tmap <tab>` and see if it's bound to something in your config
