### ISSUE TITLE
Kill all toggleterm terminals on neovim quit.

### ISSUE THREAD

**Issue by a2n-s** [akinsho/toggleterm.nvim#155]
Hi :wave: 

I have a small but yet annoying issue and could not find a related already opened or closed issue...

Imagine:
- I open neovim and a terminal
- I do not close the terminal but try to quit `noevim` anyway, with `wqa!` or `qa!` through the `whichkey` plugin.
- I get the following error
```
E948: Job still running                                                                                                                                      
E676: No matching autocommands for acwrite buffer                                                                                                            
Press ENTER or type command to continue
```
or some other ones depending on the exact buffer setup inside `neovim`

**Is there a way to close and kill the `toggleterm` buffers to quit `neovim` without any errror?**

**Comment by a2n-s** [comment]
Okey, so I removed everything from my `init.lua` file inside `~/.config/nvim`.

When I open a terminal but toggle it away without killing it:
     - I definitely have the issue with `:wqa!`
     - not with `:q!`, `:wq!` and `:qa!`

When I open a terminal and do not hide it:
     - `:wqa!` gives an error
     - `:q!` and `:wq!` close the terminal buffer
     - `:qa!` works.

**Comment by a2n-s** [comment]
I would like to find a way to have 2 quit options:
- one that saves all the buffers and quits, the soft one
- and one that force everything and closes without saving the edited and unsaved buffers.
- 
And the toggleterm terminals too ;)

**Comment by a2n-s** [comment]
No idea about the bug...
It does seem to come from `toggleterm` as it appears even with `toggleterm` only :thinking: 

However, I think I have a nice solution:
- **replace `:wqa!` with `:qa!` for the soft quit**: it quits if no unsaved buffer, throws the E37 error and switches to the buffer. I cant then just save with `:wa!` or `:w` and quit, which is perfect
- **let `:qa!` for the hard quit**: this justs works and quit without saving!

The fix is [here](https://github.com/a2n-s/neovim/commit/1cab8a28bb96489d716614efd92062faf58b5c0b#diff-18b7e49fb27f4cb83ac8f7539cde0cb872584df97ed10fa4d17e76abcab93e7d) inside the `whichkey` config file.

Feel free to close this, even if I do not give any answer to the base problem :wink:

**Comment by ravenxrz** [comment]
> No idea about the bug... It does seem to come from `toggleterm` as it appears even with `toggleterm` only 🤔
> 
> However, I think I have a nice solution:
> 
> * **replace `:wqa!` with `:qa!` for the soft quit**: it quits if no unsaved buffer, throws the E37 error and switches to the buffer. I cant then just save with `:wa!` or `:w` and quit, which is perfect
> * **let `:qa!` for the hard quit**: this justs works and quit without saving!
> 
> The fix is [here](https://github.com/a2n-s/neovim/commit/1cab8a28bb96489d716614efd92062faf58b5c0b#diff-18b7e49fb27f4cb83ac8f7539cde0cb872584df97ed10fa4d17e76abcab93e7d) inside the `whichkey` config file.
> 
> Feel free to close this, even if I do not give any answer to the base problem 😉

I wrote a function:
```
function SaveAndExit()
    -- wirte all buffers first
    vim.api.nvim_command(":wa")
    -- quit all buffers
    vim.api.nvim_command(":qa")
end
```
and set a keybinding(ZZ, in my case) to it.

Now the whole program will exit when I type ZZ.

**Comment by kohane27** [comment]
Original I had `vim.keymap.set("t", "<A-c>", [[<C-\><C-n><C-W>c]], opts)`. But I realized it was not "terminating" the terminal but merely hides it.

To reproduce:

1. Have the following config:

```
vim.keymap.set("t", "<A-c>", [[<C-\><C-n><C-W>c]], opts)
```

2. Spawn a toggleterm with `<cmd>ToggleTerm<CR>`

3. Try to quit nvim with `:wq`

4. The following error occurs:

```
E948: Job still running
E676: No matching autocommands for buftype= buffer
```

![2023-04-26-11-37-08](https://user-images.githubusercontent.com/57322459/234464111-4108670b-2b57-4484-8c3e-ddb5a6037786.png)

## Solution

I now use `vim.keymap.set("t", "<A-c>", [[<Cmd>q!<CR>]], opts)` to force quit toggleterm window.

Full config:

```lua
function _G.set_terminal_keymaps()
  local opts = { buffer = 0, noremap = true }

  -- force close without prompting
  vim.keymap.set("t", "<A-c>", [[<Cmd>q!<CR>]], opts)
end
```

Cheers!

**Comment by sand4rt** [comment]
I have the same problem. Can this be reopened?

**Comment by A-caibird** [comment]
I have the same problem. Can this be reopened?
<img width="372" alt="image" src="https://github.com/user-attachments/assets/15d0251a-83ca-4432-b87b-610687bf0b1f" />

my config
<img width="596" alt="image" src="https://github.com/user-attachments/assets/9cabaee7-f734-44ec-9cd3-820e96ad1917" />

**Comment by A-caibird** [comment]
> No idea about the bug... It does seem to come from `toggleterm` as it appears even with `toggleterm` only 🤔
> 
> However, I think I have a nice solution:
> 
> * **replace `:wqa!` with `:qa!` for the soft quit**: it quits if no unsaved buffer, throws the E37 error and switches to the buffer. I cant then just save with `:wa!` or `:w` and quit, which is perfect
> * **let `:qa!` for the hard quit**: this justs works and quit without saving!
> 
> The fix is [here](https://github.com/a2n-s/neovim/commit/1cab8a28bb96489d716614efd92062faf58b5c0b#diff-18b7e49fb27f4cb83ac8f7539cde0cb872584df97ed10fa4d17e76abcab93e7d) inside the `whichkey` config file.
> 
> Feel free to close this, even if I do not give any answer to the base problem 😉

Do you know how to fix it, thanks?

**Comment by Elite-zx** [comment]
```lua
	local function SaveAndExit()
		-- wirte all buffers first
		vim.api.nvim_command(":wa")
		-- close all buffers first
		vim.api.nvim_command(":qa")
	end
	vim.api.nvim_create_user_command("Wqa", SaveAndExit, {})
	vim.api.nvim_set_keymap("c", "wqa", "Wqa", { noremap = true, silent = false })
```
