### ISSUE TITLE
Lazygit complains 'Not enought space to render panels'

### ISSUE THREAD

**Issue by Bekaboo** [akinsho/toggleterm.nvim#156]
## My config:

```lua
require('toggleterm').setup{
  -- size can be a number or function which is passed the current terminal
  size = function(term)
    if term.direction == "horizontal" then
      return 10
    elseif term.direction == "vertical" then
      return vim.o.columns * 0.4
    end
  end,
  start_in_insert = false,
  shade_terminals = false,
  open_mapping = [[<C-\>]],
  terminal_mappings = true, -- whether or not the open mapping applies in the opened terminals
  persist_size = true,
  direction = 'horizontal',
  float_opts = { width = 150, height = 40 }
}

local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({
  cmd = 'lazygit',
  hidden = true,
  start_in_insert = false,
  dir = 'git_dir',
  direction = 'float',
  float_opts = {
    border = { '╒', '═', '╕', '│', '╛', '═', '╘', '│' },
    width = 150,
    height = 40
  },
  -- function to run on opening the terminal
  on_open = function(term)
    vim.api.nvim_buf_set_keymap(term.bufnr, 'n', 'q', '<cmd>close<CR>',
                                {noremap = true, silent = true})
    vim.api.nvim_buf_set_keymap(term.bufnr, 'n', '<esc>', '<cmd>close<CR>',
                                {noremap = true, silent = true})
    vim.api.nvim_buf_set_keymap(term.bufnr, 'n', '<C-\\>', '<cmd>close<CR>',
                                {noremap = true, silent = true})
  end
})

function Lazygit_toggle()
  lazygit:toggle()
end

vim.cmd [[ command Git lua Lazygit_toggle()<CR> ]]
```
Notice that I do not have `vim.cmd('startinsert')` in the `on_open` function.

## Actual Behavior
When you open a vertical or horizontal terminal that is not wide/high enough and then call the `Lazy_toggle()` function with your cursor in the vertical terminal, lazygit will complain there's no space for panels. After entering the terminal mode (insert mode) by manually hitting 'i', lazygit displays normally.

https://user-images.githubusercontent.com/76579810/154117823-8837007d-dca0-48e7-afaa-3783746517bc.mp4

## Expected behavior
lazygit displayed normally in the floating window without entering terminal mode.

**Comment by akinsho** [comment]
@Bekaboo I'm not sure exactly where the issue relating to toggle term comes in to things, `lazygit` is its own program with its own rules around sizing. I don't know how it detects sizes or what the required sizes are or what version you are on and how behaviour changes between versions. I currently don't see this issue, but importantly, I don't manually set the size of the float. If you do and lazygit thinks it's too small, I'm not sure that this is a problem for toggleterm to solve since it is agnostic of the program you are running within the terminal 🤷🏿
