### ISSUE TITLE
There's no way to exit vim in terminal

### ISSUE THREAD

**Issue by yesmeck** [akinsho/toggleterm.nvim#158]
Sorry it's more like a question than a issue, but it seems there's no way to exit vim that accidentally opened in terminal (e.g git commit opens vim). When I input `:q` in normal mode, the command is send to the host vim.

**Comment by akinsho** [comment]
@yesmeck can you clarify the problem a bit more, I'm not sure if I understand. Do you mean that a nested nvim session is being created inside the toggle term? there are tools to prevent nesting such as `neovim-remote` which is built by a vim contributor and prevents nvim sessions from being nested

**Comment by yesmeck** [comment]
Thanks @akinsho, neovim-remote solves my problem.
