### ISSUE TITLE
[Question]: Command to explicitly close or open

### ISSUE THREAD

**Issue by ByteDrummer** [akinsho/toggleterm.nvim#160]
Just wondering, are there are any commands that I can run to explicitly open or close the terminal as opposed to toggling? I know older versions had them, but I can't seem to find them in the README.

**Comment by akinsho** [comment]
@ByteDrummer you can explicitly close all terminals using `ToggleTermToggleAll!` with a `!` at the end. You can also target specific terminals using their terminal number, e.g. `2ToggleTerm`. If you'd like to contribute a PR to implement anything more granular we can discuss it further, but otherwise I'm going to leave things as is.

**Comment by ByteDrummer** [comment]
`ToggleTermToggleAll!` seems to also open the terminal, not just close.

**Comment by tklebanoff** [comment]
hi folks! first off, nice plugin! the idea of having lua terminal objects which can be pre-configured and toggled is wizard!

i think i have a related issue to OP

in the readme (which is great), it says we can do:
`function _G.set_terminal_keymaps()
  local opts = {noremap = true}
  vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', 'jk', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-h>', [[<C-\><C-n><C-W>h]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-j>', [[<C-\><C-n><C-W>j]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-k>', [[<C-\><C-n><C-W>k]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-\><C-n><C-W>l]], opts)
end

vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')`

this almost solves one problem i was having.  before including this code, when i press one of hjkl after the terminal command runs, the buffer automatically closes.  this isnt the behavior i want, but i like the fact that i can run the toggle command again and it will rerun the associated shell command.

when i include the code above, the first problem goes away -- i can then use hjkl to move around, yank, visually select, etc as i expect.  

however, now something else happens which seems like it might be a bug to me:

If I close that buffer and then relaunch the command (perhaps with a different input) it simply shows the previously closed buffer without running anything!

maybe if there was a way to explicitly close the terminal i could just use that and get the benefits of being able to hjkl around inside the completed command buffer, as well as being able to launch something new when i want it next.

what do you think?  Is there a way to fix my problem? I hope i was able to adequately explain what i am experiencing

**Comment by tklebanoff** [comment]
basically i want to include those keymappings so that i can hjkl around, but then have it so that when i close the buffer with :q it actually destroys the buffer.  

i suppose i could also use a command to explicitly close the buffer (which is why i kept this question on the thread)

**Comment by akinsho** [comment]
@tklebanoff thanks for the kind words 👍🏿 

If I understand your issue, there are a few things to note
> when i press one of hjkl after the terminal command runs, the buffer automatically closes

This shouldn't be happening, it'd be great to see a GIF of this behaviour

>If I close that buffer and then relaunch the command (perhaps with a different input) it simply shows the previously closed buffer without running anything!

This also doesn't sound right, what command are you using. I just tried `TermExec cmd='<MyCommand>'` and this works fine repeatedly

Lastly `:q` is not the correct command to delete a buffer `:q` closes a *window* not deletes a buffer. To delete a buffer, you should use `:bd!`

**Comment by tklebanoff** [comment]
![bug_gif](https://user-images.githubusercontent.com/48869587/155678911-2b8cfc4f-4e50-43e7-9189-99d71aeaa8cf.gif)
here is a gif! basically, once the terminal opens, i just hit `h` on my keyboard and it immediately closes

**Comment by tklebanoff** [comment]
i am about to try :bd! instead of :q to see what happens

**Comment by tklebanoff** [comment]
:bd! worked! but i am definitely experiencing some unpredictable behavior...  now i am noticing that sometimes i can hjkl around and sometimes it immediately closes like in the gif

**Comment by akinsho** [comment]
@tklebanoff something strange seems to be happening in your terminal, it seems to be closing exiting immediately. It looks like you're running some command or process, which is what is quitting

**Comment by tklebanoff** [comment]
the process is very fast and exits with code 0 

basically, once it has exited, i want to be able to inspect what it has produced, move around within it, visually select things if i'd like, etc.

then, when i close the window, i want the whole thing to start fresh

**Comment by tklebanoff** [comment]
i might run that same command again at another moment on a different input.  i'd like it to regenerate the output

**Comment by tklebanoff** [comment]
thank you, btw, for helping me :)

**Comment by tklebanoff** [comment]
i am wondering if perhaps it might be a setting i have flipped somewhere in my vim config but unrelated to the plugin.  i will hunt to see what i can find

all things considered, this ability of yours to create multiple terminal objects in lua and then toggle them  on/off later will likely revolutionize my editing and automation workflows :)

big thank you 🙏

**Comment by tklebanoff** [comment]
ok! got it! what i am doing now is keeping the mappings and calling :shutdown() right before :toggle()
for my use case, that seems to be appropriate!

today, my understanding of the api is vastly improved. my eyes must have been a bit tired last night.  i think that it is great! everything is super clear and useful!

thank you for making such a system available!

To the OP: you might be able to achieve the functionality you want by calling into the api yourself via a lua function somewhere in your config, and then mapping that function somehow.  that's what i am doing and it is working like a charm.

All the best,
-Tom

**Comment by akinsho** [comment]
I'm going to close this question out, since the answer is essentially no. I get requests for a myriad of different command configurations, I'd be open to adding this open or close command as a flag on the main toggle command so anyone feel free to raise that PR, if not I'll close this out rather than it remaining here indefinitely
