### ISSUE TITLE
is there any way to set something like nowrap in a toggleterm buffer?

### ISSUE THREAD

**Issue by tklebanoff** [akinsho/toggleterm.nvim#161]
Sometimes, especially in vertical mode, the returned lines have more columns than available in the buffer and so come back chopped and messy on the screen.

I think this seems to be a more general issue with terminal mode buffers in nvim and not specifically something from toggleterm. However, I thought I'd ask to see if you knew of a fix or workaround.

**Comment by tklebanoff** [comment]
perhaps there is some way to create the terminal with a number of columns different than the number of columns in the window displaying the buffer?

**Comment by akinsho** [comment]
@tklebanoff as you point out this isn't really a toggleterm issue and is more one of how you handle terminals generally, I'd recommend something like `autocmd BufEnter * if &bt == 'terminal'  setlocal nowrap endif` as a general idea or something like that

**Comment by akinsho** [comment]
I'll close this out, since otherwise I'll forget, and I'd rather deal with it now. Hopefully the advice helps or you can find a solution elsewhere
