### ISSUE TITLE
Screen number bug after gulp

### ISSUE THREAD

**Issue by Asterovim** [akinsho/toggleterm.nvim#173]
I use neovim v0.6.1
Lastest Treesitter and OneDarkPro color (no custom config)
I use Windows Terminal and WSL2 (windows 11).

Open a file : 
![image](https://user-images.githubusercontent.com/34446820/157645899-6b2202f4-c8bc-4ce7-9a1e-35111ee6a1c8.png)

Toggle term float : 
![image](https://user-images.githubusercontent.com/34446820/157645950-4308d9c4-e5b3-47ae-be9b-ee7f03a68df3.png)

Toggle term float : 
![image](https://user-images.githubusercontent.com/34446820/157646030-c6ec7efc-59a6-42e0-b892-ee86daaef046.png)

Toggle term and use gulp : 
![image](https://user-images.githubusercontent.com/34446820/157646119-ce06cc11-6a10-4386-9737-b7aca6c8a57f.png)

Toggle term : 
![image](https://user-images.githubusercontent.com/34446820/157646212-72c8f0ad-6884-4286-8858-3d724df6cb30.png)

It's break the line : 
![image](https://user-images.githubusercontent.com/34446820/157646252-8fc3ca4e-b6df-49ee-a24a-7b8eddd37710.png)

Could you help me please ?

**Comment by akinsho** [comment]
@Asterovim I don't think this issue is with toggleterm but neovim core, this issue is around core rendering of characters in nvim which really isn't something this plugin controls, all it does is open windows with terminals in them. I think this issue is best reported upstream rather than here.
