### ISSUE TITLE
Setting it up with powershell windows?

### ISSUE THREAD

**Issue by lilheart** [akinsho/toggleterm.nvim#178]
Greetings, 
Any suggestions on how to make it set with powershell instead of CMD on windows?

**Comment by akinsho** [comment]
@lilheart I don't use Windows and am not familiar with its shells at all unfortunately

**Comment by lilheart** [comment]
Thank you for you response!

**Comment by jantari** [comment]
Ok so I got it working with the help of https://github.com/neovim/neovim/issues/15634 and `:help shell-powershell`

My Environment:

```
Windows 10 21H2 Build 10.0.19044
NVIM v0.7.0
Neovim installed through scoop in case that matters (binary is C:\Users\jantari\scoop\shims\nvim.exe)
PowerShell 7.3.0-preview.4
```

the neovim config I needed (I still use vimfile config, not LUA, sorry):

```
let &shell = has('win32') ? 'powershell' : 'pwsh'
let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
set shellquote= shellxquote=
:lua require("toggleterm").setup{}
```

after this, both `:execute termopen('powershell')` and `:ToggleTerm` just worked.

@akinsho Would you mind If I added this to the [toggleterm wiki](https://github.com/akinsho/toggleterm.nvim/wiki)? Maybe under tips & tricks?

**Comment by akinsho** [comment]
@jantari that is a great idea and really helpful for others, thanks 👍🏿

**Comment by jantari** [comment]
Well I sorta messed up putting it inside the Tips and Tricks section and now I don't know how to move it, but anyway it's there and maybe you can move it: https://github.com/akinsho/toggleterm.nvim/wiki/Using-with-PowerShell

Thank you for the great plugin, I've already enjoyed using it a lot even just today :)

**Comment by abdullah1astro** [comment]
can i add a keymap for it instead of typing :execute termopen('powershell')
