### ISSUE TITLE
Is there a way to avoid top lines removing?

### ISSUE THREAD

**Issue by lopi-py** [akinsho/toggleterm.nvim#179]
https://gyazo.com/e1a9c74c6a070ee919cf6084527b5e36

**Comment by akinsho** [comment]
This appears to be a rendering issue with the terminal itself, which is not something this plugin controls or can change. I'm going to close this out as it isn't something this plugin is doing but you can report this issue to nvim core as that is likely where it needs a fix

**Comment by akinsho** [comment]
On second thought, have you enabled `start_in_insert` that could be forcing the terminal to scroll to the bottom since you are automatically inserting.
