### ISSUE TITLE
[Question] Is there a way to whenever I toggle the terminal to be in the same directory as the buffer?

### ISSUE THREAD

**Issue by lilheart** [akinsho/toggleterm.nvim#180]
Greetings, as the title says is there a way whenever I toggle the terminal it will open the same directory at the same buffer directory I am in?

**Comment by akinsho** [comment]
There is no automatic way to do this, you can pass in the `dir` argument when opening a terminal and use expand syntax like `ToggleTerm dir='%:p:h'` will open toggleterm to the directory of the current buffer

**Comment by SamDc73** [comment]
> There is no automatic way to do this, you can pass in the `dir` argument when opening a terminal and use expand syntax like `ToggleTerm dir='%:p:h'` will open toggleterm to the directory of the current buffer

ok,  adding `dir = "%:p:h"` to the config file didn't work , are there any work around so i can open the terminal in the same directory as the buffer by default ?

**Comment by akinsho** [comment]
@SamDc73 it won't work in your config file because that will be evaluated once at startup and the directory would stay the same you need to create a mapping that using that dir, and it will re-evaluate it when you use the command

**Comment by edte** [comment]
well,but it working when i set like this
```
vim.api.nvim_set_keymap("", "<A-8>", '<cmd>execute  v:count . "ToggleTerm dir=\'%:p:h\'"<CR>', {})
```

![a](https://user-images.githubusercontent.com/50194671/179223504-2f5595a9-801d-4967-953a-972999953bdf.gif)
