### ISSUE TITLE
[Question] Is it possible to create multiple profiles?

### ISSUE THREAD

**Issue by CleoMenezesJr** [akinsho/toggleterm.nvim#183]
It would be possible to have multiple shells and be able to access them like: Ctrl + \ = zsh; Ctrl + shift + \ = bash?

**Comment by akinsho** [comment]
@CleoMenezesJr you can probably already do this yourself by creating custom terminals using the terminal API in the doc and passing in the shell as the `cmd`. I'm on mobile ATM so can't show an example but if you have a look at the custom terminals bit in the readme that should help
