### ISSUE TITLE
Size of Terminal.new

### ISSUE THREAD

**Issue by diego-rapoport** [akinsho/toggleterm.nvim#187]
Hi all,
I really would like to have `size` as an argument when we create a custom terminal. I tried to make the size bigger globally, but then it lost it's purpose because I only need a bigger size to a specific custom terminal.
Is it already possible to do it another way?

Something like
`
local customterm = Terminal.new({
    cmd = "...",
    size = 65,
    ...
})
`

**Comment by akinsho** [comment]
@diego-rapoport you can pass the size in to the terminal when you toggle it i.e. `Terminal:new({cmd = "blah"}):toggle(60)`

**Comment by diego-rapoport** [comment]
Thanks! That worked perfectly.
