### ISSUE TITLE
Failed to update the last master

### ISSUE THREAD

**Issue by tin-pham** [akinsho/toggleterm.nvim#195]
Everything else update just fine
![image](https://user-images.githubusercontent.com/20679090/162089481-c4ec63f8-673e-4214-8fa8-8919ab02f92a.png)

**Comment by tin-pham** [comment]
Anyway, i think i solved it by just reinstall it again ^ ^
![image](https://user-images.githubusercontent.com/20679090/162092800-fadeb99e-d240-4a73-9e26-21b3ea371497.png)

**Comment by primalmotion** [comment]
The master branch was renamed to `main`...
