### ISSUE TITLE
Lazygit Config

### ISSUE THREAD

**Issue by jeeeem** [akinsho/toggleterm.nvim#202]
How can I use my lazygit config with the custom terminal using toggleterm? As it is not working whenever I tried to use the custom terminal.

TUI Lazygit
![2022-04-11_21-11](https://user-images.githubusercontent.com/51053482/162746985-c54c5e50-a7b5-4dd6-bb24-59de74505ac9.png)

Toggleterm Lazygit
![2022-04-11_21-12](https://user-images.githubusercontent.com/51053482/162747030-4dfc13b8-3ba9-485d-a920-62154afaefe0.png)

As you can see I use delta for better viewing diff and the underline.

**Comment by akinsho** [comment]
@jeeeem there's no special config as part of this plugin to get lazygit to use your own config. It should do that by default. Mine uses my config inside neovim, and I've never had any issues from other users about this, so it's likely something needed tweaking in your config. Can you open a normal terminal using `:terminal` and run `lazygit` if it appears the same then this issue isn't with this plugin but likely your environment somehow, but I don't know what that would be.

**Comment by jeeeem** [comment]
> @jeeeem there's no special config as part of this plugin to get lazygit to use your own config. It should do that by default. Mine uses my config inside neovim, and I've never had any issues from other users about this, so it's likely something needed tweaking in your config. Can you open a normal terminal using `:terminal` and run `lazygit` if it appears the same then this issue isn't with this plugin but likely your environment somehow, but I don't know what that would be.

Through your reply I just realized I set another path in `XDG_CONFIG_HOME` for my neovim lua config. That is why it is not using my default lazygit config, rather it is using the path that I use for my neovim lua config which has no lazygit config.
