### ISSUE TITLE
Feature request: open a file in the host neovim

### ISSUE THREAD

**Issue by szsdk** [akinsho/toggleterm.nvim#205]
[floaterm](https://github.com/voldikss/vim-floaterm) has a shell command `floaterm` to open a file in the host session. Can we make similary command in toggleterm.nvim? Or is it there already?

**Comment by akinsho** [comment]
@szsdk I don't entirely know what exactly you mean as you haven't really detailed this functionality or how it's supposed to work, although I presume what you want can be set up using [neovim-remote](https://github.com/mhinz/neovim-remote). I think if you read through the documentation for this you will probably find what you need

**Comment by szsdk** [comment]
Yes, the `nvr -l` from neovim-remote is what I need. Please feel free to close this issue.

Sorry for not making myself clear. Please take a look at [this](https://github.com/voldikss/vim-floaterm#floaterm). Basically, it ships with a command called `floaterm` which could be used for openning file.

I found that floaterm does not require neovim-remote as depdendency. It seems that it implements something similar inside the package.

**Comment by srihari93** [comment]
For those who ran across this issue, this is the quick answer. 
The command to open the file in the host nvim is `nvim --server $NVIM_LISTEN_ADDRESS --remote-tab {filename}`

**Comment by szsdk** [comment]
Here is a bash script which opens a file in a Toggleterm:
```bash
#!/bin/bash

readpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

#realpath "$0"

if [ -z $NVIM_LISTEN_ADDRESS ]; then
    echo "This command should be used in ToggleTerm."
else
    fn=$(readpath "$1")
    nvim --server $NVIM_LISTEN_ADDRESS --remote-send "<C-\><C-n>:ToggleTerm<CR>:e ${fn}<CR>"
fi
```
The usage is simply
```bash
script.sh file_to_open
```

**Comment by ktunprasert** [comment]
Adding to this Issue I just finished configuring LazyGit to send file back to host thanks to @szsdk it's a bit hard coded so it's not perfect
```lua
local Terminal = require('toggleterm.terminal').Terminal

local lg_cmd = "lg $(pwd)"
if vim.v.servername ~= nil then
    lg_cmd = string.format("NVIM_SERVER=%s lg $(pwd)", vim.v.servername)
end

local lazygit = Terminal:new({
    count = 5,
    cmd = lg_cmd,
})

-- For Editing back from LazyGit
-- $ nvim --listen localhost:6666
-- 
-- ~/.config/lazygit/config.yml
-- os:
--   editCommand: 'nvim --server $NVIM_SERVER'
--   editCommandTemplate: "{{editor}} --remote-send '<C-\\><C-n>:5ToggleTerm<CR>:lua _edit({{filename}}, {{line}})<CR>'"
function _edit(fn, line_number)
    local edit_cmd = string.format(":e %s", fn)
    if line_number ~= nil then
        edit_cmd = string.format(":e +%d %s", line_number, fn)
    end
    vim.cmd(edit_cmd)
end

function _lazygit_toggle()
    lazygit:toggle()
end
```
I've tested this and it will work even without the `--listen` option - when I run my Neovim without that option the output of `vim.v.servername` is `/tmp/nvimirBxpY/0` which is the focused instance of your Neovim.

**Comment by KarlWithK** [comment]
Just fyi, with the latest lazygit I've noticed that I had to use local `lg_cmd = "lg -w $(pwd)"`
