### ISSUE TITLE
closing a terminal for good

### ISSUE THREAD

**Issue by kraxli** [akinsho/toggleterm.nvim#210]
Many thanks for this great plugin! :-) 

Question: when I close a terminal with `[[<C-\><C-n>]]` it disappears. Opening it again, it is at the same stage (I see the commands executed and their output) as before which is desired in most cases. Sometime I would like to close e.g. a cluttered terminal for good. Is there a way to do this?

**Comment by akinsho** [comment]
@kraxli you can just delete the buffer the same as any other buffer in neovim with `bufdelete`

**Comment by akinsho** [comment]
Closing this out since the above answers the question. Terminals are buffers just like any other so can be deleted in the exact same way as other terminals
