### ISSUE TITLE
[Question] how to escape % in TermExec / require('toggleterm').exec_command

### ISSUE THREAD

**Issue by kraxli** [akinsho/toggleterm.nvim#213]
I would like to run the current file in a ipython terminal with `F5` by sending literally `%run /path/filename.py` to the terminal . For this i would like to have sth like the follwing keymap:
```
  vim.api.nvim_set_keymap('n', "<F5>", [[<cmd>lua require('toggleterm').exec_command('cmd="' .. '%run '  .. vim.api.nvim_buf_get_name(0) .. '"', vim.v.count)<CR>]], opts)
```
However % is replaced by the file name and the command sent to the terminal ends up to be 
```
/path/filename.pyrun /path/filename.py
``` 
instead of `%run /path/filename.py`

**Comment by akinsho** [comment]
@kraxli you can escape special characters in vim commands with `\` so your example would become `\%run`

**Comment by anurag3301** [comment]
You can just try escaping it with `\%` if this doesn't work escape the `\` separately like this `\\\%`

**Comment by akinsho** [comment]
If that works, can you close this issue out 🙏🏾

**Comment by kraxli** [comment]
thanks! I have tried before `\%` which doesn't work. But `\\%` (two backslashes) works :-)
