### ISSUE TITLE
Close terminal after executing command

### ISSUE THREAD

**Issue by anurag3301** [akinsho/toggleterm.nvim#214]
Hey I use `TermExec` as my code runner, I have the following code for executing and it works really good
```lua
local run_command_table = {
    ['cpp'] = 'g++ %:t -o %:r && ./%:r',
    ['c'] = 'gcc %:t -o %:r && ./%:r',
    ['python'] = 'python %:t',
    ['lua'] = 'lua %:t',
    ['java'] = 'javac %:t && java %:r',
    ['zsh'] = 'zsh %:t',
    ['sh'] = 'sh %:t',
    ['rust'] = 'rustc %:t && ./%:r',
    ['go'] = 'go run %:t'
}

function run_code()
    if (run_command_table[vim.bo.filetype]) then
       vim.cmd('2TermExec cmd="'.. run_command_table[vim.bo.filetype]..'" direction=float')
   else
       print("\nFileType not supported\n")
   end
end

```

But after the execution, it just drops to next shell prompt.
![image](https://user-images.githubusercontent.com/52702259/165053328-686709ad-872a-490e-b78a-4511a4e85978.png)

Is it possible to make the terminal execute the command and instead of dropping to next shell prompt, ask user to press ENTER and as user press ENTER the terminal closes.

**Comment by akinsho** [comment]
@anurag3301 I think you can solve this in your config by just adding ` | exit` or something to your command not sure that pipe will work maybe it's more like `;exit` not sure but either way I think this can be solved in your config without any change in this plugin. You can experiment with some solution till you find the best one, but I don't think there's a safe general way that this plugin could or should intervene. I think this kind of use case should be done in users configs since the plugin is completely agnostic to what sort of thing the user is doing in the terminal

**Comment by anurag3301** [comment]
Hey @akinsho Thank for you brilliant suggestion, added this `extra` string to do all those stuff, you can have a look.
```lua
local run_command_table = {
    ['cpp'] = 'g++ %:t -o %:r && ./%:r',
    ['c'] = 'gcc %:t -o %:r && ./%:r',
    ['python'] = 'python %:t',
    ['lua'] = 'lua %:t',
    ['java'] = 'javac %:t && java %:r',
    ['zsh'] = 'zsh %:t',
    ['sh'] = 'sh %:t',
    ['rust'] = 'rustc %:t && ./%:r',
    ['go'] = 'go run %:t'
}

local extra = 'echo \"\\\\n\\\\033[0;33mPlease Press ENTER to continue \\\\033[0m\"; read; exit;'

function run_code()
    if (run_command_table[vim.bo.filetype]) then
       vim.cmd("2TermExec cmd='".. run_command_table[vim.bo.filetype].."; " .. extra .. "' direction=float")
   else
       print("\nFileType not supported\n")
   end
end

```
Figuring out the escape sequence for `\` was pain, had to escape a symbol twice one for lua then one for vim. Anyway the result
![image](https://user-images.githubusercontent.com/52702259/165145977-fe43e25c-01ce-44c9-a6be-9665e9845ef1.png)
It Exits as you press ENTER. Thank you :)

**Comment by akinsho** [comment]
Nice, glad it worked, I've been thinking of adding a wiki to this plugin, so people can share things like this. I'll enable it now and if you want to post this in there please feel free 👍🏿 . Otherwise, I'll close this out

**Comment by milanglacier** [comment]
there is a vim function called `vim.fn.shellescape`, may be you can try to call that function and see if it can reduce some extent of annoying escapes to make it more readable.
