### ISSUE TITLE
How to scroll

### ISSUE THREAD

**Issue by anurag3301** [akinsho/toggleterm.nvim#220]
Just a quick question, how can you scroll up and down in the terminal. Is there a key binding for that?

**Comment by akinsho** [comment]
@anurag3301 it's just a normal vim buffer so you can scroll it the normal way you would scroll a vim buffer. You can go inside the buffer and do something like `<C-U>` or `<C-D>` etc.

**Comment by anurag3301** [comment]
Um dont work, `<C-U>` is I suppose `Ctrl+u` but does nothing and `<C-D` kills the terminal. Do I have to do the `insert` or `normal` mode thing for the terminal cuz currently it's just a standard terminal with no vim modes.

**Comment by akinsho** [comment]
@anurag3301 you have to be in normal mode to use those command. This question is more about usage of vim and default terminal behaviour and isn't really specific to this plugin. I suggest searching for answers in the help there  isn't anything special about scrolling related to this plugin

**Comment by anurag3301** [comment]
Sure I'll look into it and figure this out, Thanks for your help. :)

**Comment by anurag3301** [comment]
Hey @akinsho so I figured out `  start_in_insert = true,` setting this to false, the terminal will spawn in normal mode and I am able to do all the vim stuff and scrolling. But as I press `i` get into insert, I am not able to get back to normal mode with the `Esc` key. Is there some other key for that?
Or maybe I have to add something to my config
```lua
-- include toggleterm
require('toggleterm').setup{
  size = 15,
  open_mapping = '<F1>',
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = 1,
  start_in_insert = true,
  insert_mappings = true,
  persist_size = true,
  direction = 'horizontal',
  close_on_exit = true,
  shell = vim.o.shell, -- change the default shell
}

```

**Comment by akinsho** [comment]
@anurag3301 I really strongly suggest you read `:help terminal-input` in the terminal mode, `Esc` doesn't work to leave insert mode you need to press a specify key for that, and you can remap it in your config. This is all just things about how neovim's terminal works, quite separate to this plugin. I think it's important to read that section when working with any terminal inside neovim.

I don't think start in insert is the problem, I think getting your head around what is terminal mode and how to switch modes in the terminal is the key thing here.

**Comment by anurag3301** [comment]
@akinsho Thanks a lot, this was `Use <C-\><C-N> to return to normal-mode` all I needed. I'll read the rest of the terminal man pages.

**Comment by akinsho** [comment]
@anurag3301 I don't use `Esc` in terminal I use something like `jj` or `jk` I think the help docs explains why you shouldn't use it.
