### ISSUE TITLE
Update colorsscheme and background of fly

### ISSUE THREAD

**Issue by Liverm0r** [akinsho/toggleterm.nvim#223]
When I set colorscheme with Telescope or `:colorscheme <name>`, theme is not applied to a hidden Toggle-term window. If toggle-window is opened, theme will be applied, but after toggling it the previous theme will reappear in the toggle-term window.

Currently I fixed it with applying `:on_open` function, where I check current theme and set it. Don't know if it's a bug. 

My config looks like (it's fennel, but it's readable I guess):

```fennel
(module plugin.toggleterm
  {autoload {nvim aniseed.nvim
             term toggleterm
             t    toggleterm.terminal}})

(defn update-bg []
  (set nvim.o.background nvim.o.background)
  (vim.api.nvim_command (.. "colorscheme " nvim.g.colors_name)))


(term.setup 
  {:size 25
   :open_mapping "•" ; alt + 8 (cmd + 8 from karabinner)
   :hide_numbers true
   :shade_terminals false
   :shading_factor 2
   :on_open update-bg
   ;:start_in_insert false
   :insert_mappings true
   :terminal_mappings true
   :direction :horizontal
   :persist_size true})

```

**Comment by akinsho** [comment]
fixed by #231
