### ISSUE TITLE
Toggletermin splitting; implementation of terminal offset possible?

### ISSUE THREAD

**Issue by mosmuell** [akinsho/toggleterm.nvim#225]
Hi there,
I experimented with the terminal splits, particularly doing it horizontally. As of now, the terminal will be opened through `open_split(size, term)` (in `ui.lua`) which will open a split with `vim.cmd(...)` where the parameter is given in the `split_commands` variable.
Opening a horizontal terminal will call `vim.cmd("botright split")` which just splits the whole window. When using nvim-tree, this is annoying as I would like to have the file tree remain on the left and only my windows where I edit the files to be split. This can be implemented using `vim.cmd("rightbelow split")`. However, with this you will only split the window you are working on (if you have another vertical split for example). As I'm not using vsplits that often I prefer that option anyway.

I was now wondering whether you could implement a variable in the config that would allow you to choose between those two methods (`"botright"/"rightbelow"`) or even do something like implementing an offset like in bufferline.nvim where you can specify where toggleterm should not split the window (something like `offsets = {{filetype = "NvimTree"},...}`)?

**Comment by akinsho** [comment]
@mosmuell I *really* do not want to add custom config options geared at sidebar panels as this is truly a nasty rabbit hole as I have now learned with bufferline and I definitely don't want to bring that trouble to toggleterm. I think exposing window commands will make things more complicated to maintain in the long term. This has been raised by other users who came up with workarounds please see https://github.com/akinsho/toggleterm.nvim/issues/97

**Comment by mosmuell** [comment]
Thanks for the quick answer and the reference to the other issue. I was also suspecting that there might be many rabbit holes coming along with that.
