### ISSUE TITLE
Extra  cmd text on top of prompt

### ISSUE THREAD

**Issue by anurag3301** [akinsho/toggleterm.nvim#226]
Hey @akinsho I use TermExec as a coderunner, everything works fine except when I call TermExec there is a repetition of my command at the top before the shell prompt
![image](https://user-images.githubusercontent.com/52702259/168947685-e1e4ba10-f3f1-4655-a0bb-bd1b0c02c2d2.png)

I am using following command to call TermExec.
```lua
       vim.cmd("2TermExec cmd='go run test.go; echo "\n\033[0;33mPlease Press ENTER to continue \033[0m"; read; exit;' direction=float")
```
Can you please tell me how I can remove that line at the top?

**Comment by akinsho** [comment]
@anurag3301 thanks for reporting, haven't had much time to investigate though just mentioning that I've seen your issue 👍🏿

**Comment by akinsho** [comment]
@anurag3301 you could just set your shell for that terminal to use `bash` e.g. `Terminal:new {shell = 'usr/bin/bash'}` or something which will probably run quite fast and prevent this issue

**Comment by akinsho** [comment]
Gonna close this out since I don't think this is something I can fix easily and is more a userland issue.
