### ISSUE TITLE
Question: how to escape/write cmd-argument to run under Linux and Windows 

### ISSUE THREAD

**Issue by kraxli** [akinsho/toggleterm.nvim#236]
I would like to execute the command `run "<full_file_path>"` in an ipython instance of a toggleterm-terminal. The following works perfectly under Linux
```
    local run = 'run' 
    local count = 1 
    local exe_cmd_str = [[cmd=']] .. run .. [[ "]] .. vim.api.nvim_buf_get_name(0) .. [["']]
    require('toggleterm').exec_command(exe_cmd_str, count)
```
However, on Windows only `nil` is passed to the ipython instance in the toggleterm-terminal. How would I need to escape or set-up the string such that it works under Linux and Windows?

**Comment by akinsho** [comment]
@kraxli the short answer is I have no idea I'm primarily a mac and Linux user and have never developed on a Windows machine, so I have no idea how any of it works with paths or any of that, tbh all windows related code in this plugin has been contributed by Windows users of this plugin I have no idea about any of it personally. I'm guessing you read through past issues and tried things like using `\` etc?

**Comment by kraxli** [comment]
`vim.opt.shellslash = true` solves the issue :-) - I thought this has been tackled in #110

**Comment by akinsho** [comment]
Going to close this out then
