### ISSUE TITLE
Pass in Current File when Opening a Custom Terminal

### ISSUE THREAD

**Issue by experiacc** [akinsho/toggleterm.nvim#241]
hi, 
I wanted to know how can i pass in currently opened file when opening custom terminals.
So far I've tried doing something like this 
![image](https://user-images.githubusercontent.com/82676586/173572683-843ea959-da44-4ca0-bf0d-44ff9c57f9ce.png)
but it didn't work.
thanks

**Comment by experiacc** [comment]
I was already aware of TermExec (and it works) but it opens the full terminal with shell prompt whereas i just want to run a single process and then quit on execution.
The custom terminal thing was perfect for my usecase if only it was possible to pass in the file.
But if that's not the case, I can make do with TermExec as you said 😄

**Comment by akinsho** [comment]
@experiacc I think you can work something like this out in your config but I'd suggest something like create the new terminal inside a function which will re-evaluate the command every time then use the close on exit boolean or something. I don't know exactly what the effect you are trying to achieve is but you can do some experimenting in your config to see what works 🤷🏿

**Comment by experiacc** [comment]
okay, so how can i autoclose the :TermExec spanned terminal if the process exists successfully. sorry if this is too obvious

**Comment by experiacc** [comment]
Ok I finally figuered it out, the command I was trying to run was just getting executed without giving any process exit code with TermExec. All I had to do was modify the command outside of neovim to terminate. Thanks for the help and this great plugin @akinsho 😄
