### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by justleoo** [akinsho/toggleterm.nvim#242]
hello! is possible activate a theme with toggle term?? theme: https://github.com/itsook/ok.nvim, if possible, how?

**Comment by akinsho** [comment]
@justleoo custom themes per window is not supported in neovim yet so this plugin cannot do that

**Comment by justleoo** [comment]
ah, thank you

**Comment by rafaelpirolla** [comment]
Out of curiosity, if I open a :terminal, it seems that the theme is the one I'm using in neovim, all fine – transparency and all.
But if I open the terminal using ToggleTerm then the theme seems to be stuck at a black background and transparency doesn't affect it – using iTerm2 on MacOS.
