### ISSUE TITLE
Wrong indent when a complex section is sent to ipython

### ISSUE THREAD

**Issue by szsdk** [akinsho/toggleterm.nvim#243]
The python code I want to send:
```python
def f():
    for i in range(12):
        pass
    return i
```
The python code shown in ipython:
```
In [1]: def f():
   ...:     for i in range(12):
   ...:         pass
   ...:         return i
   ...:
```
If I directly copy the code, result is correct.

**Comment by akinsho** [comment]
@szsdk the send selection logic is user contributed and best effort. I don't actively maintain that logic myself. Feel free to have a go at fixing it you'd like though

**Comment by etjupm** [comment]
This comes from ipython's autoindent feature. For an immediate solution, you can invoke ipython with the `--no-autoindent` flag and then redefine the send-code commands to not trim leading and trailing whitespace:
```lua
vim.api.nvim_create_user_command("ToggleTermSendCurrentLine",
  function(opts)
    send_term("single_line", false, opts.args)
  end,
  { nargs = "?", force = true }
)
vim.api.nvim_create_user_command("ToggleTermSendVisualSelection",
  function(opts)
    send_term("visual_selection", false, opts.args)
  end,
  { range = true, nargs = "?", force = true }
)
vim.api.nvim_create_user_command("ToggleTermSendVisualLines",
  function(opts)
    send_term("visual_lines", false, opts.args)
  end,
  { range = true, nargs = "?", force = true }
)
```

Note, the second argument to send_term() is a boolean that determines whether or not to trim whitespace. Note also that you can define new user commands instead of overwriting them by using new names for the first argument to nvim_create_user_command() and setting `force = false` in the opts table, e.g.
```lua
vim.api.nvim_create_user_command("ToggleTermSendCurrentLineNoTrimWs",
  function(opts)
    send_term("single_line", false, opts.args)
  end,
  { nargs = "?", force = false }
)
...
```

**Comment by szsdk** [comment]
@etjupm Thanks. It works well.

**Comment by akinsho** [comment]
Gonna close this out since this seems rather specific to this use case. I guess if either of you wanted to submit a PR that had some general purpose value, that could be good 🤷🏿‍♂️

**Comment by meicale** [comment]
@etjupm @szsdk  It is cool. I encounter the same problem. I think your solution should work. But I can not figure out where the "send_term" coming from. Can you share more about this config or code snaps? It doesn't work if I just use that code. Thanks a lot!

**Comment by meicale** [comment]
> This comes from ipython's autoindent feature. For an immediate solution, you can invoke ipython with the `--no-autoindent` flag and then redefine the send-code commands to not trim leading and trailing whitespace:

> Note, the second argument to send_term() is a boolean that determines whether or not to trim whitespace. Note also that you can define new user commands instead of overwriting them by using new names for the first argument to nvim_create_user_command() and setting `force = false` in the opts table, e.g.
> 
> ```lua
> vim.api.nvim_create_user_command("ToggleTermSendCurrentLineNoTrimWs",
>   function(opts)
>     send_term("single_line", false, opts.args)
>   end,
>   { nargs = "?", force = false }
> )
> ...
> ```

@etjupm @szsdk  It is cool. I encounter the same problem. I think your solution should work. But I can not figure out where the "send_term" coming from. Can you share more about this config or code snaps? It doesn't work if I just use that code. Thanks a lot!

**Comment by jo-ap** [comment]
@meicale I guess the implementation changed. For me it worked by just changing  `send_term` to `require("toggleterm").send_lines_to_terminal`.

**Comment by schiegl** [comment]
Here is a shorter version that uses IPython's `%paste` keyword to paste in from the clipboard. This handles blank lines.

```lua
function visual_send()
	if vim.bo.filetype == "python" then 
		vim.api.nvim_feedkeys('"+y', "v", true)
		require("toggleterm").exec("%paste", 1)
	else
		-- fallback doesn't work :/
		require("toggleterm").send_lines_to_terminal("visual_selection", true, "1")
	end
end
```

@akinsho I wanted to fallback to the regular visual selection command of toggleterm. Do you know why the fallback above doesn't work?
