### ISSUE TITLE
How to scroll to the old views

### ISSUE THREAD

**Issue by invokermoon** [akinsho/toggleterm.nvim#247]
Env:
MacOS12 + iterm2

```
 local status_ok, toggleterm = pcall(require, "toggleterm")
  if not status_ok then
      return
  end

  toggleterm.setup({
      size = 20,
      open_mapping = [[<C-\>]],
      hide_numbers = false,
      shade_filetypes = {},
      shade_terminals = true,
      shading_factor = 3,
      start_in_insert = true,
      insert_mappings = true,
      persist_size = true,
      direction = "float",
      close_on_exit = true,
      shell = vim.o.shell,
      float_opts = {
          border = "curved",
          winblend = 3,
          highlights = {
              border = "Normal",
              background = "Normal",
          },
      },
  })
```

I trigger a new sub terminal in Nvim, i can work on it.
But when i tried to scroll the terminal to locate old outputs, i only could see the history commands from the terminal.
So how to scroll the sub terminal?

**Comment by akinsho** [comment]
@invokermoon the scroll history of the buffer isn't something that this plugin interacts with or controls at all. *This plugin just creates windows and puts terminals in them* it doesn't change the native functionality of the terminal at all. If you are unable to get scrollback history I'd read the terminal docs and if not there then raise an issue in core
