### ISSUE TITLE
Is there any ways to set the term's floating-window edge distance?

### ISSUE THREAD

**Issue by NEX-S** [akinsho/toggleterm.nvim#248]
I am wondering if there is any ways to config my toggleterm's floating-window's edge distance (padding)

**Comment by akinsho** [comment]
If you meant how far away the content of the window is from the border then no, unfortunately neovim does not support that

**Comment by mortymacs** [comment]
If you want to remove the left padding, you can add an event:
```lua
vim.api.nvim_create_autocmd("TermOpen", {command = "setlocal nonu nornu signcolumn=no"})
```
Command source: https://stackoverflow.com/a/63908546/2338672

**Comment by redeemefy** [comment]
> I am wondering if there is any ways to config my toggleterm's floating-window's edge distance (padding)

If what you want to to keep the terminal prompt off the edge of the screen, you could play with the colors of the theme you are using. I set the all the colors to the same color so gets the effect that the prompt its off the edge.
```lua
use({
  'akinsho/toggleterm.nvim', tag = '*', config = function()
    require("toggleterm").setup({
      direction = 'float',
      highlights = {
        NormalFloat = {
          guibg = '#292c3c',
        },
        FloatBorder = {
          guifg = '#292c3c',
          guibg = '#292c3c',
        }
      },
      float_opts = {
        height = 10,
      },
    })
  end
})
```
