### ISSUE TITLE
NormalFloat and FloatBorder are required if highlighting a floating terminal

### ISSUE THREAD

**Issue by ptwales** [akinsho/toggleterm.nvim#250]
When applying any highlighting to a floating terminal, you must provide _both_ `NormalFloat` and `FloatBorder` or else you will get an `attempt to index attrs (a nil value)` error.

Those highlights are hard coded on [ui.lua#L98](https://github.com/akinsho/toggleterm.nvim/blob/ce755e3a07f2464287dc60ed448fdbbe6ea157f5/lua/toggleterm/ui.lua#L98) and aren't checked if they are nil on [ui.lua#L103](https://github.com/akinsho/toggleterm.nvim/blob/ce755e3a07f2464287dc60ed448fdbbe6ea157f5/lua/toggleterm/ui.lua#L103)

Example
```lua
local toggleterm = require "toggleterm"
toggleterm.setup {}
local Terminal = require("toggleterm.terminal").Terminal
local lazygit = Terminal:new {
    cmd = "lazygit",
    direction = "float",
    highlights = {
        -- Comment or un-comment these to see behavior.
        NormalFloat = { link = "PMenu" },
        -- FloatBorder = { link = "PMenu" },
    },
    hidden = true,
}

local toggle_lazygit = function()
    lazygit:toggle()
end

keys.nmap("<leader>gT", toggle_lazygit, {})
```

**Comment by akinsho** [comment]
@ptwales can you try #257 , there is logic already to add defaults for each of those groups which is why they are used without `nil` checks but could be the fallbacks are not being set so I've adjusted the logic now so that `nil` should default to a default highlight.
