### ISSUE TITLE
Toggleterm not working with Windows Powershell

### ISSUE THREAD

**Issue by gabrielkryss** [akinsho/toggleterm.nvim#251]
Hi, first let me describe my environment:

- using Windows 11
- Pwershell as my default terminal 
![image](https://user-images.githubusercontent.com/20222391/174957521-041d6a88-3bf4-422c-9bcd-87aa14d7f9cf.png)
- using nerovide on Windows not wsl
- running nvim on neovide on Windows
- using nvim 0.8.0

I installed the plugin and when I bring up the terminal it shows the following

![image](https://user-images.githubusercontent.com/20222391/174957433-850cd579-1784-4140-997f-85cb1bdc1003.png)

I explored some other solutions like setting my `vim.opt.shell="bash"` in hopes to use git-bash instead but it yielded the same result.

I know the ultimate solution is to use wsl but I wanted to ask here before I do that.

**Comment by gabrielkryss** [comment]
Oh nvm, I figured it out I just need to comment out my `vim.opt.shell` statement and just not use it at all it seems like, it makes sense cuz the official docs says its depricated it seems

![image](https://user-images.githubusercontent.com/20222391/174961384-646b42f9-1461-4c15-bb48-44d5c5b40f10.png)

but anyway it works now.

**Comment by azinsharaf** [comment]
@gabrielkryss Hi Gabriel, How do we dictate which shell we want to use in Toggle Term? I have fish installed on my Cygwin env.
I defined a $SHELL env var but didn't work.
