### ISSUE TITLE
Minimal setup :ToggleTerm opens split for 0.5s and then closes. 

### ISSUE THREAD

**Issue by Normanras** [akinsho/toggleterm.nvim#255]
The title says it all, I followed the instructions for a minimal setup using Packer. With no other files or configuration, when I use the command `:ToggleTerm`, I see the terminal split open for half a second and then it closes. It closes too quickly for me to interact with it. 

My default shell is fish. I read the docs 3x over and didn't see anything about fish shell causing issues, or anyone else having this specific issue. I tried adding `shell = '/usr/local/bin/fish` to my config, but that didn't solve the issue. 

I'm sure it's interacting with another plugin, but I looked through standard keymaps and can't seem to find something that would be triggering an auto-close like that.

**Comment by akinsho** [comment]
@Normanras have you tried another shell to see if it relates to fish. I know there are a lot of fish related issues in neovim and vim. I don't use it nor do I know much about it so can't really advise you. I'd suggest trying to open neovim's terminal as normal without this plugin and see how that behaves as well

**Comment by Normanras** [comment]
The standard terminal doesn't really work. It opens and throws a "process exited" immedieatly. Which I assume is what is happening with ToggleTerm since it uses the same terminal. 

I looked through a few other's `toggleterm.lua` config's and got it working. Then I updated my `keymaps.lua` and it stopped working again - same issue. I don't know how this could help neovim as a whole, but if I open the terminal in zsh, everything works as planned - including ToggleTerm. I can then run `/usr/local/bin/fish` and despite some weird font/color issues, fish works without issue for now. But there's something about opening it directly in fish that causes issues. 

I'll keep messing with my config. If I find an answer enough for a PR, I'll reach out.

**Comment by akinsho** [comment]
@Normanras thanks for documenting your findings. I'm not sure if that should be part of the docs since I don't know what exactly is happening anyway, so not sure if it's advice I should give since I don't know what it means. Anyway, I'll close this out and maybe other people can find it in the future.

**Comment by azinsharaf** [comment]
hi @Normanras ,
Did you figure it the reason this issue happens? 
I am using Fish (in Cygwin) and experiencing same issue in Astronvim when i use Toggleterm.
