### ISSUE TITLE
Floating terminal bottom borderline is not rendered

### ISSUE THREAD

**Issue by haluk** [akinsho/toggleterm.nvim#258]
I'm using neovim compiled from master branch. When I toggle the floating terminal, it's bottom borderline is not rendered. I didn't have this problem with neovim 0.7.

![image](https://user-images.githubusercontent.com/183110/177195644-ef96a3a6-012a-4df5-9627-50aea2a8ac05.png)

**Comment by akinsho** [comment]
@haluk, have you enabled winbar globally, by any chance? This doesn't reproduce under normal circumstances. If you have then you'll need to figure out how to disable it in toggleterm in your config, at least until nvim core fix its usage in floats

**Comment by akinsho** [comment]
Going to close this out as this is not reproducible without using winbar which is known to have this bug
