### ISSUE TITLE
Can't close terminal: `Couldn't find a terminal to close`

### ISSUE THREAD

**Issue by sinnrrr** [akinsho/toggleterm.nvim#261]
When I am opening the `nvim` for the first time, when I press `C-t` and then `C-t` again to close, I am ended up with two terminal windows. When pressing `C-t` for the third time - closes one of them, but doing this again causes the error. See video.

https://user-images.githubusercontent.com/25615887/178107109-c420ee1b-ff44-4407-873c-4aad8e648e45.mov

In the end, I am clicking on the terminal to focus on it, and `ZZ` to close it. After that, it works as expected: `C-t` toggles it on and off.

**Comment by akinsho** [comment]
@sinnrrr can you share your config or does this reproduce without one?

**Comment by sinnrrr** [comment]
@akinsho sure, https://github.com/sinnrrr/dotfiles/tree/macos/lvim/.config/lvim

**Comment by akinsho** [comment]
@sinnrrr can you just share the snippet that causes this issue just the few lines off code needed, not the entire config 🙏🏾

**Comment by sinnrrr** [comment]
@akinsho oh, I am really sorry for this
https://github.com/sinnrrr/dotfiles/blob/macos/lvim/.config/lvim/lua/options/toggleterm.lua

here is my config for `toggleterm`

`.active` is for lunarvim to know if I still need toggleterm, or lunarvim can remove it

**Comment by akinsho** [comment]
@sinnrrr lunar vim is a layer on top of this plugin. This plugin exposes a setup function. what I need is the exact settings that go into that. Do you know how this plugin is set up in a minimal environment without lunarvim if so can you just paste the setup call for this plugin. What you linked still involves some layer of abstraction from this plugin

**Comment by sinnrrr** [comment]
okay, [here](https://github.com/LunarVim/LunarVim/blob/6d43a7946489764b57d2771fcfba260109ef984b/lua/lvim/core/terminal.lua#L5) is the setup config options and [here](https://github.com/LunarVim/LunarVim/blob/6d43a7946489764b57d2771fcfba260109ef984b/lua/lvim/core/terminal.lua#L50) it `.setup()` function call

**Comment by akinsho** [comment]
@sinnrrr these are really large files with a bunch of comments can you please just just figure out on your side exactly what settings trigger this issue in just a few lines and paste that. I have many issues in many plugins to fix. It makes things very hard for me to try and dig it a user's specific config at minimum I need each user reporting an issue to share exactly the minimum code to show their problem without any frameworks

**Comment by sinnrrr** [comment]
@akinsho seems like this is a problem on my end (something in config triggers terminal duplication), I have run a clean LunarVim config and this problem doesn't exist there. Sorry for wasting your time...

Thank you very much for such a great project!
