### ISSUE TITLE
Last neovim unstable update.

### ISSUE THREAD

**Issue by ElcomJ** [akinsho/toggleterm.nvim#263]
Good Morning.

I am using the unstable version of neovim, and in the update that occurred today, when I went to open my neovim, it complained about some deprecated terms in the toggleterm as seen in the images below:
![Captura de tela de 2022-07-10 11-09-52](https://user-images.githubusercontent.com/37147897/178148493-713beac6-7f1a-490f-9a01-6f54add28099.png)

![Captura de tela de 2022-07-10 11-10-08](https://user-images.githubusercontent.com/37147897/178148563-c3603284-217e-4585-b87e-da0d02f76e78.png)

Even though it has these errors, your plugin works normally, but I would like to know how I could fix this error, or if you will make an update about these deprecated terms?

**Comment by akinsho** [comment]
@ElcomJ seems you are using an old version of this plugin since I dropped the usage of the method a while ago. Can you make sure your version is up-to-date and see if the error is still there afterwards

**Comment by ElcomJ** [comment]
@akinsho I just used vim.plug to be able to update all my Plugins, and I am using the latest version yes.

But still the error continues :(

Can you tell me how I can fix this problem ?

**Comment by akinsho** [comment]
@ElcomJ did you change the tag for this plugin. Can you please post how you install the plug-in. What line are you using?

**Comment by ElcomJ** [comment]
@akinsho I use the same one that is indicated for use in the Readme on github.

Github:
![Captura de tela de 2022-07-10 12-22-26](https://user-images.githubusercontent.com/37147897/178151234-a7dda01f-c2cf-448e-8085-f40cc80bd320.png)

Mine:
![Captura de tela de 2022-07-10 12-24-25](https://user-images.githubusercontent.com/37147897/178151249-4a5ad3bc-905c-4d32-bb3b-04b77d7545eb.png)

**Comment by akinsho** [comment]
@ElcomJ try updating the plugin again, I just pushed a new tag. The last tag was old and didn't have any of the changes I made for a while. I'll re-open if it's still broken

**Comment by ElcomJ** [comment]
@akinsho It worked! :)

Thanks for the quick help and congratulations on your great plugin, have a great day :)
