### ISSUE TITLE
`:ToggleTermSendVisualLines` terminal_id` got string

### ISSUE THREAD

**Issue by YuCao16** [akinsho/toggleterm.nvim#270]
Hi, I have just recently discovered that toggleterm has a send function, but I get following ERROR when I try to follow the GIF (I didn't add terminal_id) in Readme.
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/62466929/179352673-43ac11c9-2026-45b9-b02c-b20882db0a0e.png">

I tried to modify `toggleterm.nvim/lua/toggleterm.lua:204`, `set terminal_id = 1` it works.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/62466929/179352717-8b43314a-7d38-4a0f-8586-003faefc6b68.png">

I'm using Neovim 0.7.2 and latest toggleterm.nvim.

**Comment by akinsho** [comment]
This should now be fixed by 9f050333629308c80540bfa88631c9eccacbd282

**Comment by YuCao16** [comment]
> This should now be fixed by [9f05033](https://github.com/akinsho/toggleterm.nvim/commit/9f050333629308c80540bfa88631c9eccacbd282)

Thanks for your quick reply, it now works!
