### ISSUE TITLE
Wrong behavior with custom matches in Toggleterm

### ISSUE THREAD

**Issue by augustocdias** [akinsho/toggleterm.nvim#275]
Hi,

I'm trying to create a custom match to highlight trailing spaces and tabs in my windows and I would like to except toggleterm from that rule, but I'm having issues as it seems it is removing and re-adding the matches after setting the filetype.

So the idea is basically set the highlight to every new window and remove from specific filetypes as you can see in the auto commands definitions here:

```lua
local spaces_highlight_group = augroup('SpacesHighlightGroup')
autocmd({ 'VimEnter', 'WinNew' }, {
    desc = 'Highlight all tabs and trailing whitespaces',
    pattern = '*',
    group = spaces_highlight_group,
    callback = function()
        print('set')
        vim.fn.matchadd('ExtraWhitespace', '\\s\\+$\\|\\t')
        print(vim.inspect(vim.fn.getmatches()))
    end,
})

autocmd({ 'FileType' }, {
    desc = 'Remove spaces highlights in selected filetypes',
    pattern = 'help,toggleterm',
    group = spaces_highlight_group,
    callback = function()
        print('remove')
        print(vim.inspect(vim.fn.getmatches()))
        for _, match in ipairs(vim.fn.getmatches()) do
            print(match['group'])
            if match['group'] == 'ExtraWhitespace' then
                vim.fn.matchdelete(match['id'])
            end
        end
    end,
})
```

This produces the following output when I open toggleterm
```
set
{ {
    group = "ExtraWhitespace",
    id = 4,
    pattern = "\\s\\+$\\|\\t",
    priority = 10
  } }
remove
{}
```

As you can see, the ordering of the events is correct, but when it is executed the match list is empty.

It is weird because it is restored afterwards, if I execute `:lua print(vim.inspect(vim.fn.getmatches()))` I see the group defined there.

**Comment by akinsho** [comment]
@augustocdias I don't really know that this is a toggleterm issue or something I can meaningfully intervene with. I have extra whitespace highlighting in config, and it works fine without involving toggleterm. Are you sure that `toggleterm,help` as an autocmd pattern works as you expect? Anyway, really not sure that this is an issue for here rather than a config thing 🤷🏿‍♂️ 

I think other people who use toggleterm probably have this working, so maybe you can copy one of those setups, or you can try matching on the buffer name like `term://*` 🤷🏿‍♂️

**Comment by augustocdias** [comment]
well... it works for the `help` buffer. What I find specially strange is that after the event is fired the matches are set back

**Comment by augustocdias** [comment]
You're right... I have no idea what is happening.

I've put some prints inside toggleterm when it sets the filetype and look at this:

```lua
    print('term')
    print(vim.inspect(vim.fn.getmatches()))
    vim.bo[buf].filetype = constants.term_ft
    print('after')
    print(vim.inspect(vim.fn.getmatches()))
```

```
set
{ {
    group = "ExtraWhitespace",
    id = 4,
    pattern = "\\s\\+$\\|\\t",
    priority = 10
  } }
term
{ {
    group = "ExtraWhitespace",
    id = 4,
    pattern = "\\s\\+$\\|\\t",
    priority = 10
  } }
remove
toggleterm
{}
after
{ {
    group = "ExtraWhitespace",
    id = 4,
    pattern = "\\s\\+$\\|\\t",
    priority = 10
  } }
```
Only during the event the window doesn't have any match. But before and after it is there...

**Comment by augustocdias** [comment]
I figured out the reason, but not why it happens. It turns out during toggleterm activation it triggers the event in a window that is not the same from the one in toggleterm. I printed the current window in the plugin and in the event and they're different. After everything is executed the window from event doesn't exist anymore...
