### ISSUE TITLE
`hide_numbers = false` doesn't work with float terminal

### ISSUE THREAD

**Issue by ResolverJay** [akinsho/toggleterm.nvim#280]
As titled, I can't seem to get `hide_numbers = false` working with float terminal, though the other directions work fine. Is this a bug or something I missed in the config?
```vim
function s:toggletermInit()
lua << EOF
require("toggleterm").setup{
  size = function(term)
    if term.direction == "horizontal" then
      return vim.o.lines * 0.2
    elseif term.direction == "vertical" then
      return vim.o.columns * 0.4
    end
  end,
  open_mapping = [[<C-t>]],
  hide_numbers = false,
  shade_filetypes = {},
  shade_terminals = false,
  start_in_insert = false,
  insert_mappings = true,
  persist_size = false,
  direction = 'float',
  close_on_exit = true,
  shell = vim.o.shell,
}
function _G.set_terminal_keymaps()
  local opts = {noremap = true}
  vim.api.nvim_buf_set_keymap(0, 't', '<C-w><C-h>', [[<C-\><C-n><C-W>h]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-w><C-j>', [[<C-\><C-n><C-W>j]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-w><C-k>', [[<C-\><C-n><C-W>k]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-w><C-l>', [[<C-\><C-n><C-W>l]], opts)
end
vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
EOF
endfunction
```
<img width="718" alt="image" src="https://user-images.githubusercontent.com/13752789/180671091-43fdca2d-961e-4c09-82f0-c0155c0897cc.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/13752789/180671076-ce5490e3-1180-40b3-9c0e-f28efa6ed727.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/13752789/180671144-8d39b877-23e6-447e-8fd1-6c445af53d42.png">

**Comment by akinsho** [comment]
@ResolverJay by default neovim does not show numbers in floating windows. That option is intended for directions like horizontal where it is relevant. If you want to show numbers in floats you'll need to figure out how to add that in your config on your own. I don't intend to do that in this plugin since this is non standard behaviour

**Comment by ResolverJay** [comment]
Thanks @akinsho. I fixed by
```vim
autocmd TermEnter term://*toggleterm#* setlocal number relativenumber
```
One note though, it only works after insert mode is activated (or set `start_in_insert = true`).
