### ISSUE TITLE
Issue when winbar is active using latest Neovim

### ISSUE THREAD

**Issue by ChristianChiarulli** [akinsho/toggleterm.nvim#284]
![image](https://user-images.githubusercontent.com/29136904/182393908-85c19347-6c3f-47e2-acea-ea3820678b42.png)

**Comment by akinsho** [comment]
This bug is caused by an upstream issue which is tracked here: https://github.com/neovim/neovim/issues/19458
The winbar feature here is still experimental and subject to these kinds of bugs, so I recommend not using it here till the feature in core itself is stable

**Comment by ChristianChiarulli** [comment]
Gotcha, for anyone who wants to avoid this issue but still use 0.8 winbar and toggleterm you can checkout this commit: `2966cfe2`

**Comment by Livingnight** [comment]
> Gotcha, for anyone who wants to avoid this issue but still use 0.8 winbar and toggleterm you can checkout this commit: `2966cfe2`

Is this a commit for toggleterm, winbar, or neovim?

**Comment by akinsho** [comment]
Neovim commit @Livingnight, switching toggleterm commit won't matter if you're on a buggy nightly nvim version

**Comment by Livingnight** [comment]
@akinsho i gotcha. I should've looked more closely at the previous comments. Seeing as it's an upstream issue then it must be a neovim commit :smile: Thank you!

**Comment by nullchilly** [comment]
@akinsho Thank you so much, it was so frustrating for me but I didn't have the time to investigate.

The cost of using nightly features I guess...

**Comment by akinsho** [comment]
This has now been resolved in the latest nightly versions, so going to close this out
