### ISSUE TITLE
toggleterm broken if `dir` not exist

### ISSUE THREAD

**Issue by eeeXun** [akinsho/toggleterm.nvim#292]
I usually use mapping to open toggleterm in directory of current file like this.
```vim
noremap [somekey] :ToggleTerm dir=%:p:h<CR>
```
But if I accidentally open term in not exist file, such as `Git` in [vim-fugitive](https://github.com/tpope/vim-fugitive).
The toggleterm would not show the shell, then I can't type to shell anymore.
What I can do is reopening neovim. Then open toggleterm in a exist file.

**Comment by akinsho** [comment]
@eeeXun I don't entirely follow exactly what is going on here, but from what you are saying, it sounds like you are trying to open toggleterm in an incorrect directory. This seems like a user error to me, I'd suggest not opening it in a non-existent directory. If you'd like to contribute some validation to make this easier on the user, then please be my guest.

If you or no one else is going to submit this though, then I will close this out after a grace period

**Comment by akinsho** [comment]
fixed by #293
