### ISSUE TITLE
can't use Fish shell in toggleterm

### ISSUE THREAD

**Issue by azinsharaf** [akinsho/toggleterm.nvim#295]
hi,

I can't configure `toggleterm` in `neovim`. Not sure if it is a teoggleterm misconfiguration/issue or neovim/shell issue in my env.
this is the related lines in `plugins.lua` file: 
```
 -- Terminal
use {"akinsho/toggleterm.nvim", tag = 'v2.*', config = function()
  require("toggleterm").setup()
end}
```

this is the keymap in `keymaps.lua` file:  (Sapce is leader key.)

`keymap("n", "<leader>t", ":ToggleTerm<cr>", opts)`

so when i press leader-e i get he following error: (same result if I run `:ToggleTerm` on neovim command line.)

![84](https://user-images.githubusercontent.com/10101468/185438063-33d6b5fc-e574-4ded-ace2-e7712c8e969f.png)

the fish shell works fine outside of neovim. I am using Fish shell in cygwin environment.

**Comment by akinsho** [comment]
@azinsharaf issues relating to fish shell are not specific to this plugin, but related to getting fish shell working in general. Please check this issue https://github.com/akinsho/toggleterm.nvim/issues/255 I personally do not use fish shell so have no other advice than recommending switching your `vim.o.shell = bash` for a quick fix
