### ISSUE TITLE
Active Buffer scrolls to bottom and lose focus on `TermExec` if terminal is already open

### ISSUE THREAD

**Issue by Miradorn** [akinsho/toggleterm.nvim#296]
Hey there and thanks for this great plugin ❤️ 

I have a kind of weird behaviour that I couldn't really debug by looking through the code:

Basically, when im in Buffer `A` on any line and do `:TermExec` the first time (when no terminal is currently showing) everything works as expected (focus stays in Buffer `A` on the current line).
Now if i do the exact command again while the terminal is still open, the current Buffer will scroll to the last line and the focus is now at the terminal (which does run the command as expected).

My toggleterm setup (changing the options don't change this behavior):

```
            tt.setup {
                start_in_insert = false,
                auto_scroll = false,
            }
```

Thanks for any help, really appreciate it!

**Comment by akinsho** [comment]
Thanks for reporting this @Miradorn this is probably due to an issue in the auto scroll logic that was added a little while ago. I'll take a look

**Comment by akinsho** [comment]
@Miradorn can you try again, I've just pushed some fixes to the main branch

**Comment by Miradorn** [comment]
wow, thanks for that super quick reply! Seems to work great 🤟
