### ISSUE TITLE
Setting background color for horizontal/vertical term

### ISSUE THREAD

**Issue by krshrimali** [akinsho/toggleterm.nvim#297]
Hi! I know this is a silly question, but I'll still ask.

How can I set the highlight like it can be set for floating mode using `float_opts`? I want to set the background for my horizontal and vertical term to the original alacritty colorscheme...

Horizontal Term:
![image](https://user-images.githubusercontent.com/19997320/186932955-a6accd73-0faf-4afd-bb48-8d226013936f.png)

Float Term: (I want to set the colors for my horizontal/vertical term like below)
![image](https://user-images.githubusercontent.com/19997320/186933002-017efa30-c0c0-4d33-ab46-1307e7f888dc.png)

My `toggleterm.lua`: https://github.com/krshrimali/nvim/blob/master/lua/user/toggleterm.lua

**Comment by akinsho** [comment]
@krshrimali you should disable `shade_terminals` it's in the help docs

**Comment by krshrimali** [comment]
> @krshrimali you should disable `shade_terminals` it's in the help docs

Thank you so much! I appreciate the help.
