### ISSUE TITLE
toggling terminal dragging prompt to bottom.

### ISSUE THREAD

**Issue by ishwar00** [akinsho/toggleterm.nvim#300]
Hey there, thanks for the plugin :) 

I was setting up `toggleterm.nvim`, and i copied first 39 lines of this [config](https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/toggleterm.lua). When i toggle terminal using `<c-\>`, terminal pops up as expected, press it(`<c-\>`) again to close it, and after doing(toggling) it couple of times, a new prompt appears at the bottom, with old prompt at the top or sometimes old prompt disappears(afting toggling too many times).

Thanks

**Comment by akinsho** [comment]
@ishwar00 this isn't super clear what you are describing, can you attach a GIF or some screenshots, I don't really know what you mean. You can maybe try and set `auto_scroll` to false, but otherwise I'd need some images as I can't tell

**Comment by ishwar00** [comment]
Right!, i should have attached some visuals. While recording below video, i was only toggling(pressing `<S-t>`) terminal. First time works as expected, you get a prompt at the top, but second time it does not go well.

- I tried `auto_scroll=false`, it did not fix 
- Ran `:PackerAsync` before creating this issue.

(I changed `open_mapping` from `<c-\>` to `<S-t>`)

[Screencast from 29-08-22 10:24:52 PM IST.webm](https://user-images.githubusercontent.com/60176567/187253679-563ce89b-3853-40f1-8582-567660bc82cc.webm)

**Comment by akinsho** [comment]
@ishwar00 this doesn't reproduce for me, I hit the mapping several times in a row and the terminal does not do this. Can you please try running a minimal configuration without any other things except loading this plugin and seeing if the behaviour reproduces.

**Comment by ishwar00** [comment]
Hey @akinsho,

I figured, it's [nushell](https://www.nushell.sh/)'s bug. I tried with `bash` it works fine :D.

Sorry to bother you.
