### ISSUE TITLE
How to set it up?

### ISSUE THREAD

**Issue by sfmth** [akinsho/toggleterm.nvim#302]
I added this to my ~/.config/nvim/init.vim
```
Plug 'akinsho/toggleterm.nvim', {'tag' : 'v2.*'}

.
.
.

autocmd TermEnter term://*toggleterm#*
      \ tnoremap <silent><c-t> <Cmd>exe v:count1 . "ToggleTerm"<CR>

" By applying the mappings this way you can pass a count to your
" mapping to open a specific window.
" For example: 2<C-t> will open terminal 2
nnoremap <silent><c-t> <Cmd>exe v:count1 . "ToggleTerm"<CR>
inoremap <silent><c-t> <Esc><Cmd>exe v:count1 . "ToggleTerm"<CR>

```
and It doesn't even enable a ToggleTerm command

I know I'm a noobie in nvim but the instructions on readme.md are very unclear

**Comment by akinsho** [comment]
@sfmth you seem to have copy and pasted blocks from the readme that tbh I explicitly mention should only be used by people who are trying to do something complex. I *strongly* recommend reading the readme very closesly in detail.

A short example of how to use this would be
```lua
Plug 'akinsho/toggleterm.nvim', {'tag' : 'v2.*'}

lua << EOF
require('toggleterm').setup()
EOF
```

As a new user, I strongly recommend reading some preliminary documentation, so you understand how lua in neovim works, e.g. https://github.com/nanotee/nvim-lua-guide
