### ISSUE TITLE
[Documentation] Explicit instructions for setting up `powershell` shell in `nvim`

### ISSUE THREAD

**Issue by yehorb** [akinsho/toggleterm.nvim#303]
Hi. I recently encountered an issue using `powershell` shell with `toggleterm.nvim`. As usual, I was getting an empty screen when I opened the default terminal, and no terminal programs were working (a terminal window flashed for a second). This is a known issue, already mentioned in https://github.com/akinsho/toggleterm.nvim/issues/90, with a solution mentioned in https://github.com/neovim/neovim/issues/15634.

This is not the `toggleterm.nvim` issue, but a misconfiguration issue on the user side. But, I believe a lot of people in `nvim` community have already encountered or will encounter this issue mostly with the `toggleterm.nvim`, as it is one of the most popular terminal managers for `nvim`. `powershell` is the default shell for all new Windows editions, and it does not work with `nvim` (and, correspondingly, `toggleterm`) out of the box, which can be a major pain point for Windows users.

I propose adding a dedicated section in documentation specifically for Windows/`powershell` users. The section should mention taking a look at `:help shell-powershell` and include the snippet with relevant options translated into Lua, so that the solution is easy to incorporate into a config. Here is my port of the shell options to Lua, which solved the issue for me:

```lua
local powershell_options = {
  shell = vim.fn.executable "pwsh" and "pwsh" or "powershell",
  shellcmdflag = "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;",
  shellredir = "-RedirectStandardOutput %s -NoNewWindow -Wait",
  shellpipe = "2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode",
  shellquote = "",
  shellxquote = "",
}

for option, value in pairs(options) do
  vim.opt[option] = value
end
```

If you find it appropriate, `toggleterm.nvim` itself can include such options as an exported variable, or have the API call that will set the options for the user. But this is debatable.

I am willing to submit a PR for this, but I am just not sure where to put the changes.

Thank you for the great work!

**Comment by akinsho** [comment]
@yehorb so I very much do not want to be in the business of maintaining documentation for an OS I do not use with commands I do not understand. I generally do not want to be in a situation where I'm having to give specific instructions to fish users or powershell users etc. I would have no way of knowing if these commands were correct or validating these instructions if a user decided to contribute fixes over time.

I also definitely do not want to maintain this as actual code inside the plugin, let alone as docs. I think a good halfway house would be to open a wiki and put the instructions there. Windows users can then change it as they like with no input or verification from me.

**Comment by akinsho** [comment]
Actually this already exists 😆 https://github.com/akinsho/toggleterm.nvim/wiki/Tips-and-Tricks#using-toggleterm-with-powershell I completely forgot. I will link to it in the README

**Comment by akinsho** [comment]
I've now added a link in an FAQ section to the README and added your lua version of the solution. I believe this is a reasonable compromise, so will close this out.

**Comment by yehorb** [comment]
Great, thanks! Having the FAQ related to PowerShell on the main page is much better than not having one. Wiki can be overlooked sometimes (I definitely missed it).

**Comment by rohit-kumar-j** [comment]
From the wiki, and with os detection:

```lua
-- Example: put -> require('core.plugin.togglerm') in the main .lua file

-- toggleterm.lua :

-- Check if Windows
local is_win32 = vim.fn.has("win32")
if (is_win32 == 1) then
    local powershell_options = {
      shell = vim.fn.executable "pwsh" == 1 and "pwsh" or "powershell",
      shellcmdflag = "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;",
      shellredir = "-RedirectStandardOutput %s -NoNewWindow -Wait",
      shellpipe = "2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode",
      shellquote = "",
      shellxquote = "",
    }

    for option, value in pairs(powershell_options) do
      vim.opt[option] = value
    end
end


require("toggleterm").setup({
    on_create = function (require'toggleterm'.exec("echo hello!") end), -- optional
    -- Other options
    open_mapping = [[<c-\>]],
    direction = 'float',
    size = 40,
    float_opts = {
        border = "double",
    },
})

```
