### ISSUE TITLE
Dynamic directory change (follow nvim-tree)?

### ISSUE THREAD

**Issue by xbladesub** [akinsho/toggleterm.nvim#304]
Is it possible to dynamically change current directory - follow current nvim-tree path? Would be very-very useful. If you jump between buffers and projects (project.nvim) I'd like to also change opened terminal window directory.

**Comment by jdeut** [comment]
I think it is worth noting that 6dcdad0b9815f28b6e6299767edd4fbefa7e5d9a doesn't realize a very dynamic approach of following the current working directory. If the terminal is already open then the directory is only changed upon reopening the terminal.

Perhaps `toggleterm` would benefit from a more dynamic approach. I suggest implementing a suitable autocommand like the following one:

```
vim.api.nvim_create_autocmd(
   {'DirChanged'}, {
      pattern = {'window', 'global'},
      callback = function()
         if term:is_open() then
            term:send(string.format('cd %s', vim.fn.getcwd()), true)
         end
      end
   }
)
```

Best regards

**Comment by akinsho** [comment]
@jdeut thanks for the suggestion. I actually opted against such a solution because it felt way too invasive. There isn't really a good way to monitor the state of a terminal, it's just being open is not really a guarantee that now is a good time to try to mess with it. Imagine a user is halfway through a command or doing whatever in their terminal, and they switch directories. Suddenly, toggleterm is firing commands into their terminal. This is a can of worms. I think the snippet is fine to add to the wiki or something.

Having re-opened terminal change their directories feels safer i.e. it wasn't even open so presumably maybe not in use. This doesn't entirely safeguard against there having been partial input at the prompt, but it's a better best-effort IMO.

**Comment by jdeut** [comment]
> @jdeut thanks for the suggestion. I actually opted against such a solution because it felt way too invasive. There isn't really a good way to monitor the state of a terminal, it's just being open is not really a guarantee that now is a good time to try to mess with it. Imagine a user is halfway through a command or doing whatever in their terminal, and they switch directories. Suddenly, toggleterm is firing commands into their terminal. This is a can of worms.

I can understand your reasoning. It really depends on the specific use case and user preferences. However unless the shell implements a proper ipc/jobcontrol to query information about running processes from outside we always have to guess the current state of the shell in any case.

> I think the snippet is fine to add to the wiki or something.
> 
> Having a re-opened terminal change their directory feels safer, i.e. it wasn't even open so presumably maybe not in use. This doesn't entirely safeguard against there having been partial input at the prompt, but it's a better best-effort IMO.

In my case the approach you've mentioned would heavily interfere with my workflow. I use `toggleterm` solely with `pianocomposer321/yabs.nvim` as a code runner plugin. Therefore my usecase is not representative for the majority of `toggleterm` users i guess.

But I hope that the future will bring a more sophisticated solution.

Best regards

**Comment by Dawn-K** [comment]
@jdeut

**Comment by xiantang** [comment]
for nerdtree can use this config

```lua
require("toggleterm").setup {
  start_in_insert = false,
  size = 20,
  on_open = function(_)
    -- check nerdtree is visible
    --   -- g:NERDTree.IsOpen()
    -- get buffwinr
    local name = vim.fn.bufname("NERD")
    local winnr = vim.fn.bufwinnr(name)
    if winnr ~= -1 then
      local pwd = vim.fn.getcwd()
      -- NerdTree
      -- async running
      vim.defer_fn(function()
        local cmd = string.format("NERDTreeToggle %s ", pwd)
        vim.cmd(cmd)
        local cmd_retoggle = string.format("NERDTreeToggle %s | 1 | wincmd p", pwd)
        vim.cmd(cmd_retoggle)
      end, 100)


    end
  end,
}
```
