### ISSUE TITLE
[BUG] `close_on_exit` no longer working?

### ISSUE THREAD

**Issue by nwaywood** [akinsho/toggleterm.nvim#305]
I have `lazygit` setup with toggleterm https://github.com/nwaywood/dotfiles/blob/master/config/nvim/lua/user/plugins/toggleterm.lua.

When I press `q` to quit `lazygit`, toggleterm used to close the terminal window (because I have `close_on_exit = true`).

But after running `:PackerSync` it has stopped working, now when I quit `lazygit` I get this:

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/3773641/188828707-b6004404-ddb7-44f4-8122-141d1ea10dc9.png">

**Comment by akinsho** [comment]
@nwaywood can you narrow this down to a specific commit?

**Comment by nwaywood** [comment]
I'll try a bunch of different commits and see if I can help narrow it down.

Btw are you able to reproduce the issue?

**Comment by akinsho** [comment]
@nwaywood no I cannot reproduce this on the latest commit. I tried using `ToggleTerm direction=float` then I ran `exit` which successfully closed the window. Can you try the same flow?

**Comment by nwaywood** [comment]
> I tried using ToggleTerm direction=float then I ran exit which successfully closed the window. Can you try the same flow?

Yes that works for me as well.

What doesn't work is lazygit. Does that work for you?

![Sep-07-2022 21-01-27](https://user-images.githubusercontent.com/3773641/188862791-a05ad406-823e-44fa-a7e5-075ea6c538be.gif)

**Comment by akinsho** [comment]
My lazygit exits fine without the behaviour you've shown above, not a lazygit expert though, so I wouldn't know why. Can you see how it behaves in a terminal outside neovim

**Comment by nwaywood** [comment]
lazygit exits as expected outside of neovim. I don't think its a lazygit issue because the message in the toggleterm window that sticks around after quitting lazygit says `[Process exited 0]`. So I assume that means that toggleterm knows that the process has exited?

**Comment by nwaywood** [comment]
@akinsho I just setup a minimal `init.lua` and it works... so it must be something else in my config causing this issue somehow. Sorry to bother you!

init.lua
```
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "akinsho/toggleterm.nvim",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  local toggleterm = require("toggleterm")

  toggleterm.setup({
    size = 20,
    open_mapping = [[<c-\>]],
    direction = "float",
    close_on_exit = true,
    float_opts = {
      border = "curved",
      winblend = 0,
      highlights = {
        border = "Normal",
        background = "Normal",
      },
    },
  })

  local Terminal = require("toggleterm.terminal").Terminal
  local lazygit = Terminal:new({ 
    cmd = "lazygit", 
    hidden = true,
  })

  function _LAZYGIT_TOGGLE()
    lazygit:toggle()
  end
end
```

**Comment by MikaelElkiaer** [comment]
> @akinsho I just setup a minimal `init.lua` and it works... so it must be something else in my config causing this issue somehow. Sorry to bother you!

Did you figure out what caused it? I am experiencing the same for lazygit and lazydocker, but not for zsh.

**Comment by nwaywood** [comment]
@MikaelElkiaer no I never got to the bottom of the issue sorry.

It was getting too difficult maintaining my own config so I switched to LunarVim. The issue isn't present in LunarVim
