### ISSUE TITLE
[Bug] Terminal:send is not working 

### ISSUE THREAD

**Issue by Strongleong** [akinsho/toggleterm.nvim#308]
If I set in my setup config `on_open` handler like this:
```lua
  on_open = function (t)
    t.send('some_command')
  end,
```
I get error
```
Error executing Lua callback: Vim:E474: Invalid argument
stack traceback:
        [C]: in function 'chansend'
        ...packer/start/toggleterm.nvim/lua/toggleterm/terminal.lua:297: in function 'send'
        ...ngleong/.config/nvim/lua/plugins/settings/toggleterm.lua:17: in function 'on_open'
        ...packer/start/toggleterm.nvim/lua/toggleterm/terminal.lua:471: in function 'open'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:56: in function 'smart_toggle'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:266: in function 'toggle'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:239: in function 'toggle_command'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:376: in function <...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:376>
```

I looked at the code, specifically into  `lua/toggleterm/terminal.lua` and I found that cmd parameter is overridden with boolean value before it sent to the terminal (line 296) :

```lua

---Send a command to a running terminal
---@param cmd string|string[]
---@param go_back boolean? whether or not to return to original window
function Terminal:send(cmd, go_back)
  cmd = type(cmd) == "table" and with_cr(unpack(cmd)) or with_cr(cmd) -- <-- Here
  fn.chansend(self.job_id, cmd)
  self:scroll_bottom()
  if go_back and self:is_focused() then
    ui.goto_previous()
    ui.stopinsert()
  elseif not go_back and not self:is_focused() then
    self:focus()
  end
end
```

**Comment by akinsho** [comment]
@Strongleong your example uses this method incorrectly. It does in fact work correctly. In lua in order to call a method you must use the `:` syntax i.e. `term:send('ls -a')` not `term.send('ls -a')` the second example is wrong because the `:` syntax implicitly passes `self` as the first argument. If you change your example to the correct syntax this should work.

**Comment by akinsho** [comment]
The line you point to is not ovewriting command with a boolean operator. It is essentially a ternary operatory that checks the type of `cmd` and call the function one way or another

**Comment by Strongleong** [comment]
Thank you! Now everything works. But now I realize `on_open` is not what I actually want, so now I have a second question: is there something like `on_init` hook? 
I don't want to execute a command every time I open a terminal, only when I open it for the first time
