### ISSUE TITLE
Jump to last line after TermExec

### ISSUE THREAD

**Issue by xbladesub** [akinsho/toggleterm.nvim#314]
If I use for example ```TermExec cmd="cargo test"``` - command executes, but terminal doesn't scroll to the end. Is there any way how I can change this behavior?

**Comment by akinsho** [comment]
Setting `auto_scroll = true` should do this. If it isn't working then this is a duplicate of #307 so will close this in favour of that. Please feel free to contribute a fix if it turns out it isn't working. I don't have the time atm.
