### ISSUE TITLE
Use TermExec with vim.fn.input

### ISSUE THREAD

**Issue by xbladesub** [akinsho/toggleterm.nvim#315]
How can I use TermExec with vim.fn.input? I made shortcut for which-key plugin to run TermExec, but I also want to pass some arguments by my choice and confirm execution. 

something like ```"<cmd>TermExec cmd='cargo run' .. vim.fn.input('args: ')<CR>"``` doesn't work

<img width="602" alt="Screen Shot 2022-09-16 at 7 44 35 PM" src="https://user-images.githubusercontent.com/45129790/190632508-75e809b9-ef19-4a0c-a89a-698a041d5e3d.png">

**Comment by akinsho** [comment]
@xbladesub the issue tracker isn't the right place to open issues about how to setup your configuration but rather a place to raise bugs with the plug-in which this is not. You need to change your mapping into a function. The example you are trying isn't valid code

**Comment by xbladesub** [comment]
I figured it out. May would be helpful for someone:

```lua
lvim.builtin.which_key.mappings["s"].S = {
	"<cmd>lua require('auto-session').SaveSession(require('auto-session').get_root_dir() .. vim.fn.input('SessionName: '))<CR>",
	"Save session"
}
```
