### ISSUE TITLE
Compatibility with Git Bash/msys64?

### ISSUE THREAD

**Issue by musjj** [akinsho/toggleterm.nvim#324]
This is my terminal-related settings:
```
vim.opt.shell = "C:/msys64/usr/bin/bash.exe"
vim.opt.shellcmdflag = "--login -i -c"
```

Running `:ToggleTerm` spawns the following process:
`C:/msys64/usr/bin/bash.exe --login -i -c "\"C:/msys64/usr/bin/bash.exe;#toggleterm#1\""`

Which results into the following error:
`bash: C:/msys64/usr/bin/bash.exe;#toggleterm#1: No such file or directory`

It seems that the command would work *if* you don't put literal quotes inside the command string like this:
`C:/msys64/usr/bin/bash.exe --login -i -c "C:/msys64/usr/bin/bash.exe;#toggleterm#1"`

Is there any way to prevent it from putting in quotes into the string?

**Comment by musjj** [comment]
It seems that setting `vim.opt.shellxquote` to an empty string fixes this issue, but I'm not sure what side effects that might cause.

**Comment by akinsho** [comment]
@musjj I'm not a Windows user, so I can't comment on any of the requirements, but I'm aware that there are some hoops that need to be jumped through to make things work in the terminal with certain windows shells and neovim. I must clarify the toggleterm does not directly influence the underlying behaviour of the terminal. It is a UI wrapper that opens windows in a specific way, but how a terminal works in neovim etc. is not the remit of this plugin.

If setting that option works for you then that's good, but whether to use it is definitely out of scope for this plugin as that is a more general question about neovim and how its terminal works
