### ISSUE TITLE
Depreciation of vim.highlight.create in Neovim 0.8.0

### ISSUE THREAD

**Issue by daviddevs23** [akinsho/toggleterm.nvim#328]
Hello, 

I opened Neovim after upgrading to 0.8.0 and I receive this message. This isn't a real problem right now but could cause issues later on when Neovim 0.9 is released.

`vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead. See :h deprecated
This function will be removed in Nvim version 0.9
stack traceback:
        /usr/share/nvim/runtime/lua/vim/highlight.lua:14: in function 'create'
        ...k/packer/start/toggleterm.nvim/lua/toggleterm/colors.lua:99: in function 'set_highlights'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:359: in function 'setup'
        /home/david/.config/nvim/init.lua:302: in main chunk
Press ENTER or type command to continue
`

**Comment by akinsho** [comment]
@daviddevs23 are you on the latest commit of toggleterm I think I removed those functions quite a while ago.

**Comment by daviddevs23** [comment]
@akinsho It would appear you are right. Packer was not updating it so I had to do it manually. My apologies for not catching that.
