### ISSUE TITLE
`vim.highlight.create` is deprecated

### ISSUE THREAD

**Issue by superfive666** [akinsho/toggleterm.nvim#331]
vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead. See :h deprecated
This function will be removed in Nvim version 0.9
stack traceback:
        ...ar/neovim/0.8.0/share/nvim/runtime/lua/vim/highlight.lua:14: in function 'create'
        ...k/packer/start/toggleterm.nvim/lua/toggleterm/colors.lua:99: in function 'set_highlights'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:359: in function 'setup'

**Comment by akinsho** [comment]
Please update your version of toggleterm I'm getting this issue almost weekly now but people aren't checking their toggleterm version before reporting this. This change was made a long time ago so your version must be quite old.

**Comment by superfive666** [comment]
@akinsho Oh, ok, thanks for the update, let me double check on my end :)

**Comment by superfive666** [comment]
got it working now with update to:
`tag = "*"`

**Comment by 0styx0** [comment]
^Thanks for that. I installed this plugin when nvim 0.7 was in beta and had `tag = "v1.*"` to prevent breaking changes
