### ISSUE TITLE
Better way of naming terminals

### ISSUE THREAD

**Issue by axieax** [akinsho/toggleterm.nvim#332]
Is it possible to do something like this to name terminals:

```lua
local lazygit = require("toggleterm.terminal").Terminal:new({
  cmd = "lazygit",
  direction = "float",
  hidden = true,
  count = 5,
  name = "lazygit",
  -- -- OR
  -- on_open = function(t)
  --  t.name = "lazygit"
  -- end,
})
lazygit:toggle()
```

I'm aware of `:ToggleTermSetName` but it seems like a lot of extra code + could not get it working without the vim.ui.input prompt, passing in count.

Also, another question: is it possible to configure `close_on_exit` to be true if exit status is 0, and false otherwise? Would be great for catching errors.

**Comment by akinsho** [comment]
Forgot to respond to this. You can use the `display_name` field. Regarding the second question you can configure neovim to do this natively with 
```vimdoc
- The |TermClose| event gives the terminal job exit code in the |v:event|
  "status" field. For example, this autocmd closes terminal buffers if the job
  exited without error: >vim
    autocmd TermClose * if !v:event.status | exe 'bdelete! '..expand('<abuf>') | endif
```

**Comment by canvanaut** [comment]
<img width="351" alt="image" src="https://github.com/akinsho/toggleterm.nvim/assets/95581035/87899043-7682-4064-afbb-239f9b5377a2">

Hmm, it seems like the `display_name` field isn't setting the name of the terminal buffer.

**Comment by akinsho** [comment]
@canvanaut you cannot change the actual buffer name and scheme that neovim uses. That format and style is specifically chosen by the nvim team and required for some of the terminals functionality

**Comment by devansh08** [comment]
@akinsho Can `display_name` be set as part of `ToggleTerm` or `TermExec` itself ?
For my setup I have different custom terminals setup up to keybinds using just `TermExec`, and so I don't need to call the `Terminal:new` function. Would be great if I could pass the name as part of the exec itself.

Thanks!
