### ISSUE TITLE
Feature Request: Repeat Last Command

### ISSUE THREAD

**Issue by tlelson** [akinsho/toggleterm.nvim#334]
I often want to repeat a command a couple of times as I navigate around a file editing it.  For example `go test -run TestSomeTest`.

Something like this:

```lua
  cmd(
    "ToggleTermRepeat",
    function(args) M.repeat_last_command(args) end,
    { range = false, nargs = "0" }
  )
```

I would just add this command to my own configuration but I need to save a set of lines within the module for later access.

If others would find this useful I'd be happy to submit [this commit ](https://github.com/akinsho/toggleterm.nvim/compare/main...tlelson:toggleterm.nvim:main) as a PR. If not happy to to close the issue.

**Comment by tlelson** [comment]
Perhaps a more general solution to implement an optional `on_stdin` function in the configuration would allow for this and other customization in a more standardized way?

**Comment by akinsho** [comment]
@tlelson under the hood toggleterm uses the `termopen` function, which has the same args as `:help jobstart`. If you read through the arguments that that takes, you will find that there is no `on_stdin` option for the terminal in neovim. I don't mind the idea, but there isn't really a robust mechanism for keeping track of what the "last command" was. You could hook into things where a user specifically sends toggleterm a command, but what about if I was in the terminal itself and I entered `git status` then ran the `RunLast` command. How would toggleterm know that git status was my last command?

**Comment by tlelson** [comment]
@akinsho Thanks for the background.  That all makes sense.  I realized that the simplest solution for this is a mapping to `TermExec cmd='!!'`.

I will still look into the idea of an input preprocessor somewhere because I think it makes sense as a feature and I specifically need to be able to skip empty lines.

The reason for this is that I like to send multi-line input to repl's.  The following python code will execute at the empty line and the 2nd method will raise and indentation error:

```python
class c:
    def f1(self):
        print("f1")

    def f2(self):
        print("f2")
```

I understand that supporting everyone's unique edge case is not something you want to do, but if you have guidance about how to address this in a general way that is consistent with the projects fundamental concepts and objectives, I would be happy to work in that way.

At the moment i have the following hack patch in my local fork:

```diff
@@ -224,8 +224,11 @@ function M.exec_lines(id, trim_spaces, current_window, start_line, start_col)
 
   for _, line in ipairs(lines) do
     local l = trim_spaces and line:gsub("^%s+", ""):gsub("%s+$", "") or line
+    if l == '' then goto continue end -- skip empty lines
     M.exec(l, id)
+    ::continue::
   end
+  M.exec('\n', id) -- skip empty lines and finish with this for ipython shell
 
   -- Jump back with the cursor where we were at the beginning of the selection
   api.nvim_set_current_win(current_window)
```

**Comment by piersolenski** [comment]
Is there a way to stop the current process running first when running `TermExec cmd='!!'`?

**Comment by akinsho** [comment]
I'm going to close this issue out as there's no clear and easy way to implement this. If anyone has a suggestion please raise a PR. As for tips on how to achieve this feel free to post comments but I won't be involved as I don't have any of these answers (I don't automate running the last command, I just do that in the shell)
