### ISSUE TITLE
Can't unbound the  shortcut <c-h>

### ISSUE THREAD

**Issue by xyegithub** [akinsho/toggleterm.nvim#336]
In my linux, the shortcut `<c-h>` is used in the fish shell command line.  Thus, I do not want to use `<c-h>` in `toggleterm`. However, even I only set `open_mapping = [[<c-\>]]`. `<c-h>` is used by `toggleterm` and is not used by my fish shell command line.

**Comment by akinsho** [comment]
@xyegithub toggleterm does not bind control-h. That key might mean something different in the terminals than you expect, but in either case this issue does not come from this plugin as this plugin doesn't do anything with that key
