### ISSUE TITLE
[Bug] ;2u appears when I accidentally type shift + space

### ISSUE THREAD

**Issue by diegoulloao** [akinsho/toggleterm.nvim#338]
This appears when I'm typing fast and I press shift + space instead of only space:

![Screenshot 3](https://user-images.githubusercontent.com/45423661/199684084-504599aa-73f1-4d05-8e44-ae0c45722327.png)

It's really annoying have to go back and erase it

```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

`toggleterm latest version`

Config:
```lua
toggleterm.setup({
  open_mapping = [[<c-t>]],
  direction = "float", -- vertical | horizontal | tab | float
  persist_mode = true,
})

```

**Comment by akinsho** [comment]
@diegoulloao toggle term doesn't *at all* control what is rendered in the terminal. That is all handled by neovim. Nothing that appears or doesn't appear when you type is actually the responsibility of this plugin. I think if this is an issue it is best directed to nvim core unless you can show that this does not happen in any other floating or normal terminal except in toggleterm

**Comment by diegoulloao** [comment]
OK I'll check it in my weekend.
Thanks for the quick response, I'll keep you updated on this.

**Comment by n3oney** [comment]
@diegoulloao hello, have you found a solution? This is quite annoying when typing and accidentally instead of removing 1 character I add 6 (shift+backspace)

**Comment by diegoulloao** [comment]
no solution man, I didn't have time for research on this :(

**Comment by n3oney** [comment]
> no solution man, I haven't had time for research on this :(

I have managed to make a workaround solution, see https://github.com/NotAShelf/neovim-flake/issues/69#issuecomment-1533410759
(note this needs to be translated into the vim syntax, the syntax there is specific for that project)
