### ISSUE TITLE
Toggleterm do not load

### ISSUE THREAD

**Issue by troflog** [akinsho/toggleterm.nvim#344]
I have installed toggleterm with:

use {"akinsho/toggleterm.nvim", tag = '*', config = function()
          require("toggleterm").setup()
end}

but it does not work. I have to run the command: lua equire("toggleterm").setup() everytime I start neovim. I tought that this allready is done in the config thing.

**Comment by akinsho** [comment]
@troflog apologies for the late reply, unfortunately I really don't have the bandwidth to deal with anything other than bugs breaking functionality or super valuable feature requests. This plugin definitely does work/can be loaded, so this is very likely a configuration issue on your end.
