### ISSUE TITLE
toggle 2 terminals individually with different keymap

### ISSUE THREAD

**Issue by diegoulloao** [akinsho/toggleterm.nvim#348]
I have 2 terminals, the default one, which I trigger with Ctrl+t, and a second one which I open programmatically in order to open spotify tui, a spotify terminal client.

I have the following code:
```lua
local toggleterm_status, toggleterm = pcall(require, "toggleterm")
if not toggleterm_status then
  return
end

-- custom setup
toggleterm.setup({
  open_mapping = [[<c-t>]],
  direction = "float", -- vertical | horizontal | tab | float
  persist_mode = true,
})

local toggleterm_instance_status, toggleterm_instance = pcall(require, "toggleterm.terminal")
if not toggleterm_instance_status then
  return
end

-- spotify
local Terminal = toggleterm_instance.Terminal
local spotify_control = Terminal:new({
  cmd = "spotify_player",
  direction = "float"
})

function _spotify_toggle()
  spotify_control:toggle()
end

```

key mappings:
```lua
-- spotify keymap
vim.keymap.set("n", "<C-y>", "<cmd>lua _spotify_toggle()<CR>")
```

but when I open the spotify terminal the first time with Ctrl+y and I try to toggle/hide it, it not works.

I want to toggle the default one by pressing Ctrl+t and the spotify one by Ctrl+y

**Comment by akinsho** [comment]
I'm closing out all question issues as I personally don't have time to debug personal use case issues/problems. Please try to debug things if you can, or seek help on Reddit.
