### ISSUE TITLE
Error displayed with :ToggleTerm - E716: Key not present in Dictionary: "t"

### ISSUE THREAD

**Issue by minego** [akinsho/toggleterm.nvim#350]
If I start neovim, and then run `:ToggleTerm` it displays `E716: Key not present in Dictionary: "t"`

It only happens the first time opening a terminal after starting.

**Comment by akinsho** [comment]
Closing, as there is no clear reproduction here, and I do not experience this issue

**Comment by minego** [comment]
Wow. Well if it doesn't happen for you it must not be a bug. Don't bother asking any questions or making any suggestions for debugging.

That's fine. I'll uninstall.

**Comment by akinsho** [comment]
@minego as I pointed out, the main issue here is that you did not provide any actionable information about how I could reproduce this issue. You simply documented an issue with no clear way of how a person is supposed to reproduce it and perfectly fine with you. Uninstalling this is open source after all

**Comment by minego** [comment]
If I had more information I would have provided it. I installed it, and ran it following the directions as documented.

**Comment by akinsho** [comment]
@minego if you have ensured that you are on an up to date version of neovim and still seeing this issue but have no other reproduction steps then I don't know what to suggest. No one else has reported a similar issue, so my assumption is that this is not widespread and is specific to your setup and configuration. Have you tried a minimal configuration before opening this issue? Have you tried just running this plugin on its own with no other configuration or setup?
