### ISSUE TITLE
Cancel long running process

### ISSUE THREAD

**Issue by RomanoZumbe** [akinsho/toggleterm.nvim#352]
I have a long running process which directly responds to changes in my code. I want to start it in toggleterm to see the results without switching to another terminal window. Unfortunately the only way to stop that process is by pressing <C-c> (in Powershell). Is there any way to cancel that process from the toggleterm window? <C-c> is just passed to nvim, which inform me about saving and using :qa

**Comment by RomanoZumbe** [comment]
I noticed that the process ID is displayed on the bottom of the window. So I just used that to Stop the process. Does the plugin somehow expose the process ID so that I can map a keybinding to that operation?

**Comment by akinsho** [comment]
There is no straightforward way to do this, happy to have some contribution to add this but havent got the free time to go down this path personally. Each terminal has a job ID from neovim but that doesn't give you the ability to easily stop the containing process. AFAIK this isn't really easily done via neovim let alone this plugin

**Comment by RomanoZumbe** [comment]
What about exposing the process ID? I'll try to implement something in a fork
