### ISSUE TITLE
Toggling terminal always goes back to 'normal' mode

### ISSUE THREAD

**Issue by sycc90** [akinsho/toggleterm.nvim#357]
This is pretty much the same as #286 but not just for tabs.
This is on Windows 10 with nvim 0.8.1
I'm using version 2.3.0, with the following minimal config:
```lua
  require("toggleterm").setup({
    direction = 'float',
    open_mapping = '<M-`>',
    start_in_insert = true,
    persist_mode = true,
  })
```
The very first time I open the terminal in a new vim session, it opens in insert mode.  After that, whenever I toggle back to the terminal, it goes back to normal mode.  The linked issue was specific for 'tab' direction, but in my case it's happening with any direction (also 'float' and 'vertical' for example).
I also tried different combinations of `start_in_insert` and `persist_mode`, but it's aways back to normal mode.

Is there anything I'm not configuring properly?  Or maybe I misunderstood those options?

**Comment by akinsho** [comment]
@sycc90 have you updated the commands you use to move between terminal windows to use `wincmd` as described in the README?

**Comment by sycc90** [comment]
@akinsho  Thank you for replying!
I'm not using any commands to move between windows, just toggling the terminal on and off with <M-\`>
I did find something yesterday, I was following the wiki [entry](https://github.com/akinsho/toggleterm.nvim/wiki/Tips-and-Tricks#using-toggleterm-with-powershell) to use powershell with the terminal and it turns out that with that one it works correctly.
So if I set `shell=pwsh.exe` it works fine (goes back to the correct mode).  But if I set `shell=cmd.exe` then it will always go back to normal mode.

Taken from the wiki, this is what I added (you can see the commented line where I try one or the other):
```
if has('win32')
  "set shell=pwsh.exe
  set shell=cmd.exe
  let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
  let &shellredir = '-RedirectStandardOutput %s -NoNewWindow -Wait'
  let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
  set shellquote= shellxquote=
endif
```

Do you think there's any reason why it wouldn't work with cmd.exe?

**Comment by akinsho** [comment]
@sycc90 I don't use Windows at all so all of that section of the wiki is all Greek to me. Personally I have no idea why one of those would work better than another 🤷🏾‍♂️

**Comment by exactly-one-kas** [comment]
I believe #351 should fix this issue

**Comment by akinsho** [comment]
#351 is merged now 👍🏿
