### ISSUE TITLE
option to toggle in split window

### ISSUE THREAD

**Issue by ad-fabiane** [akinsho/toggleterm.nvim#360]
Hey Guys,

thank you for this amazing plugin.
But my workflow often includes opening splitwindows and then open files/terminals.
How would i do this with toggleterm?

I couldn't find anything like ":ToggleTerm init", but i would help me out a lot!
Or is there already an other way to do this?

best regards

**Comment by akinsho** [comment]
Sorry @ad-fabiane it's only me no there's no team maintaining this plugin and as I'm trying to manage my FOSS time better I generally don't dig into configuration related issues like this e.g. how can I make the plugin do X in my config etc. Please have a read through the docs and wiki and if you are unable to find a solution, I'm open to PRs to add functionality as long as they are well explained and considered.
