### ISSUE TITLE
When i try to execute command in toggle term it gives a error could find a terminal to close 

### ISSUE THREAD

**Issue by srikanth-iyengar** [akinsho/toggleterm.nvim#364]
I cannot close execute anything in toggle term
When i create a new toggleterm using command it closes the terminal on enter
Please help
![C__Program Files (x86)_PowerShell_7_pwsh exe 2022-12-13 14-26-44(1)](https://user-images.githubusercontent.com/88551109/207274612-5be7cf9c-bfda-43e7-8b24-1d8b9fd4f276.gif)

**Comment by akinsho** [comment]
@srikanth-iyengar can you please provide *exact steps to reproduce this issue with a minimal init.lua configuration*?

**Comment by akinsho** [comment]
Closing this out as there are no steps to reproduce this
