### ISSUE TITLE
[Lazygit example] Pressing esc doesn't close the "commit message input" or "stash message input" box.

### ISSUE THREAD

**Issue by aasutossh** [akinsho/toggleterm.nvim#367]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/18498932/207575146-afdac066-445b-4bbb-aa32-268efe541c02.png">
Rather than closing the input box, it goes into "normal mode" where I can do hjkl movements. Pressing `a` takes me to append mode then I can write.

**Comment by akinsho** [comment]
@aasutossh some remapping of your neovim keys will be required to use something like lazygit in all likelihood. Setting up specific config etc. isn't something that I generally get involved with as I have very limited time and get asked dozens of questions like this a week, which takes up a lot of time already. You need to consider what mapping are needed in your configuration and add those there.

**Comment by aasutossh** [comment]
I got it sir.
Thank you for replying. If I fail to set it up, I'll post my questions here.
