### ISSUE TITLE
cannot unmap insert mappings

### ISSUE THREAD

**Issue by LachlanGray** [akinsho/toggleterm.nvim#369]
I use kj to enter normal mode. I'm trying to create a new terminal to use with the lf file manager. My normal kj mapping clashes with the file manager so I want to disable that mapping when I open this terminal.

To do this here's everything I've tried so far:

```
local lf = Terminal:new{
	cmd = "lf",
        insert_mappings=false,
        terminal_mappings=false,
        ...,
	on_open = function(term)
		vim.cmd("iunmap kj")
        end,
	on_close = function(term)
		vim.cmd("inoremap kj <Esc>")
	end
}
```

But kj still goes into normal mode inside of this terminal. Is there a different way to do it?

I also noticed that even if I unmap kj before opening the new terminal, the kj mapping persists.

**Comment by akinsho** [comment]
@LachlanGray this mapping is from your config not from this plugin so figuring out how to remove it is something that has to happen on your end and is not an issue with this plugin. Please find the mode you have bound the mapping with probably `tmap` and make sure you have deleted in the correct mode
