### ISSUE TITLE
E73: tag stack empty | on .exs and .ex files

### ISSUE THREAD

**Issue by ChristopherKRad** [akinsho/toggleterm.nvim#373]
I've been observing this issue for a while but hesitated in posting to be sure.

The following is my toggleterm config, but for whatever reason it does not work on .exs nor .ex files (nor .heex files)

I've checked my `:map!` to see if there are any conflicting bindings and was unable to find any.

Not sure if anyone else has come across this, or has a recommended solution.

> require("toggleterm").setup{
>
>    direction = "float",
>    open_mapping = [[<c-t>]],
>    hide_numbers = true,
>    close_on_exit = true,
>    float_opts = {
>	border = "curved"
>    },
>}

**Comment by akinsho** [comment]
@ChristopherKRad I have no idea how that would even happen, this plugin doesn't do any filetype specific stuff. The most likely issue is that something in your configuration is interacting badly. Please try to see if this issue reproduces with a minimal init.lua. If it does not, then that confirms it's a configuration issue.

**Comment by ChristopherKRad** [comment]
I've rebound the keymap and it does look like it may be an issue with my config.

I'll keep investigating to try and figure out incase someone else comes across the `E73: tag stack empty` error in the future.

Wishing you an excellent holiday! @akinsho

**Comment by poperigby** [comment]
If anybody comes across this issue and is using lazy.nvim, make sure you set `lazy = false` in your plugin spec for toggleterm. I think this issue is happening because toggleterm isn't actually loaded by default.
