### ISSUE TITLE
Auto Change Directory not working

### ISSUE THREAD

**Issue by papatenko** [akinsho/toggleterm.nvim#379]
Is `autochdir=true` meant to change the directory the terminal is opened in depending on the buffer/file being edited or is it meant to do something else? 

I'm only asking cause I like VSCode's implementation of its terminal where it opens on the current directory the project is within and I want toggleterm to work the same way if possible. 

I thought adding `autochdir=true` would do the job but it doesn't seem to change anything for me. Is that the intended purpose and if so, what am I missing that's causing it not to work, or is that a feature that hasn't been implemented yet?

**Comment by ehaynes99** [comment]
Vim always has a current working directory. You can print what it currently is with:
```
:pwd
```
Or change it with:
```
:cd path/to/dir
```
(The equivalent lua commands are `vim.fn.getcwd()` and `vim.fn.chdir('path/to/dir')`)

The setting merely makes a NEW terminal open in whatever dir that is. Note that when you toggle an existing terminal, it keeps the existing one open in the background, so you would have to explicitly `exit` the terminal and open a new one.

**Comment by papatenko** [comment]
Thank you for your answer! It helped point me in the right direction of finding a solution to automatically changing the directory, to which I found this command on a Reddit thread:
```
cd %:h
``` 
That is all.
