### ISSUE TITLE
Question: Is there a way to create arbitrary number of terminals on demand?

### ISSUE THREAD

**Issue by ctrlplusb** [akinsho/toggleterm.nvim#380]
I'd like to create terminals without having to provide a terminal number,

i.e. 

- split a new vertical terminal to the right
- split a new horizontal terminal to the left
- ability to keep splitting

```
:ToggleTermNew direction=horizontal
:ToggleTermNew direction=vertical
```

Then I would navigate using my keybindings to cross splits, e.g <A-h>, <A-j>, <A-k>, and <A-l>

**Comment by akinsho** [comment]
short of using the command x times then no, alternatively since this is lua you can just write a function to do this yourself.

```lua
function create_layout()
  local T = require('toggleterm.terminal').Terminal
  T{my_prefs}:new():open()
  T{my_prefs_2}:new():open()
end
```

Then map that to a key mapping. I won't go through specifics of achieving your exact requirements but just illustrating that this can be done programmatically like the above

**Comment by rochacbruno** [comment]
I ended doing like this

```lua
function split_terminal_right()
  local Terminal = require('toggleterm.terminal').Terminal
  Terminal:new({direction='horizontal'}):open()
end

vim.api.nvim_create_user_command('SplitTerminal', split_terminal_right, {})
vim.keymap.set({"t"}, "<c-s>", "<cmd>SplitTerminal<cr>")
```

Now you can open a terminal and inside terminal hit Ctrl-s to split terminal, you can press it many times and it keeps opening horizontal terminals.

You can also run :SplitTerminal if needed from cmdline.

**Comment by ctrlplusb** [comment]
Awesome, thanks for sharing @rochacbruno!
