### ISSUE TITLE
Cannot move terminal window to the new tab with <C-w>T

### ISSUE THREAD

**Issue by carljohnesan** [akinsho/toggleterm.nvim#381]
Unlike with builtin `:term` which I can move to a new tab with `<C-w>T`, I cannot move toggleterm's terminal. Instead when I try to move toggleterm's terminal to a new tab, same file buffer I was before opening terminal opens in a new tab.

**Comment by akinsho** [comment]
This is a known limitation of this plugin and a hard problem to fix, very open to PRs from interested parties otherwise I think it's fine to at best document this and close this out

**Comment by carljohnesan** [comment]
Thanks, I got it. Sorry for asking off-topic question, but just to not create another possibly-duplicate issue: is this a known limitation too when I open few terminals e.g. horizontally and then another one vertically the layout becames very messed up in the best case, and I got lua errors sometimes in the worst case?

**Comment by akinsho** [comment]
Yes, that's also a complex problem, essentially this plugin isn't really designed to do window management style layout of terminals. It was designed initially to just open on or two terminals and remember them, but keep them out of the way. I think some people's use cases have ended up needing quite complex laying out of terminals, but isn't really something I need or have been inclined to build, especially as this isn't trivial either.

**Comment by carljohnesan** [comment]
Thanks for your time, now I understand.

**Comment by carljohnesan** [comment]
I think a found a workaround, however it is incomplete yet, I though maybe you might help me here.
So basically here's the workaround:
```lua
-- function for <expr> mapping to move terminal to a new tab
local insert_keys_to_move_term_to_new_tab = function()
  if vim.fn.match(vim.fn.expand('%'), [[^term:\/\/.*toggleterm#.*]]) == 0 then -- toggleterm's terminal
    local bufnr = vim.api.nvim_get_current_buf()
    return '<cmd>wincmd T<cr><cmd>buffer ' .. tostring(bufnr) .. '<cr>'
  else -- regular :terminal
    return '<cmd>wincmd T<cr>'
  end
end

-- ...

-- Alt-t to move terminal to a new tab from normal mode
vim.keymap.set('n', '<A-t>', insert_keys_to_move_term_to_new_tab, {silent = true,  expr = true})

local set_term_keymaps = function()
  -- ...
  -- Alt-t to move terminal to a new tab from terminal mode
  vim.keymap.set('t', '<A-t>', insert_keys_to_move_term_to_new_tab, {silent = true, buffer = true, expr = true})
  -- ...
end
local term_autocmd_group = vim.api.nvim_create_augroup('term_group', {clear = true}) -- terminal autocommands group
-- set terminal mappings when terminal is opened
vim.api.nvim_create_autocmd('TermOpen', {
  group = term_autocmd_group,
  pattern = '*',
  callback = set_term_keymaps,
})
```

First I was glad because that solution worked perfectly, until I tested it with horizontal terminal, with floating terminal it works, but with horizontal terminal it doesn't. I actually discovered that neither type of toggleterm's terminal is listed in buffer list (i.e. `:ls`) so I think this is the problem.
Have any thoughts [akinsho](https://github.com/akinsho)?

**Comment by akinsho** [comment]
@carljohnesan sorry I really don't know specifically what you should do exactly I haven't really looked into this feature in a very long time. I think if it seems like it's working for you then that's good enough. The reason buffers don't show in `:ls` is one of the core reasons this plugin exists which is to prevent terminal windows showing up in buffer listing which I feel adds noise so they are `nobuflisted` by default

**Comment by carljohnesan** [comment]
I see. Well then yeah it seems my workaround works seamlessly for me so I guess that's it. Thank you!

**Comment by strogonoff** [comment]
In case anyone finds it useful, this little function https://vim.fandom.com/wiki/Move_current_window_between_tabs works with normal buffers and with terminals.
