### ISSUE TITLE
How to exit insert mode when on terminal?

### ISSUE THREAD

**Issue by hrqmonteiro** [akinsho/toggleterm.nvim#383]
Isn't there a way to exit insert mode using only keyboards when on the terminal?

The only way i could find is clicking with the mouse outside of the terminal window. I want to be able to, like, press Esc on the terminal window and it exits the insert mode and i can navigate to other windows, how to do that?

**Comment by akinsho** [comment]
@hrqmonteiro this isn't really a toggle term question and more one about how to use neovim's terminal. Please have read through `:help terminal` this documentation is extensive and explain how neovim's terminal works and how to do things like map keys to behave as you'd please
