### ISSUE TITLE
Can't link `NormalFloat` to `Normal`

### ISSUE THREAD

**Issue by eeeXun** [akinsho/toggleterm.nvim#384]
```lua
require("toggleterm").setup({
    highlights = {
        Normal = {
            link = "Normal",
        },
        NormalFloat = {
            link = "Normal",
        },
    },

})
```
I've already linked `NormalFloat` to `Normal`. But it always link to `Pmenu`.
Output of `:highlight NormalFloat`
![image](https://user-images.githubusercontent.com/58657914/213520211-739d5d3c-bb5d-436d-8083-7b50bf71b29f.png)

**Comment by eeeXun** [comment]
Oh, It seems `NormalFloat` and toggleterm.NormalFloat are two different thing.
But I still have the problem that when I set background of `Normal` to `NONE`, which means transparent

```lua
vim.api.nvim_set_hl(0, "Normal", { guibg = NONE, ctermbg = NONE })
```

The float term is not transparent.

**Comment by gonviegas** [comment]
You probably have something overriding toggleterm config, as all that you mention is working fine for me.

**Comment by gonviegas** [comment]
@eeeXun actually, you're right. I can link but can't set colors in toggleterm config.

**Comment by eeeXun** [comment]
I found I can't set it to transparent with lua
```lua
vim.api.nvim_set_hl(0, "Normal", { guibg = NONE, ctermbg = NONE })
```

Only vimscript works
```vim
highlight Normal guibg=NONE ctermbg=NONE
```

**Comment by eeeXun** [comment]
neovim 0.9 fix this
