### ISSUE TITLE
Disallow other buffers in toggleterm window

### ISSUE THREAD

**Issue by bennypowers** [akinsho/toggleterm.nvim#389]
How could I go about preventing other buffers from taking over the terminal window?

A common occurrence in my workflow:
1. Open a toggleterm window in a horizontal split
2. do some terminal stuff
3. switch cursor to previous window
4. somehow get back to the toggleterm, but in normal mode (maybe by mousing into visual mode)
5. before entering insert (ie terminal) mode, open a file in a new buffer

Result:
- new buffer opens in toggleterm's window (bottom)

Expected:
- new buffer opens in previous window (top)

<details><summary>screenshot tour of the problem</summary>

1. horizontal split toggleterm
![1 new term](https://user-images.githubusercontent.com/1466420/216958011-c4fbd37f-50f0-48c3-8095-23474abf9f61.png)
2. somehow get into normal mode in the toggle term window
![2 enter normal mode](https://user-images.githubusercontent.com/1466420/216958173-1e755d2f-a317-45ac-b0f2-d6f848b63661.png)
3. telescope a file to open in a new buffer
![3 pick buffer](https://user-images.githubusercontent.com/1466420/216958764-4fa07136-3d2e-4b6b-8166-ff0b69a5077e.png)
4. end up with a file buffer open in the toggleterm window
![4 two file windows](https://user-images.githubusercontent.com/1466420/216958774-861efe82-d3e0-4981-b9e0-f6a97c2ebc14.png)

</details>

The goal here is to only allow toggleterm to occupy the window it creates.

**Comment by akinsho** [comment]
@bennypowers if I'm understanding correctly, what you want is something like https://github.com/stevearc/stickybuf.nvim. This is definitely a desirable trait/feature, but as the README for the linked plugin shows/the code itself, achieving this behaviour requires a fair few hacks. I'm personally against incorporating a bunch of logic like this into my plugins when ultimately the solution should ideally come from upstream neovim.

My suggestion here would be to either adopt that plugin and maybe post how you've configured it to work here for future searchers, or to comment in the issue upstream 🤷🏿‍♂️. I'd much rather not take on the responsibility of maintaining yet another workaround for this behaviour here.

**Comment by bennypowers** [comment]
So this works about as well as you'd expect

```lua
term_pinned = Terminal:new {
  direction = 'horizontal',
  size = 20,
  dir = 'git_dir',
  on_create = function()
    pcall(function() vim.cmd':PinBuftype' end)
  end
}
```

There's some jank with the buffer background highlight colours, but given the subject matter it seems not worth digging in to.

**Comment by CyrenArkade** [comment]
For anyone else who finds this, as of neovim 0.10 you can do this.
```lua
on_open = function(term)
  vim.opt_local.winfixbuf = true
end,

```
