### ISSUE TITLE
How to close all terminals using a keymap while in insert mode in a terminal

### ISSUE THREAD

**Issue by haikyuu** [akinsho/toggleterm.nvim#390]
Thanks for this great project 👍 I enjoy it very much.

I have a keymap to toggle all terminals. And I want to use it whilst in insert mode in a terminal. How do I do that?

**Comment by akinsho** [comment]
@haikyuu you can figure this out by looking at how `tnoremap` and other terminal mappings work. This isn't an issue though and generally I keep the issue tracker exclusively for bugs or feature requests as I don't have enough time to handle questions on usage like this

**Comment by haikyuu** [comment]
Thank you @akinsho I'll ask in neovim matrix server next time.
