### ISSUE TITLE
Specific keymap doesn't work 

### ISSUE THREAD

**Issue by TroySigX** [akinsho/toggleterm.nvim#402]
I have the following mapping:
```
local toggleTerm = function()
    local api = vim.api
    local bufnr = api.nvim_get_current_buf()
    local filename = api.nvim_buf_get_name(bufnr)
    local modifiable = api.nvim_buf_get_option(bufnr, 'modifiable')

    if filename ~= '' and modifiable then
        api.nvim_command('write')
    end

    api.nvim_command('ToggleTerm')
end

map({ 'n', 'i', 'v' }, '<F9>', function()
    vim.cmd.stopinsert()
    toggleTerm()
end, { desc = 'Toggle Term', silent = true })
```

ToggleTerm works fine in normal and visual mode, but in insert mode, when entering terminal, it doesn't let me type.

**Comment by akinsho** [comment]
When you are typing in the terminal you are in `terminal` mode not in `insert` mode, you should be mapping to `t` please see `:help tnoremap` for more info

**Comment by TroySigX** [comment]
No, I already have t mapping. What I meant was, when being in insert mode and I want to open toggleterm, the above issue persists.
