### ISSUE TITLE
Feature Question: Execute not entire file but selected line with visual mode.

### ISSUE THREAD

**Issue by PorcoRosso85** [akinsho/toggleterm.nvim#406]
https://github.com/akinsho/toggleterm.nvim#termexec
This is beautiful feature.

toggleterm provide to run selected line?
not only cmd='lua %'
but also cmd='lua <selected line visual mode>

**Comment by akinsho** [comment]
@PorcoRosso85 this feature is indeed offered and is documented please read the help i.e. `ToggleTermSendVisualLines` please have a read through the docs for usage. I will not be able to help you work things out in your config so please don't post on the issue tracker for that sort of help 🙏🏿
