### ISSUE TITLE
`persist_mode`'s default is incorrectly documented

### ISSUE THREAD

**Issue by mawkler** [akinsho/toggleterm.nvim#409]
`:help toggleterm.txt` states that `persist_mode` is set to `true` by default, however in reality it is [set to `false`](https://github.com/akinsho/toggleterm.nvim/blob/main/lua/toggleterm/config.lua#L48).

I can create a PR fixing this. Which one should it be? Personally I think `persist_mode = true` seems like the best default.

**Comment by akinsho** [comment]
Thanks for raising this @mawkler. Personally don't really mind, I have it set to true in my config but guess lots of people won't be able to benefit from it if it's false without reading the docs so I think setting it to true by default is better 👍🏿
