### ISSUE TITLE
Can't change default shell to bash on Windows

### ISSUE THREAD

**Issue by nickmarks00** [akinsho/toggleterm.nvim#413]
By default, Neovim on Windows will use `cmd` as the shell when using `:term`, however this can be overridden by setting `vim.opt.shell = "bash.exe"` as an example. The issue is that upon toggling the terminal open, I receive a floating window that immediately closes containg only the error message:

> /usr/bin/bash /s: No such file or directory

Running `:echo &shell` returns `bash`. I've also tried explicitly setting the path to the `bash` executable, e.g. `vim.opt.shell = '"C:/Program Files/Git/usr/bin/bash.exe"'`, where `:echo &shell` now returns this full path but toggling the terminal open and closed still produces the same error.

**Comment by akinsho** [comment]
@nickmarks00 the entire flow of how this works is dependent on what is set in neovim this plugin isn't really intervening or responsible it largely just takes the value it is given from vim.o.shell. This issue sounds like difficulty with the neovim setting and not really an issue with this plugin specifically.

You can set the shell used by toggleterm in the config and there are some entries in the wiki regarding how to set things up for windows. Besides this I don't really have any advice or information about how to make this work but seems to be a commonly encountered issue on windows so maybe search previous issues/search the web.

**Comment by akinsho** [comment]
I'm going to close this out since I think this is a platform specific configuration issue rather than a bug specifically with this plugin.
