### ISSUE TITLE
ToggleTermClose or a way to close the terminal when dap-ui starts

### ISSUE THREAD

**Issue by ebiscaia** [akinsho/toggleterm.nvim#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I would to ask if it is possible to implement a ToggleTermClose(All) function so that when I run Dap-Ui the terminal closes when it is starts since DapUi has its own terminal. I am also open to other solutions such as storing the terminal state in variable so that when I start and finish DapUi the terminals are just toggled, but in this case I would need some help to implement that by myself.

Thanks in advance,

Eddie

**Comment by akinsho** [comment]
@ebiscaia you can already use `ToggleTermCloseAll` with a bang at the end `ToggleTermCloseAll!`  or `require('toggleterm').toggle_all(true)` should close all terminals. Regarding implementing a custom solution if necessary unfortunately that will be up to you or some kind onlooker who might want to post a suggestion for you

**Comment by ebiscaia** [comment]
Hi @akinsho,

```
:ToggleTermCloseAll
E492: Not an editor command: ToggleTermCloseAll
```

Toggling the terminal on and off instead of closing it would have the side effect that the terminal would open if I start DapUi with the terminal closed.

Thanks for the attention

**Comment by akinsho** [comment]
@ebiscaia I meant `ToggleTermToggleAll!` just made a typo. I've previously had this issue raised about specific commands to explicitly close a terminal. The command I linked should work but if it doesn't I have previously also mentioned in such issues that I'd welcome a PR to add it as an option to an existing command `close=true` or something
