### ISSUE TITLE
[Bug] Shortcut doesn't work in different profiles of iTerm.

### ISSUE THREAD

**Issue by nottyl** [akinsho/toggleterm.nvim#419]
I'm using Neovim with iTerm2. I currently have two profiles (one dropdown and one normal window profile).

I have set the ToggleTerm key shortcut to <C-\`>. However, this shortcut only works in the dropdown profile but not in the normal window profile. I can still open Terminal using `:ToggleTerm` command but I can't use the shortcut to open it. Every time I try to do that, it'll just show an error `E78: Unknown Mark`.

What could be causing this problem? I don't really know what is causing all of this. 
This is the plugin's config:
```
require "toggleterm".setup({
	open_mapping = [[<C-`>]],
	size = 20,
	start_in_insert = true,
	insert_mappings = true,
})
```

**Comment by akinsho** [comment]
@nottyl this is *well outside* of the remit of this plugin I literally have no idea, I don't use iTerm so I don't know what it's doing at all. Maybe it's sending a different character sequence than expected or something. In either case this isn't an issue for this repo but maybe an iTerm support forum
