### ISSUE TITLE
[BUG] The terminal is toggled when I press ENTER

### ISSUE THREAD

**Issue by inaki6martinez** [akinsho/toggleterm.nvim#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the next configuration the terminal is also toggles  when I press the ENTER key, what makes impossible to execute any command on the terminal.
```
require("toggleterm").setup{
  open_mapping = [[<c-m>]],
}

```

### Expected Behavior

The terminal should be only toggled when I press the combination on the open_mapping.

### Steps To Reproduce

1. Set the configuration 
```
require("toggleterm").setup{
  open_mapping = [[<c-m>]],
}

```
2. Press ENTER in normal mode or when I'm on the terminal and try to execute a command on the terminal pressing ENTER

### Environment

```Markdown
- OS: Debian 11
- neovim version:0.8.2
- Shell:zsh
```

### Anything else?

I have tried disabling all my plugins but toggleterm and it still happening.

**Comment by akinsho** [comment]
@inaki6martinez this isn't a bug, in the land of terminal emulators `<C-M>` is read as being the same thing as `<CR>` this is an issue with neovim/the terminal etc. I would choose another key and call it a day if I were you but definitely not a bug/issue.
