### ISSUE TITLE
[BUG] Changing git branches in toggle term doesn't refresh buffers

### ISSUE THREAD

**Issue by rossvz** [akinsho/toggleterm.nvim#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing git branches using toggle term doesn't notify/refresh the open file buffer.

### Expected Behavior

I don't know enough about it - but I expect that whatever file-change event is supposed to fire when swapping branches doesn't seem to be happening?

### Steps To Reproduce

- Open buffer in nvim
- Toggleterm
- `git checkout foo` (some other branch that has changes in the currently opened file)
- close terminal and buffer is not refreshed (unless manually running `:e` or something)

Compare to
- open buffer in nvim
- open separate terminal outside of nvim (new terminal window, etc)
- `git checkout foo`
- buffer is automatically refreshed/reloaded with new branch change

### Environment

```Markdown
- OS: macOS
- neovim version:  v0.8.3
- Shell: zsh
```

**Comment by akinsho** [comment]
@rossvz I think this might be a misunderstanding about neovim's terminal, none of the functionality you are describing is controlled by or related to this plugin or the terminal really. This relates to neovim and its ability to respond to external changes. If you search around you will find workarounds as well as with in progress PRs for this

**Comment by rossvz** [comment]
Sorry, I may be misunderstanding - but neovim responds to changing the branch if I use a _different_ terminal but switching branches specifically with `toggleterm` creates an issue?

**Comment by akinsho** [comment]
@rossvz I've never had a report like this before. I do this workflow you describe all the time without issue. Can you confirm that you have also tested this with a minimal init.lua to ensure it's not related to some plugin or configuration issue
