### ISSUE TITLE
[BUG] Toggleterm is not opening in insert mode anymore

### ISSUE THREAD

**Issue by andremralves** [akinsho/toggleterm.nvim#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the command `:ToggleTerm`, the terminal opens in insert mode only for the first time, when the terminal instance is created.

This is my setup:
```lua
require("toggleterm").setup{
  start_in_insert = true,
  float_opts = {
      border = 'curved',
  },
}
```

If I close the terminal and open it again, the terminal doesn't open in insert mode anymore.

I noticed that this regression was introduced in version 2.5.0. Before it, the behavior was working as expected.

### Expected Behavior

The terminal should always open in insert mode when I run `:ToggleTerm`.

### Steps To Reproduce

After installing ToggleTerm:

1. Run `:ToggleTerm` 3 times.
2. In the third time, the terminal will not open in insert mode.

### Environment

```Markdown
- OS: Ubuntu 22.10
- neovim version: 0.10.0
- Shell: zsh
```

**Comment by akinsho** [comment]
@andremralves `persist_mode`'s default value was changed from `false` to `true` so whatever mode you were in when the terminal last closed will be remembered. This coupled with whether you are using mapping that take you out of terminal mode buffer changing the buffer will cause this behaviour. You should either turn off `persist_mode` if you like or tweak you mapping so you aren't being put in normal mode before closing the terminal

I've just tested things locally and can definitely have the terminal open in insert mode multiple times in a row.

**Comment by andremralves** [comment]
@akinsho Thank you! It worked! I haven't seen this setting before. My fault.
