### ISSUE TITLE
Feature: Option to disable lateral mouse scroll

### ISSUE THREAD

**Issue by Zeioth** [akinsho/toggleterm.nvim#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using a trackball for scrolling, it is very easy to accidentally do side scrolling, which is an unwanted behavior

### Expected Behavior

Only vertical scroll is allowed (or an option for this)

### Steps To Reproduce

* Use a trackbal to scroll the terminal.
* You will be able to scroll vertically and horizontally, which we do not want.

### Environment

```Markdown
- OS: arch-
- neovim version: 0.9.0
- Shell: zsh
```

**Comment by Zeioth** [comment]
This could be achieved with a simple 

```
augroup NoScrollPlease
  autocmd!
  autocmd CursorMoved * norm!99zH
augroup END
```

**Comment by Zeioth** [comment]
There is some way to disable lateral scroling for :term and TermToggle? 

Thank you.

**Comment by akinsho** [comment]
@Zeioth there isn't a way to disable lateral scrolling just for terminal buffers. There is an option called `mousescroll` that you can look into. This can be used to disable horizontal scrolling but this is a global option with no local variant and I won't mess with a user's global settings whereas you can do this yourself in your own config

**Comment by Zeioth** [comment]
Do you know what value should I give to the global? I cannot find info about it. I have set nowrap on my settings which should already disable horizontal scroll, but it doesn't work for terminal.

**Comment by akinsho** [comment]
@Zeioth please read through `:help mousescroll` I just searched the docs for it and read it and it explains that you can set the horizontal value to zero. It is described in that doc section

**Comment by Zeioth** [comment]
It must be kinda new, I only found it [here](https://github.com/neovim/neovim/blob/c9f47fca8b896ecb304294cce675fedac9ab926c/runtime/doc/options.txt#L4260):

Setted as

    mousescroll = "ver:1,hor:0",

Thank you so much. That fixed it.
