### ISSUE TITLE
[BUG] stdout moves cursor to the latest output

### ISSUE THREAD

**Issue by krishna-bala** [akinsho/toggleterm.nvim#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the toggleterm terminal (`:ToggleTerm`) and executing a command which writes to stdout (e.g. `while sleep .1; do echo "hello"; done`) , the terminal will scroll to the latest output in normal mode when the window is focused. Here is an example of this behavior:

https://github.com/akinsho/toggleterm.nvim/assets/20020722/9810d734-4884-4dfd-b077-cb2726a02acc

### Expected Behavior

When using the default terminal (`:terminal`) and executing the same command which writes to stdout, the terminal will **_not_** scroll to the latest output in normal mode when the window is focused. Here is an example of this behavior:

https://github.com/akinsho/toggleterm.nvim/assets/20020722/d3afef19-190d-4383-85b8-0281a457bf78

### Steps To Reproduce

1. Open toggleterm: `:ToggleTerm`
2. Execute the following command: `while sleep .1; do echo "hello"; done`
3. Attempt to scroll up in the toggleterm window while in normal mode.
4. Repeat steps 1-3, but instead of using `:ToggleTerm` use `:terminal` and compare.

### Environment

```Markdown
- OS: Ubuntu 18.04
- neovim version: v0.9.0
- Shell: bash
```

### Anything else?

I'm using [LazyVim](https://www.lazyvim.org/plugins) and have toggleterm set up using
```lua
-- ~/.config/nvim/lua/plugins/toggleterm.lua

-- set_terminal_keymaps is used to create an autocmd in lua/config/autocmds.lua
function _G.set_terminal_keymaps()
  local opts = { buffer = 0 }
  vim.keymap.set('t', '<leader><esc>', [[<C-\><C-n>]], opts)
  vim.keymap.set('t', 'jk', [[<C-\><C-n>]], opts)
  vim.keymap.set('t', '<leader><C-h>', [[<Cmd>wincmd h<CR>]], opts)
  vim.keymap.set('t', '<leader><C-j>', [[<Cmd>wincmd j<CR>]], opts)
  vim.keymap.set('t', '<leader><C-k>', [[<Cmd>wincmd k<CR>]], opts)
  vim.keymap.set('t', '<leader><C-l>', [[<Cmd>wincmd l<CR>]], opts)
end

return {
  "akinsho/toggleterm.nvim",
  lazy = false,
  init = function()
  end,
  opts = {
    size = 30,
    open_mapping = [[<c-\>]],
    autochdir = true,
    autoscroll = false,
    hide_numbers = true,
    shade_filetypes = {},
    shade_terminals = true,
    shading_factor = "-30",
    start_in_insert = false,
    insert_mappings = true,
    persist_size = true,
    direction = "horizontal",
    float_opts = {
      border = "curved",
    },
    close_on_exit = true,
    shell = vim.o.shell,
  },
}
```

**Comment by akinsho** [comment]
@krishna-bala this isn't a bug but a feature actually added by a user who wanted this functionality. It can be disabled using `auto_scroll = false` seems you've made a typo in your config so it isn't actually disabled in your case
