### ISSUE TITLE
[BUG] <title>unable to use alias in toggleterm

### ISSUE THREAD

**Issue by hopezh** [akinsho/toggleterm.nvim#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use the following config in `$profile` for powershell to set `ls` as the alias for `colorls`:

```
Function colorls_cmd {colorls -l -a -G --sf --gs}
set-alias -name ls -value colorls_cmd
```

However, it's not recognized in `toggleterm` floating window:
```
'ls' is not recognized as an internal or external command,
operable program or batch file.
```

May I ask if anyone has similar issue? and, if yes, how to solve it? 

Thanks. 

### Expected Behavior

Run `colorls` when alias `ls` is typed in `toggleterm`. 

### Steps To Reproduce

`toggleterm.lua`:

```
return {
    {
        "akinsho/toggleterm.nvim",

        config = true,

        cmd = "ToggleTerm",

        keys = {
            {
                "<F3>",
                "<cmd>ToggleTerm<cr>",
                desc = "Toggle floating terminal",
            },
        },

        opts = {
            open_mapping = [[<F3>]],
            direction = "float", -- float/horizontal
            shade_filetypes = {},
            hide_numbers = true,
            insert_mappings = true,
            terminal_mappings = true,
            start_in_insert = true,
            close_on_exit = true,

            float_opts = {
                border = "curved",
                -- width = 100,
                -- height = 100,
            },
        },
    },
}
```

### Environment

```Markdown
- OS: Windows 11
- neovim version: v0.10.0-dev-400+ge41b2e34b
- Shell: PowerShell
```

### Anything else?

Nil.

**Comment by akinsho** [comment]
Hi @hopezh,

So the issue of hours specifically your terminal works isn't actually what this plugin controls. The terminal is controlled/implemented by neovim this plugin just opened windows so any issues setting aliases etc. Wouldn't be due to this plugin but the underlying terminal
