### ISSUE TITLE
stop proccess

### ISSUE THREAD

**Issue by asyncci** [akinsho/toggleterm.nvim#446]
excuse me , if it is dumb , but can I actually send  ```ctrl+c``` through ```cmd=```  to stop process inside the terminal?

**Comment by asyncci** [comment]
Ok , I've tried this , seems to be working :  ```vim.keymap.set('n','c;','<Cmd>TermExec cmd="<C-c>"<CR>')```

**Comment by kassio** [comment]
This didn't work to me, is there any documentation on that?

**Comment by nemo-omen** [comment]
Setting the keymap for use in terminal buffers worked for me: `vim.keymap.set('t','c;','<Cmd>TermExec cmd="<C-c>"<CR>')`
