### ISSUE TITLE
Keymap with function in terminal

### ISSUE THREAD

**Issue by leosmaia21** [akinsho/toggleterm.nvim#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
i am trying to create this keymaps:

local buildcommand = "make"

vim.api.nvim_create_user_command('Setbuild', function()
	buildcommand = vim.fn.input('Comando para executar no termimal quando carregar CTRL m: ', buildcommand)
end, {})
vim.keymap.set('n', ctrl m, function()
	buildcommand = vim.fn.input('Comando para executar no termimal quando carregar CTRL b: ', buildcommand)
end, {}
)vim.keymap.set('t', ctrl m, function()
	buildcommand = vim.fn.input('Comando para executar no termimal quando carregar CTRL b: ', buildcommand)
end, {}
)
vim.keymap.set('n', ctrl b, function() vim.cmd("TermExec go_back=0 cmd='" .. buildcommand .. "'<CR>")end , opts)
vim.keymap.set('t',ctrl b, function() vim.cmd("TermExec go_back=0 cmd='" .. buildcommand .. "'<CR>")end , opts)

i needed to write ctrl m and ctrl b here in the issue  because it didnt apear with the keybinding

the ones in normal mode work fine, but those in terminal mode mess up with terminal, like when i type something in terminal and press enter it run the function to get the new build command

### Expected Behavior

terminal mode work like in normal mode

### Steps To Reproduce

just run terminal and try type something and then enter

### Environment

```Markdown
- OS:
- neovim version:
- Shell:
```

**Comment by akinsho** [comment]
Sorry @leosmaia21 this seems like a usage question and not a true bug in this plugin. For the most part I don't anwser usage questions as they are as I'm sure you can guess relatively non stop as there are always people trying to figure out how to make stuff work and only one of me. Using `TermExec cmd="make"` does work so it will be something to do with how the command is being written. Given the formatting it's very hard for me to see anyway but in either case I suggest experimenting in your config
