### ISSUE TITLE
[BUG] ToggleTermSendVisualLines doesn't work on the first try

### ISSUE THREAD

**Issue by louis-vinchon** [akinsho/toggleterm.nvim#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When visual selecting lines to execute (line-wise with `<C-v>`), if I use the `ToggleTermSendVisualLines` command it apparently doesn't do anything.

Using it again and again doesn't do anything until you leave visual line selection, select them again and run the command again. Then it works.

### Expected Behavior

`ToggleTermSendVisualLines` should work on the first try.

### Steps To Reproduce

Lazy lua module:

```lua
local function make_opts(_, opts)
  local custom_opts = {
    open_mapping = [[<C-\>]],
  }

  return vim.tbl_deep_extend(
    "force",
    opts,
    custom_opts
  )
end

local function make_keymaps()
  return {
    {
      "<leader>te",
      "<cmd>ToggleTermSendCurrentLine 8 <CR>",
      desc = "Execute current line in a terminal.",
    },
    {
      "<leader>te",
      "<cmd>ToggleTermSendVisualLines 8 <CR>",
      mode = "v",
      desc = "Execute selected lines in a terminal.",
    },
  }
end

return {
  "akinsho/toggleterm.nvim",
  lazy = false,
  keys = make_keymaps(),
  opts = make_opts,
}
```

Sample line to execute:

```md
ls
```

### Environment

- OS:
  ```
  $ uname -a
  Linux arch 6.4.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 x86_64 GNU/Linux
  ```
- neovim version:
  ```
  :version
  NVIM v0.9.1
  Build type: Release
  LuaJIT 2.1.0-beta3
  ```
- Shell:
  ```sh
  $ zsh --version
  zsh 5.9 (x86_64-pc-linux-gnu)
  ```

**Comment by akinsho** [comment]
@louis-vinchon I have been meaning to add a note about this to the README but all REPL like functionality e.g. send X to terminal etc was contributed by users. It has never been in scope personally for me to add this functionality as I do not use it at all. But having had users keen enough to put in the leg work themselves I accepted the addition of these command but I do not personally maintain them.

If you would like to see these changes made I strongly recommend having a look at the code as this is not likely something I will tweak myself.
