### ISSUE TITLE
[BUG] Custom floating terminals fail to dynamically resize

### ISSUE THREAD

**Issue by Subjective** [akinsho/toggleterm.nvim#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Custom floating terminals spawned by the Terminal class do not dynamically resize, whereas normal floating terminals spawned by the `:ToggleTerm` command do.

### Expected Behavior

I would expect both kinds of floating terminals to dynamically resize when the window is resized or font sizes change.

### Steps To Reproduce

<details>
<summary>Minimal Config</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

vim.g.mapleader = " "

-- install plugins
local plugins = {
	{ "folke/tokyonight.nvim", opts = {} },
	{
		"akinsho/toggleterm.nvim",
		cmd = "ToggleTerm",
		opts = { direction = "float" },
		init = function()
			local Terminal = require("toggleterm.terminal").Terminal
			local lazygit = Terminal:new({ cmd = "lazygit", hidden = true })
			function _lazygit_toggle() lazygit:toggle() end
		end,
		keys = { { "<leader>t", function() _lazygit_toggle() end } },
	}, -- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

</details>

1. Create a file called `repro.lua`
2. Paste the provided config into the file.
3. nvim -u repro.lua
4. Hit `<leader>t` to open a floating term. 
5. Resize the window or change the terminal font size
6. Floating term does not dynamically resize

### Environment

```Markdown
- OS: MacOS Ventura 13.4
- neovim version: NVIM v0.10.0-dev-646+gc4df2f08b
- Shell: zsh 5.9 (x86_64-apple-darwin22.0)
```

**Comment by akinsho** [comment]
@Subjective please try #460

**Comment by Subjective** [comment]
@akinsho This doesn't doesn't seem to resolve the issue for me unfortunately.

![Screen Recording 2023-07-10 at 1 05 12 AM](https://github.com/akinsho/toggleterm.nvim/assets/56745535/0858fcea-9f41-4de7-949f-42356fa730d2)

**Comment by akinsho** [comment]
Ok seems like this will be a pain to fix so will have to wait till I have more time.

**Comment by akinsho** [comment]
Ok found the issue and pushed a fixed
