### ISSUE TITLE
[BUG] Opening a terminal moves the cursor one place

### ISSUE THREAD

**Issue by videbar** [akinsho/toggleterm.nvim#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When pressing the key combination set as `open_mapping`, the terminal window opens and the cursor moves to the next place (one sport to the right).
I've tested this using different key combinations for the remap, multiple terminal directions and on both normal and insert mode.

### Expected Behavior

The terminal window should open but the cursor should stay in the same place.

### Steps To Reproduce

1. Open a terminal using either `ToggleTerm` or the remap for `open_mapping`.
2. Close the terminal window or move back to the editor.
3. The cursor has moved one placed.

### Environment

```Markdown
- OS: Fedora 38
- neovim version: 0.9.1
- Shell: bash
```

### Anything else?

This is an example of the issue:

Before opening the terminal window the cursor is on the "a" character:
![Captura de pantalla de 2023-07-12 14-15-09](https://github.com/akinsho/toggleterm.nvim/assets/87827878/0279f18e-c914-4c30-b5a3-f33cee5290ed)

After opening a terminal window and jumping back to the editor, the cursor lands on the next character, "u":
![Captura de pantalla de 2023-07-12 14-15-32](https://github.com/akinsho/toggleterm.nvim/assets/87827878/e6adb66b-605d-4e7b-b199-6f5d488bc4c2)

My config file:

```lua
-- Kemaps to send text to the terminal.
vim.keymap.set("n", "<leader>g", [[<Cmd>ToggleTermSendCurrentLine<CR>]])
vim.keymap.set("v", "<leader>g", ":ToggleTermSendVisualSelection<CR>",
    { noremap = true, silent = true })

require("toggleterm").setup {
    open_mapping = "<C-g>",
    -- when neovim changes it current directory the terminal will change it's own when
    -- next it's opened.
    autochdir = true,
    start_in_insert = true,
    -- whether or not the open mapping applies in insert mode.
    insert_mappings = false,
    -- whether or not the open mapping applies in the opened terminals. Required to be
    -- able to close terminals.
    terminal_mappings = true,
    persist_size = true,
    -- if set to true (default) the previous terminal mode will be remembered.
    persist_mode = false,
    direction = "float",
    -- close the terminal window when the process exits.
    close_on_exit = true,
    -- automatically scroll to the bottom on terminal output.
    auto_scroll = true
}

```

**Comment by akinsho** [comment]
@videbar I'm unable to reproduce this. There is also no code that would explain this. The mappings are executed using
```lua
  if mapping then
    vim.keymap.set("n", mapping, '<Cmd>execute v:count . "ToggleTerm"<CR>', {
      desc = "Toggle Terminal",
      silent = true,
    })
    if config.insert_mappings then
      vim.keymap.set("i", mapping, "<Esc><Cmd>ToggleTerm<CR>", {
        desc = "Toggle Terminal",
        silent = true,
      })
    end
```
Nothing there IMO would account for this. Can you confirm that you have tested this with a completely minimal `init.lua` (no configuration frameworks) that does not load any other plugins other than toggleterm?

**Comment by videbar** [comment]
You are right sorry, an autocmd hidden in the config files was causing the issue.

I'll close the issue.
