### ISSUE TITLE
Using `git-bash` on windows

### ISSUE THREAD

**Issue by sslime336** [akinsho/toggleterm.nvim#463]
I opened this issue not for bug reporting, just post my success experience configing and using `toggleterm.nvim` on windows as I think this would be a great help if anyone who wants to setup an env like me.

A very simple config:

```lua
require'toggleterm'.setup({
    open_mapping = '<C-\\>',
    start_in_insert = true,
    direction = 'float',
})
```

Then find a place you like to emit below:

```lua
vim.cmd [[let &shell = '"D:/Git/bin/bash.exe"']]
vim.cmd [[let &shellcmdflag = '-s']]
```

Then just press `Ctrl + \`

![图片](https://github.com/akinsho/toggleterm.nvim/assets/97684920/97456f1b-0e8f-4d79-a75e-f01e2fd95f3e)

I wish this would help, it works on my PC anyway :P

**Comment by Zooce** [comment]
This was a lifesaver...thank you! Now I can actually use toggle term at work...

**Comment by akinsho** [comment]
@sslime336 thanks for posting this. There is actually a wiki which anyone should be able to edit on this repo so you can also add this there. Hopefully people also check this.

**Comment by sslime336** [comment]
Sure, that would be more appropriate :-)

**Comment by akinsho** [comment]
I'll close this out now but keep it pinned for other users

**Comment by F2BEAR** [comment]
Hey, I tried the same using lazy.vim without success; do somebody know where should I place the vim.cmd conf?

**Comment by eatPizza311** [comment]
@F2BEAR 
For lazy.vim you can set the following in your `init.lua` or other place you like:
```lua
vim.o.shell = "D:/Git/bin/bash.exe"
vim.o.shellcmdflag = "-s"
```

**Comment by OuyangIPC** [comment]
> @F2BEAR For lazy.vim you can set the following in your `init.lua` or other place you like:
> 
> ```lua
> vim.o.shell = "D:/Git/bin/bash.exe"
> vim.o.shellcmdflag = "-s"
> ```

What's means "-s"? I look up ":help shellcmdflag", vim show default "-c",  and "/s /c" in windows.

**Comment by F2BEAR** [comment]
> @F2BEAR 
> For lazy.vim you can set the following in your `init.lua` or other place you like:
> ```lua
> vim.o.shell = "D:/Git/bin/bash.exe"
> vim.o.shellcmdflag = "-s"
> ```

This is exactly what I needed, thanks!

**Comment by eatPizza311** [comment]
@OuyangIPC I'm not sure how toggle-term starts the terminal under the hood.
But the Windows default "/s /c" will be considered as directory "/s" and "/c" in GitBash, which is not what we want.
On the other hand, Setting `shellcmdflag = -s` will start GitBash in a non-interactive mode, and it works like a charm, haha.

**Comment by Leeto1970** [comment]
> @OuyangIPC I'm not sure how toggle-term starts the terminal under the hood. But the Windows default "/s /c" will be considered as directory "/s" and "/c" in GitBash, which is not what we want. On the other hand, Setting `shellcmdflag = -s` will start GitBash in a non-interactive mode, and it works like a charm, haha.

 @eatPizza311 Thanks for you information, it's very helpful to me.

**Comment by sewbacca** [comment]
When I use `shellcmdflag = -s`, `:!ls` and friends does no longer work. When I use `shellcmdflag = -c` then toggleterm does no longer work. Did anyone encounter the same problem?

**Comment by sewbacca** [comment]
Okay I found a workarround. It is ugly, but it works:
```lua
{
	'akinsho/toggleterm.nvim',
	version = "*",
	config = function ()
		local toggleterm = require 'toggleterm'

		toggleterm.setup {}

		vim.keymap.set({ 'n', 't' }, "<C-\\>", function ()
			vim.o.shellcmdflag = '-s'
			vim.cmd.ToggleTerm()
			vim.o.shellcmdflag = '-c'
		end)
	end
}
```

**Comment by Leeto1970** [comment]
> Okay I found a workarround. It is ugly, but it works:
> 
> ```lua
> {
> 	'akinsho/toggleterm.nvim',
> 	version = "*",
> 	config = function ()
> 		local toggleterm = require 'toggleterm'
> 
> 		toggleterm.setup {}
> 
> 		vim.keymap.set({ 'n', 't' }, "<C-\\>", function ()
> 			vim.o.shellcmdflag = '-s'
> 			vim.cmd.ToggleTerm()
> 			vim.o.shellcmdflag = '-c'
> 		end)
> 	end
> }
> ```

This is what I used configure:
for toggleterm:
`return {
    {
        'akinsho/toggleterm.nvim',
        version = "*",
        opts = function()
            return {
                require('toggleterm').setup{
                    open_mapping = '<C-\\>',
                    autochdir = false,
                    start_in_insert = true,
                    shell = vim.o.shell,
                    direction = 'float',
                    float_opt = {
                        border = 'shadow',
                        width = 80,
                        heigh = 120,
                        title_pos = 'center',
                    }
                }
            }
        end,
    }
}
`
for neovim options:
`if vim.fn.has('win64') == 1 or vim.fn.has('win32') == 1 then
  vim.opt.shellquote = "\""
  vim.opt.shellxquote = "\""
  vim.opt.shellcmdflag = "-c"
end
`
