### ISSUE TITLE
[BUG] TermExec doesn't work with config.shell = function

### ISSUE THREAD

**Issue by asror1** [akinsho/toggleterm.nvim#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I when trying to use `TermExec cmd="some command"` I am faced with the following error: 
![image](https://github.com/akinsho/toggleterm.nvim/assets/92228287/9c367c81-3fe4-44ca-a57c-b9e34359cbf2)
And what ends up happening is the command is **not executed**. 

### Expected Behavior

When using config.shell = function, the `TermExec` should not throw an error, and instead execute the passed in `cmd` as normal. 

### Steps To Reproduce

1. In any buffer
2. With the following minimal config: 
```lua
require("toggleterm").setup({
  shell = function()
    return vim.o.shell
  end,
})
```
3. Run the following command `:TermExec cmd="echo test"`
4. And you should see the following error... 
![image](https://github.com/akinsho/toggleterm.nvim/assets/92228287/c3b9f40b-7eff-47fd-a9f8-8ebdc08164f6)

### Environment

```Markdown
- OS: Windows 10
- neovim version: 
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3        
Compiled by runneradmin@fv-az28-353
- Shell: pwsh
```

### Anything else?

I believe this is an easy fix. If I'm not mistaken it comes from using a function for the **shell** option in the config. I will be submitting a fix PR for this for review.

**Comment by akinsho** [comment]
fixed by #467
