### ISSUE TITLE
[BUG] The terminal might be covered by other buffer

### ISSUE THREAD

**Issue by nullptr-yxw** [akinsho/toggleterm.nvim#468]
https://github.com/akinsho/toggleterm.nvim/assets/96286337/612095cf-1fcc-4821-9d8d-a37692aaac3c

As we see, When I clicked on the bufferline, the terminal was covered by other buffer.
The native terminal of neovim has such problem as well, but some other plugins which also split the window, like nvimtree, will not.

**Comment by akinsho** [comment]
@nullptr-yxw this is the native behaviour of neovim, the terminal buffer is a buffer just like any other. I think if a user wants something like this they ought to use something like `stickybuf.nvim` or if there was a native mechanism. I know nvim-tree has added code to hijack this behaviour and stop it from happening and I'm happy to accept a PR to add that but I personally don't think I'll add this myself as this is likely to be brittle and a workaround native behaviour
