### ISSUE TITLE
[BUG] Leaving terminal mode with delay

### ISSUE THREAD

**Issue by barakolshe** [akinsho/toggleterm.nvim#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im using this to set the \<esc\> character to leave the terminal mode:

```
function _G.set_terminal_keymaps()
    local opts = { buffer = 0 }
    vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], opts)
end

vim.cmd('autocmd! TermOpen term://*toggleterm#* lua set_terminal_keymaps()')
``` 
but there is always a delay from the time i press  \<esc\>  to the time i actually leave the terminal mode.

### Expected Behavior

I should leave the terminal mode immediately after pressing  \<esc\> 

### Steps To Reproduce

Just paste the mappings code from the docs into the config, and it should reproduce when using the toggleterm terminal.

### Environment

```Markdown
- OS:
Ubuntu
- neovim version:
0.9.1
- Shell:
bash
```

**Comment by akinsho** [comment]
@barakolshe this isn't the behaviour in a minimal `init.lua` as I can confirm that locally pressing escape is instantaneous can you paste the *minimal config file* you are using. This sounds like an issue that occurs frequently relating to having another mapping bound to escape so vim is waiting to see if you will complete the mapping or not

**Comment by barakolshe** [comment]
thanks for the quick response, to be honest when i've submitted the issue i
hadn't tested on minimal config, but now i have and the bug persists.
ill send my files, the paths are:
init.lua
after/terminal.lua

and by the way, the {noremap = true, nowait = true} options don't really
matter, it doesn't work even without them.

**Comment by barakolshe** [comment]
thanks for the quick response, to be honest when i've submitted the issue i hadn't tested on minimal config, but now i have and the bug persists.

init.lua
```
-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
    -- Packer can manage itself
     use 'wbthomason/packer.nvim'

    -- -- terminal
    use { "akinsho/toggleterm.nvim", tag = '*'}
end)
```

after/terminal.lua
```
require("toggleterm").setup {
    open_mapping = [[<c-t>]],
    hide_numbers = true,      -- hide the number column in toggleterm buffers
    direction = 'horizontal',
    auto_scroll = true,       -- automatically scroll to the bottom on terminal outpu
    insert_mappings = true,   -- whether or not the open mapping applies in insert mode
    terminal_mappings = true, -- whether or not the open mapping applies in the opened terminals
    --winbar = {
    --  enabled = false,
    --  name_formatter = function(term) --  term: Terminal
    --    return term.name
    --  end
    --},
}

function _G.set_terminal_keymaps()
    local opts = { buffer = 0 }
    vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], { buffer = 0 })
    vim.keymap.set('n', '<C-h>', [[<C-w>h<CR>]], opts)
    vim.keymap.set('n', '<C-j>', [[<C-w>j<CR>]], opts)
    vim.keymap.set('n', '<C-k>', [[<C-w>k<CR>]], opts)
    vim.keymap.set('n', '<C-l>', [[<C-w>l<CR>]], opts)
    vim.keymap.set('n', '<C-w>', [[<C-\><C-n><C-w>]], opts)
end

-- if you only want these mappings for toggle term use term://*toggleterm#* instead
vim.cmd('autocmd! TermOpen term://*toggleterm#* lua set_terminal_keymaps()')
```

**Comment by xzbdmw** [comment]
I have the same problem, it is soloved?

**Comment by xzbdmw** [comment]
using `verbose tmap <esc>`,
lazyvim set the keymap `<esc><esc>` already. 
https://github.com/LazyVim/LazyVim/blob/a50f92f7550fb6e9f21c0852e6cb190e6fcd50f5/lua/lazyvim/config/keymaps.lua#L149
It's useful to add the information in Readme

> @barakolshe this isn't the behaviour in a minimal `init.lua` as I can confirm that locally pressing escape is instantaneous can you paste the _minimal config file_ you are using. This sounds like an issue that occurs frequently relating to having another mapping bound to escape so vim is waiting to see if you will complete the mapping or not
