### ISSUE TITLE
[BUG] Opening an existing terminal from TermSelect does not start it in insert mode

### ISSUE THREAD

**Issue by devansh08** [akinsho/toggleterm.nvim#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If there are multiple terminals open in the background, re-opening one from `TermSelect` does not start it in Insert mode. I have `start_in_insert` set to true and also tried running `startinsert` inside `on_open`. Neither of those helped.

### Expected Behavior

Based on the setting `start_in_insert`, reopened terminals should start in Insert mode.

### Steps To Reproduce

- Open multiple terminals with `:ToggleTerm`, `:2ToggleTerm`, ...
- Select a terminal from the list in `:TermSelect`
- Terminal reopens in Normal mode instead of Insert

### Environment

```Markdown
- OS: Arch Linux
- neovim version: v0.9.1
- Shell: fish
```

### Anything else?

Pls let me know if I'm misunderstanding `start_in_insert` or if there is anything else that can help me set this up.

Thanks!

**Comment by antsoh161** [comment]
It's in the readme but if you're toggling with keymaps make sure you use wincmd, I had to change:
`vim.api.nvim_buf_set_keymap(0, 't', '<C-j>', [[<C-\><C-n><C-W>j]], opts)`
to
`vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]], opts)`

Seems like `api.nvim_get_mode()` returns normal mode even if toggled from insert mode otherwise

Otherwise if you don't want it to remember the mode you're toggling from and always start in insert, set in init.lua:
```lua
require("toggleterm").setup({
   persist_mode = false,
   start_in_insert = true,
})
```

**Comment by devansh08** [comment]
Completely forgot I opened this :)

@antsoh161 @akinsho I tried setting the `persist_mode` option, but that does not help with the `TermSelect` flow.

If by the toggling keymap you mean the `open_mapping` config, I have mine set to `<C-E>` and toggling does already open it in insert mode OOTB for me; without having to set the `persist_mode` or use `wincmd`.
The issue I'm facing is in the `TermSelect` flow. So, open multiple terminals and then switch to one using `TermSelect`. That starts in Normal mode, which I would instead like to be in Insert mode.

The `wincmd` point is kind of confusing me right now, so hoping I don't need it for `TermSelect` :)
Here is my current config:

<details>
<summary>ToggleTerm Config (Lazy)</summary>

```lua
return {
  "akinsho/toggleterm.nvim",
  version = "*",
  config = function()
    local opts = {
      size = function(term)
        if term.direction == "horizontal" then
          return 15
        elseif term.direction == "vertical" then
          return 80
        end
      end,
      open_mapping = "<C-E>",
      hide_numbers = true,
      direction = "float",
      float_opts = {
        border = "single",
        width = 200,
        height = 40,
      },
      close_on_exit = true,
      auto_scroll = true,
--      persist_mode = false,
      start_in_insert = true,
    }

    require("toggleterm").setup(opts)
  end
}
```

</details>

Any ideas ?
Thanks!
