### ISSUE TITLE
How to open a buffer from float term using neovim remote?

### ISSUE THREAD

**Issue by xbladesub** [akinsho/toggleterm.nvim#474]
Is it possible to open a new buffer (?send to existing) from float term using neovim remote? Currently if I use `nvr myfile` inside float term - it opens this file in place, but I would like to open it not in float

**Comment by akinsho** [comment]
@xbladesub it's probably better to ask these questions on reddit or somewhere else. I'm not even sure if this question really relates to toggleterm at all it seems to be about some external plugin and how it interacts with toggleterm which really isn't something that should be being reported as an issue. I think you'll have to do some experimenting in your config about this
