### ISSUE TITLE
toggleterm border highlight

### ISSUE THREAD

**Issue by ryanmsnyder** [akinsho/toggleterm.nvim#476]
Is there a way to highlight the toggleterm border (`WinSeparator`) without affecting other WinSeparators? For example, [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) has a highlight group called `NeoTreeWinSeparator` that only affects its border without highlighting horizontal borders.

**Comment by akinsho** [comment]
Not as far as I know, I have looked for a solution for this but am not aware of one. If you find a solution please raise a PR
