### ISSUE TITLE
Terminal doesn't toggle after update to the latest version

### ISSUE THREAD

**Issue by diegoulloao** [akinsho/toggleterm.nvim#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After update (latest version) the terminal doesn't toggle. It just open but it doesn't close.

### Expected Behavior

Toggle when pressing the same keybind for `open_mappping` in the setup.

### Steps To Reproduce

Just toggle.

### Environment

```Markdown
- OS: Ventura 13.5.1
- neovim version:

NVIM v0.10.0-dev-673+g622ae2f53-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```
- Shell: zsh
```lua
-- custom setup
toggleterm.setup({
  open_mapping = [[<c-t>]],
  direction = "float", -- vertical | horizontal | tab | float
  float_opts = {
    border = "curved", -- single | double | curved
    winblend = 0,
  },
  persist_mode = true,
  highlights = {
    FloatBorder = {
      guifg = "#059de3",
    },
  },
})
```

Screen recording:

https://github.com/akinsho/toggleterm.nvim/assets/45423661/4852205e-e4b8-4c5c-b0a1-facfd342e293

**Comment by 5i1ent** [comment]
`OS: pop-os 22.03`
`NVIM v0.9.1`
`Build type: Relese`
`LuaJIT 2.1.0-beta3`

`require("toggleterm").setup({`
`    direction = 'horizontal',`
`    size = 26,`
`    shade_terminals = false,`
`    start_in_insert = true,`
`    autochdir = true,`
`    hide_numbers = true,`
`    float_opts = {`
`        border = 'single',`
`    },`
`})`

same experience as above.

**Comment by diegoulloao** [comment]
It looks like some changes introduced yesterday.

**Comment by Roboticyang** [comment]
Same here.

**Comment by akinsho** [comment]
Reverted the changes in #488 should fix this

**Comment by willothy** [comment]
Sorry about that y'all, seems that solving one issue (#487) caused another.
