### ISSUE TITLE
[BUG] Terminal doesn't retain any history if you execute the command with terminal resized to one line

### ISSUE THREAD

**Issue by hamiltonhous** [akinsho/toggleterm.nvim#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you resize the terminal to be just one line, you can run a command and it wont be stored in the terminal history. After resizing it back to a larger size, the command seemingly never was ran in the terminal history.

Also, I can't reproduce this, but I also got into a weird state where clear did not work at all anymore. When the clear command was run, it would adjust the terminal so the newest prompt line was at the top hiding the rest of the older history, but I could scroll up and see the rest still so it wasn't getting rid of it. This was during my messing around with the aforementioned issue so may be related.

### Expected Behavior

Any command run would be in the terminal history regardless of the size of the terminal window.

### Steps To Reproduce

1. Run :ToggleTerm
2. Resize it so its only showing one line
3. Run a command such as touch test
4. Resize it so its showing multiple lines
5. test file exists but the history of creating it is lost in the terminal

### Environment

```Markdown
- OS: Mac M2
- neovim version: 0.9.1
- Shell: zsh
```

**Comment by akinsho** [comment]
Hi @hamiltonhous 
So
> If you resize the terminal to be just one line, you can run a command and it wont be stored in the terminal history. After resizing it back to a larger size, the command seemingly never was ran in the terminal history.

Falls squarely in the territory of upstream neovim issues than toggleterm issues. This plugin essentially opens windows and maintains state. It does nothing at all to do with how a terminal actually works. That all comes from neovim itself and is well outside of my control. I think it's best to report this there. You can confirm this by using `:sp terminal` and then playing with that to see if it reproduces there.

If you are able to find a reproduction for the second issue please feel free to raise and issue for that.
