### ISSUE TITLE
[BUG] opening a custom terminal terminates any previously opened terminals

### ISSUE THREAD

**Issue by se-omarayman** [akinsho/toggleterm.nvim#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when toggling a normal terminal with <ctrl-\\>, the process running stays running, but if i open a custom terminal like lazygit for example, the process in the normal terminal is killed and a new normal terminal is opened.
![toggleterm](https://github.com/akinsho/toggleterm.nvim/assets/56203198/ac34152f-330b-4bdc-be14-57c0b067659e)

also if i keep the normal terminal open and trigger the custom terminal, and then try to switch to the normal terminal with <ctrl-\\>, I get "Couldn't find a terminal to close after using custom terminal".
![toggleterm3](https://github.com/akinsho/toggleterm.nvim/assets/56203198/7395634a-834f-43d7-a8ad-050ac206bda1)

### Expected Behavior

when opening a custom terminal, the normal terminal should stay running.

### Steps To Reproduce

this is my configuration:
```
local M = {
  "akinsho/toggleterm.nvim",
  commit = "19aad0f41f47affbba1274f05e3c067e6d718e1e",
  event = "VeryLazy",
}

function M.config()
  local status_ok, toggleterm = pcall(require, "toggleterm")
  if not status_ok then
    return
  end

  toggleterm.setup {
    size = 65,
    open_mapping = [[<c-\>]],
    hide_numbers = true,
    shade_terminals = true,
    shading_factor = 2,
    start_in_insert = true,
    insert_mappings = true,
    persist_size = true,
    direction = "vertical",
    close_on_exit = true,
    shell = vim.o.shell,
    float_opts = {
      border = "curved",
    },
  }

  function _G.set_terminal_keymaps()
    local opts = { noremap = true }
    vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\><C-n>]], opts)
    vim.api.nvim_buf_set_keymap(0, "t", "<C-h>", [[<C-\><C-n><C-W>h]], opts)
    vim.api.nvim_buf_set_keymap(0, "t", "<C-j>", [[<C-\><C-n><C-W>j]], opts)
    vim.api.nvim_buf_set_keymap(0, "t", "<C-k>", [[<C-\><C-n><C-W>k]], opts)
    vim.api.nvim_buf_set_keymap(0, "t", "<C-l>", [[<C-\><C-n><C-W>l]], opts)
  end

  vim.cmd "autocmd! TermOpen term://* lua set_terminal_keymaps()"

  local Terminal = require("toggleterm.terminal").Terminal
  local lazygit = Terminal:new { direction = 'float', cmd = "lazygit", hidden = true }

  function _LAZYGIT_TOGGLE()
    lazygit:toggle()
  end
end

return M
```

and i trigger lazygit with <leader>gg

**Comment by akinsho** [comment]
@se-omarayman this should definitely not be the case and I cannot reproduce it. To be clear I think an issue like this if it were in fact widespread would disrupt the vast majority of users of this plugin so in all likelihood there remains something in your setup that is triggering this. Even with the minimal config this does not happen for me.

Can you definitely clarify that a *clean* run of neovim with just this plugin no after files or ftplugin etc and definitely no other plugins reproduces this issue.

FWIW I won't be able to dig in with you as I don't have time to do individual debugging for issues like this.
