### ISSUE TITLE
Underlines are different colours from normal terminal zsh vs ToggleTerm

### ISSUE THREAD

**Issue by esn89** [akinsho/toggleterm.nvim#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have set my ls aliased to:

```zsh
ls -N --group-directories-first --color=auto
```

With LS_COLORS like:

```
no=00:rs=0:fi=00:di=04;34:ln=36:mh=04;36:pi=04;01;36:so=04;33:do=04;01;36:bd=01;33:cd=33:or=31:mi=01;37;41:ex=01;36:su=01;04;37:sg=01;04;37:ca=01;37:tw=01;37;44:ow=01;04;34:st=04;37;44:
```

This works great, as you can see on the right hand side, I see my directories being listed with a blue underline.

However, on the right, which is neovim with toggleterm, the `ls` shows a red underline for some reason.

<img width="1243" alt="Screenshot 2023-09-24 at 10 59 23 AM" src="https://github.com/akinsho/toggleterm.nvim/assets/1475220/bac847c2-42f1-4169-a665-3079f3743d11">
 

### Expected Behavior

I expect the red underline to be blue, the same as my zsh shell.

### Steps To Reproduce

```lua
    {
        'akinsho/toggleterm.nvim',
        version = '*',
        keys = {
			{ "<C-\\>", mode = 'n' },
		},
		config = function()
			require('toggleterm').setup({
				open_mapping = [[<c-\>]],
                shade_terminals = false,
                hide_numbers = true,
                start_in_insert = true,
                direction = 'float',
				persist_size = true,
				persist_mode = true,
				shading_factor = '25',
                shell = vim.o.shell,
				close_on_exit = false,
                float_opts = {
                    border = 'curved',
                    winblend = 20,
                },
				highlights = {
					FloatBorder = {
						guifg = "#e67e80",
					}
				}
            })
        end,
    },
```

### Environment

```Markdown
- OS: MacOS 13.6
- neovim version: 0.9.2
- Shell: zsh 5.9
```

**Comment by akinsho** [comment]
@esn89 this issue isn't caused by toggleterm. This is an issue with neovim upstream. I don't have that issue to hand but in short toggleterm doesn't control how things are rendered in a terminal only neovim can determine that so if something appears odd it won't be because of this plugins.
