### ISSUE TITLE
[BUG] `hide_numbers = false` in configuration, doesn't works

### ISSUE THREAD

**Issue by componhead** [akinsho/toggleterm.nvim#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As the subject says, toggling `hide_numbers` to false, the numbers still are missed.

### Expected Behavior

Terminal with the same number configuration as the other buffers.

### Steps To Reproduce

1. change configuration with `hide_numbers = false`
2. expect terminals with same configurations as other buffers (in my case numbers and relative)

### Environment

```Markdown
- OS: macos
- neovim version: 0.8.3
- Shell: fish

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.3/share/nvim"
```

**Comment by akinsho** [comment]
@componhead I depend on this option every day it works well for me, can you confirm that you have a completely minimal config setup when trying this and that no other plugin or file is setting the value of number externally

**Comment by componhead** [comment]
Ok, I checked only with my init.lua active (plus toggleterm) and still same behaviour. Maybe only a problem by my part. Thank you btw.

**Comment by akinsho** [comment]
I think you might need to try with a minimal configuration then add things in till you find the root cause

**Comment by jockee** [comment]
I'm experiencing the same issue, but only with `direction = "float"`.
