### ISSUE TITLE
[Suggestion] Floating terminal position relative to editor

### ISSUE THREAD

**Issue by boyo23** [akinsho/toggleterm.nvim#515]
Firstly, awesome plugin!

It would be nice to have an option to open the floating terminal relative to the editor.

Like this maybe:

```lua
float_opts = { relative_position = 'editor' }
```

**Comment by akinsho** [comment]
IIRC the float_opts already exists and you can in fact pass options like that 🤷🏾‍♂️ otherwise PR welcome

**Comment by akinsho** [comment]
@boyo23 I apologise but I really don't have the time to dig into this specifically I have to manage a lot of OSS projects and am trying to spend more of my time on other work. Your going to need to dig through the settings and help docs i.e. `:help toggleterm` and go from there
