### ISSUE TITLE
[Question] Frame color is not matching with the rest

### ISSUE THREAD

**Issue by Faetu** [akinsho/toggleterm.nvim#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The toggleterm has a frame when opened in float mode:
<img width="189" alt="image" src="https://github.com/akinsho/toggleterm.nvim/assets/55803495/7e79d25f-e0bc-4b71-9362-93a225538e4e">
But the frame is white and has not rounded corners like the rest of my fresh-installed lazynvim.

### Expected Behavior

I'm trying to get the toggleterm to look like this:
<img width="474" alt="image" src="https://github.com/akinsho/toggleterm.nvim/assets/55803495/f9610483-8c4a-4c7e-afcc-0560029e72a7">
But cant find any way to set it up. This look is achieved with https://github.com/folke/noice.nvim.

### Steps To Reproduce

Just toggle a fresh install of toggleterm

### Environment

```Markdown
- OS: MacOS Sonoma 14.3
- neovim version: 0.9.5
- Shell: fish
```

**Comment by akinsho** [comment]
@Faetu there's quite a lot of misconceptions here I think it's a bit hard to unpick them without having to explain quite a lot about neovim, plugins and windows. I'll give you a short version but then you will have to go to either the lazyvim repo or reddit to understand fully. In short there is absolutely no relationship between nice windows and toggleterm windows at all. All of the window settings are done by the plugin or in your case the config framework. You as a user have to organise all those things or in your case you need to talk to the folks over at lazyvim/learn how this stuff works on reddit and start there. This repo isn't the right place for this question in the broader context and the window config specific to toggleterm is documented in the README

**Comment by Faetu** [comment]
Hi @akinsho 

Thx for the explanation. I need to read more about lazyvim and the named plugins to understood the relationships or the not existing relationships.

best regards
