### ISSUE TITLE
[Feature] Add :ToggleTermSendCurrentLineOrSelection

### ISSUE THREAD

**Issue by isentropic** [akinsho/toggleterm.nvim#551]
It would be good to `:ToggleTermSendCurrentLineOrSelection` for a more seamless repl develpment. It should send the current line, or if in a visual selection, send the selction instead

**Comment by akinsho** [comment]
I think there is already some sort of functionality like this contributed by some other users might not be exactly what you want but as I mention in the README REPL functionality is out of scope as far as I'm concerned but if you are willing to raise a PR I'm happy to have a look
