### ISSUE TITLE
[help] How to hide/customize bottom bar in terminal

### ISSUE THREAD

**Issue by anandkumar89** [akinsho/toggleterm.nvim#560]
How to hide or customise this bar. I'd want a usual separator line between terminal splits, with number identifier at max. How do I achieve this ?

<img width="837" alt="Screenshot 2024-04-06 at 11 58 37 AM" src="https://github.com/akinsho/toggleterm.nvim/assets/12571250/13534b78-a8f9-415e-b8dc-ce5d2f5c27e9">

**Comment by sg3t41** [comment]
I'm also struggling to hide the default status line when using ```:ToggleTerm``` to open a split terminal. I've been trying to figure out how to do this but haven't had any success.

If there is a solution for this, I would greatly appreciate any advice.

Thank you.

**Comment by sg3t41** [comment]
Thank you for your reply. 
I understand.

**Comment by stegrams** [comment]
I'm not interested in customizing my statusline. 
I'll be satisfied if toggleterm has the same one as my other windows.

As it is now, toggleterm statusline has transparent background and its content look like as they are part of the buffer content. 
It's kind of confusing.

For the same reason, it would be great if I could remove the header "run/current-system...".
Thank you for sharing!

![Image](https://github.com/user-attachments/assets/3ad38c7c-854e-43c2-9546-b60a1dd32e86)
