### ISSUE TITLE
[BUG] open_mapping keybinding only works after `:ToggleTerm` has been called before

### ISSUE THREAD

**Issue by jmpargana** [akinsho/toggleterm.nvim#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open neovim and use the **open_mapping** (ex. `<c-\>`) nothing happens.
After I run `:ToggleTerm` for the first time the mapping becomes available and starts working to open and close the terminal.

I've tried changing the `open_mapping` option or sticking to the default but nothing changes.

### Expected Behavior

Configured mapping should work before running command.

### Steps To Reproduce

1. Using the versions listed below, setup a minimal neovim with the following config:
```
  {
    'akinsho/toggleterm.nvim',
    version = '*',
    opts = {
      open_mapping = [[<c-\>]],
    },
    keys = {
      { '<C-t>', '<cmd>ToggleTerm<cr>', desc = '[T]oggle [T]erm' },
    },
  },

```
2. Launch `nvim` and try to toggle terminal with defined config

### Environment

```Markdown
- OS: MacOS 14.4 (23E214)
- neovim version: NVIM v0.9.5
- Shell: zsh 5.9 (x86_64-apple-darwin23.0)
```

### Anything else?

I'be happy to contribute to this repository by fixing this bug if you giving me some pointers :)

**Comment by jmpargana** [comment]
After investigating I've noticed that the with `lazy.nvim` is not loading. Running `lua require("toggleterm").setup {}` or sourcing the `toggleterm.lua` file loads makes the `open_mapping` available.
I've tried to use the default configuration suggested in the README, but it has the same problem. 

Do you have any pointers?

<img width="726" alt="Screenshot 2024-04-24 at 18 17 17" src="https://github.com/akinsho/toggleterm.nvim/assets/14986865/0fc14e1a-a780-4db8-8913-1db6b2cf0ea6">

**Comment by mixtli** [comment]
The open_mapping is not working for me either.

**Comment by tkkcc** [comment]
you use lazy's `key` config, this will make it lazy load on key press,  https://github.com/folke/lazy.nvim?tab=readme-ov-file#-plugin-spec

you can set `lazy` to false besides `key`, or rich the `key` config for all bindings you need.

**Comment by jmpargana** [comment]
> you use lazy's `key` config, this will make it lazy load on key press, https://github.com/folke/lazy.nvim?tab=readme-ov-file#-plugin-spec
> 
> you can set `lazy` to false besides `key`, or rich the `key` config for all bindings you need.

Thank you that fixed it :)
