### ISSUE TITLE
[FETURE] How do I re-run a previous command?

### ISSUE THREAD

**Issue by akarl** [akinsho/toggleterm.nvim#576]
A `:TermRedo` or similar. This command would re-execute the previous `TermExec cmd=[..]`.

This is useful because you can bind that to a keymap where you can quickly re-run a command such as a make command, a unit-test, compiler, linter etc based on what you are currently working on.

I've previously used Neoterm, which had this feature.

Perhaps there is a way for me to create that functionality, but I'm unsure how.

**Comment by akinsho** [comment]
Don't think I have the bandwidth for this but happy to review a PR if you decide to take one on. Sorry but I can't run through how to go about implementing it but if you have a read of the code you might be able to get a sense of what to do
