### ISSUE TITLE
[BUG] toggle term does not respect venv

### ISSUE THREAD

**Issue by itsmenewbie03** [akinsho/toggleterm.nvim#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i execute `which pip` inside toggleterm i get `/bin/pip`

### Expected Behavior

the output should be the path to pip inside the active venv like `~/venv/bin/pip`.
this has worked completely fine before in nvim version 0.9

### Steps To Reproduce

1. create a blank directory
2. create a python virtual env inside the newly created directory
3. activate the virtualenv
4. nvim .
5. open toggleterm
6. type `which pip`

### Environment

```Markdown
- OS:EndeavourOS
- neovim version: 0.10
- Shell: zsh
```

### Anything else?

![image](https://github.com/akinsho/toggleterm.nvim/assets/89230263/92bce474-10b5-40d7-82e6-1285cc047213)
the left window is the result of `:ter which pip`

**Comment by akinsho** [comment]
@itsmenewbie03 this plug in is not actually in control of the terminal's behaviour. It's just a UI plugin so that the terminal looks nicer. How the terminal actually behaves is a neovim issue. I recommend raising an issue there if anything has changed, but that's definitely not coming from this plugin

**Comment by itsmenewbie03** [comment]
> @itsmenewbie03 this plug in is not actually in control of the terminal's behaviour. It's just a UI plugin so that the terminal looks nicer. How the terminal actually behaves is a neovim issue. I recommend raising an issue there if anything has changed, but that's definitely not coming from this plugin

Thank You 💜

**Comment by WSTRN** [comment]
I had the same issue. I moved all my export PATH lines from .zshrc to .zprofile, and everything worked fine after that.
