### ISSUE TITLE
Preserve vi mode?

### ISSUE THREAD

**Issue by rew1nter** [akinsho/toggleterm.nvim#588]
With vi mode on bash, toggleterm always goes back to normal mode when the terminal is re-opened. Is there a way to preserve the vi mode ?

**Comment by akinsho** [comment]
This functionality relates specifically to neovim not this plugin so I would look for a solution there rather than from this plugin

**Comment by rew1nter** [comment]
Interesting. Nvterm, a similar plugin, on the other hand, handles this pretty well :/
