### ISSUE TITLE
[Feature Request] Open horizontal term at the top / Expose split_commands

### ISSUE THREAD

**Issue by cagdassalur** [akinsho/toggleterm.nvim#590]
Very similar topics came up before from various needs, #326, #97. So I know it's not preferred for you to expose/maintain window commands. 

My usecase is to be able to open the `horizontal` term at top instead of bottom. Imho much more ergonomic and easy to read especially on a laptop screen that's not raised. But looking around the code and seeing the previous discussions, i don't see how this would be possible to achieve.

Maybe we can have an undocumented config? So it won't be "officially" supported but still make toggleterm a bit more scriptible.
How about adding a config for 'top/below'? similar overhead imho but seems more logical if just exposing window commands as a whole is a concern.

Maybe there are other ways, feel free to suggest or just close the issue if this is spammy.

But if you're okay with some kind of way to achieve this, i can get to creating a pr for it.

Also: thanks for this plugin!

**Comment by akinsho** [comment]
This isn't really one for me I think sounds like a non trivial amount of work and tbh I don't think it'll be worth it
