### ISSUE TITLE
[BUG] No cursor color in terminal

### ISSUE THREAD

**Issue by sharpchen** [akinsho/toggleterm.nvim#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No cursor background when typing in terminal, maybe it's terminal emulator's problem? It's the same in wezterm and WindowTerminal.
![term](https://github.com/user-attachments/assets/f8ba35b4-42f5-44d9-ad3a-835e582e3176)

### Expected Behavior

Have a cursor background to better locate where I am

### Steps To Reproduce

- OS: windows 10; nvim: 0.10.0; wsl: ArchWSL; terminal: wezterm
- config
```lua
return {
  'akinsho/toggleterm.nvim',
  version = '*',
  config = function()
    require('toggleterm').setup({
      open_mapping = '<C-\\>',
    })
  end,
}
```

### Environment

```Markdown
- OS:
- neovim version: 0.10.1
- Shell: bash
```

**Comment by akinsho** [comment]
Coloring in you terminal is way outside of the remit of this plugin it doesn't influence terminal UI at all that's a neovim/terminal level issue probably something to do with your config but certainly not toggleterm

**Comment by sharpchen** [comment]
I just found that `TermCursor` has missing background. So giving it a highlight solves the problem
