### ISSUE TITLE
[BUG] "Attempt to call field 'create' (a nil value)" error on startup

### ISSUE THREAD

**Issue by MMachado05** [akinsho/toggleterm.nvim#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On starting up Neovim, I get an error saying that the `vim.highlight.create(hl_group, options)` command is a `nil` value (specifically, the `create` function is a nil value) in the `colors.lua` file.

Here's the traceback for the error I'm receiving:
```
# stacktrace:
  - /toggleterm.nvim/lua/toggleterm/colors.lua:99 _in_ **set_highlights**
  - /toggleterm.nvim/lua/toggleterm.lua:359 _in_ **setup**
  - ~/.config/nvim/lua/plugins/toggleterm.lua:6 _in_ **config**
  - ~/.config/nvim/init.lua:19
```

### Expected Behavior

I assume I shouldn't have this error at all.

### Steps To Reproduce

I've installed Toggleterm with lazy.nvim as so:

```lua
return {
  "akinsho/toggleterm.nvim",
  version = "v1.*",
  opts = {},
  config = function()
    require("toggleterm").setup({})
  end
}
```

### Environment

```Markdown
- OS: Kubuntu 22.04.3
- neovim version: 0.10.0
- Shell: bash
```

### Anything else?

I read somewhere that the command that's giving the final error is an internal function, so maybe that got changed in the 0.10.0 release?

**Comment by akinsho** [comment]
@MMachado05 I also run v0.10 stable on macOS and don't see this issue? you're also the only person that's reported this since 0.10 got released weeks ago at this point I think

**Comment by MMachado05** [comment]
@akinsho That's very strange... plus, when trying to open a terminal (such as the lazygit terminal with the example keybind) I get an error saying that `vim.highlight.link` is also a nil value... Maybe it's not finding `vim.highlight` for some reason?

**Comment by akinsho** [comment]
@MMachado05 there are a lot of ways for nvim to be installed and I've seen issues historically about vim lua libraries having loading issues depending on linux distros etc. in this case it seems very likely to relate to your setup locally. If you have access to another machine and try or maybe another os you can see how it behaves there

**Comment by MMachado05** [comment]
@akinsho This makes sense, I recently also ran into an issue where some of my plugins were also woefully out of date and that was causing problems, so for now I'll close this as it likely *is* just a my-setup issue. Thanks for the direction and advice!
