### ISSUE TITLE
[BUG] <title> the excommand  :lcd does not trigger autochdir

### ISSUE THREAD

**Issue by WantChane** [akinsho/toggleterm.nvim#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

command ':lcd path' will change neovim cwd path,but no autochdir 

### Expected Behavior

the excommand  :lcd trigger autochdir

### Steps To Reproduce

1.Run ':lcd path'
2.open term

### Environment

```Markdown
- OS:Arch
- neovim version:0.10.2
- Shell:zsh
```

**Comment by akinsho** [comment]
This isn't an issue with toggleterm, it doesn't control the behaviour of neovims terminal that is down to your neovim settings
