### ISSUE TITLE
float terminal character color show abonarmality when i set winblend

### ISSUE THREAD

**Issue by ZhiWei-Ou** [akinsho/toggleterm.nvim#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/179bfb63-6a9f-42b0-afbc-ffefa88dfea0)

### Expected Behavior

expected same color

### Steps To Reproduce

require'toggleterm'.setup {
    float_opts = {
        border = 'double',
        winblend = 10,
        title_pos = 'center',
  },
}

then open float toggleterm

### Environment

```Markdown
- OS: MacOs sequioa
- neovim version: 
  NVIM v0.10.0
  Build type: Release
  LuaJIT 2.1.1716656478
- Shell:
  zsh
```

**Comment by akinsho** [comment]
@ZhiWei-Ou character rendering isn't handled by this plugin this sort of issue is happening at the neovim layer unfortunately so not a bug for this repo
