### ISSUE TITLE
Feature Idea: Terminals List that can be used with picker (e.g: Telescope)

### ISSUE THREAD

**Issue by kiuKisas** [akinsho/toggleterm.nvim#80]
That could be great to have a list of opens terminal and to choose between them through a picker like Telescope for example.

**Comment by akinsho** [comment]
This is a good idea, happy to review a PR for this 👍🏿

**Comment by tknightz** [comment]
@kiuKisas Hey! I made a telescope extension, you can check it out [telescope-termfinder](https://github.com/tknightz/telescope-termfinder.nvim)

**Comment by kiuKisas** [comment]
Awesome ! I'll give a try :)
