### ISSUE TITLE
Floating Terminal is fully-transparent

### ISSUE THREAD

**Issue by jjuel** [akinsho/toggleterm.nvim#89]
So when I open the terminal I an literally see everything on the neovim window behind the terminal. I have messed with the shading and shade factor to no avail. What setting do I need to adjust to make the terminal not transparent?
![toggleterm](https://user-images.githubusercontent.com/2584714/130650500-dba832c4-130b-45d8-bc50-f6589d59044f.png)

**Comment by akinsho** [comment]
@jjuel I think for some reason I can't fathom your terminal/neovim is responding badly to the `winblend` option that is set for floats, it's set to 3 which should give only the barest hint of transparency but it doesn't seem to be compatible with your config/terminal. Can you try adding `winblend = 0` to your `float_opts` and see if that fixes things for you (you'll need to verify in the README exactly where that option goes)

**Comment by jjuel** [comment]
@akinsho Yes setting `winblend = 0` fixes this issue. Yeah I am not sure if kitty terminal is the issue or something else in my config, but that setting makes it fully usable now so thank you!

**Comment by tiborsimon** [comment]
`windblend = 0` fixed for me too. I am using kitty on wayland. Thanks!

**Comment by andriati-alex** [comment]
Same issue here with kitty terminal. That fixed for me too. :+1:
