### ISSUE TITLE
Can't change default shell to powershell or pwsh

### ISSUE THREAD

**Issue by maxxnino** [akinsho/toggleterm.nvim#90]
- The default Shell like `cmd` is working fine. When i change the environment variable `$SHELL` to `pwsh` or `powershell`. The toggle term open with empty window.

![empty](https://user-images.githubusercontent.com/34153891/130977890-912aa267-4902-4f3d-8b20-f9302a02ed2d.png)

- I try to type something and press enter. It's flash some words about 1 second and auto close the window

![flash](https://user-images.githubusercontent.com/34153891/130978131-52f21f0e-4078-4843-b362-3ab5a1530240.png)

**Comment by EdenEast** [comment]
This is an issue with neovim. There is an issue with `termopen()` when `vim.o.shell` is set to `powershell` on windows. Refer to neovim issue [#15634].  I created a workaround in my config for this issue in [this commit]. This also requires that `vim.o.shell` is set to the default `cmd.exe` on windows.

[#15634]: https://github.com/neovim/neovim/issues/15634
[this commit]: https://github.com/EdenEast/nyx/commit/cb55b7bd4513dd459bca451d6bdada04433d3e49

**Comment by maxxnino** [comment]
@EdenEast thank you, it work, i use [LunaVim](https://github.com/LunarVim/LunarVim)
 - Script open lunarvim
```powershell
$env:HOME = "$HOME"
$env:USER = "$HOME"
$env:SHELL = "cmd"
$env:TERMINAL = "$env:SHELL"
$env:VIMRUNTIME = "$(scoop prefix neovim-nightly)/share/nvim/runtime";
Set-Variable -name "LUNARVIM_RUNTIME_DIR" -Value "$HOME/.local/share/lunarvim"
Set-Variable -name "LUNARVIM_CONFIG_DIR" -Value "$HOME/.config/lvim"
nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" $args
```
 - Custom shell config
```lua
lvim.builtin.terminal.shell = "pwsh -NoLogo"
```

**Comment by akinsho** [comment]
Excellent, thanks for sharing @EdenEast 🙏🏿 . Gonna close this out then

**Comment by dineshKumar777** [comment]
Adding this for reference, when configuring custom vim. Tested and working fine with nvim 0.7

``` lua
-- lua config
-- https://stackoverflow.com/questions/36108950/setting-up-powershell-as-vims-shell-command-does-not-seem-to-be-passed-correct
vim.cmd([[
set shell=pwsh
set shellcmdflag=-command
set shellquote=\"
set shellxquote=
]])
```
