### ISSUE TITLE
How to run the shell command in the appointed line in vim

### ISSUE THREAD

**Issue by InigoMarin** [akinsho/toggleterm.nvim#91]
hello,

I have this in  my Neovim.

 map <F12> :exec '!'.getline('.')

How can I do it with your plugin?

**Comment by akinsho** [comment]
@InigoMarin you can just construct a command similar to that using the `TermExec` command which is documented in the README.

Something like `map <thing> <Cmd>execut 'TermExec cmd="'.getline('.').'"<CR>'`. you can have a go with something like that and figure out the details

**Comment by InigoMarin** [comment]
Thank you for your reply @akinsho , I have succeeded.

The way to do it would be:

nmap <leader>x <cmd>execute 'TermExec cmd='.shellescape(getline('.'))<cr>
