### ISSUE TITLE
Show mode

### ISSUE THREAD

**Issue by bytesizedpcs** [akinsho/toggleterm.nvim#92]
Is there a way to show the mode that the terminal is in? Normal, insert, etc.

**Comment by akinsho** [comment]
@bytesizedpcs your statusline should show you what mode your current window is in if you have one setup or are using a plugin. Alternatively, you can turn on `showmode`.

**Comment by akinsho** [comment]
Closing this out now since I believe it's answered and doesn't really relate to this plugin

**Comment by bytesizedpcs** [comment]
Even with `showmode` enabled, on floating windows there's nothing that shows up within the status line; at least not with galaxyline.

**Comment by akinsho** [comment]
@bytesizedpcs tbh this problem seems out of scope for this plugin, I think whatever the solution would be would involve something in a user's config if possible since.
