### ISSUE TITLE
How to open multiple terminals?

### ISSUE THREAD

**Issue by augustocdias** [akinsho/toggleterm.nvim#93]
I'm sorry, but in the README it was not clear to me and from the screenshots it seems possible.

How can I open multiple terminals in horizontal for example?

I usually run `:ToggleTerm direction=horizontal` and as the name says it toggles... Is there a flag to open a new one by the side of the existing one?

**Comment by baobaoit** [comment]
Hello @augustocdias ,

When you open the first terminal like this:
![image](https://user-images.githubusercontent.com/31947091/133394658-56319997-636d-4689-9907-d127278576f9.png)

You need to escape the `TERMINAL` mode via the `<Esc>` key that has been mapped with the combination `<C-\><C-n>`
![image](https://user-images.githubusercontent.com/31947091/133395516-22fef1e6-633d-4964-9175-f76fabf66794.png)

Then you type on: `2<C-\>`, and the result:
![image](https://user-images.githubusercontent.com/31947091/133396789-fdf68b30-3a8c-440b-822f-6549f282c4fc.png)


Explain:
- `2`: this is the terminal identity, your first terminal is `1`.
- `<C-\>`: this is the combined key mapping to the command `:ToggleTerm`.

P/s: are you the guy on the Reddit `r/neovim`? I'm `u/Ok_MrDuck`. English is not my primary language so sorry about my grammar is not good. I'm finding the issue like you and suddenly I figured out the way to do it after reading the README many times LOL.

**Comment by akinsho** [comment]
@baobaoit thanks for jumping in with the explanation 🥇 that's really helpful, how would you feel about making a PR to the README with similar instructions?

@augustocdias tbh I've never really realised it might be unclear, since I built the plugin so I'm quite familiar with how it works and tbh no one has ever asked before. Hopefully with instructions like the ones above in the README that should be enough

**Comment by augustocdias** [comment]
Yes. @baobaoit  that is me 😅. Thanks for the explanation

@akinsho I can imagined. I was surprised no one asked, because I searched the issues before asking. 😅
Anyway tks for the plugin. I was a long time looking for something like it.

**Comment by jrafaaael** [comment]
Hello! I am getting the error `E481: No range allowed`.
My config:
```lua
require('toggleterm').setup {
  -- size can be a number or function which is passed the current terminal
  -- size = 20 | function(term)
  --   if term.direction == "horizontal" then
  --     return 15
  --   elseif term.direction == "vertical" then
  --     return vim.o.columns * 0.4
  --   end
  -- end,
  -- size = 20,
  open_mapping = [[<C-t>]],
  hide_numbers = true, -- hide the number column in toggleterm buffers
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = 3, -- the degree by which to darken to terminal colour, default: 1 for dark backgrounds, 3 for light
  start_in_insert = true,
  insert_mappings = true, -- whether or not the open mapping applies in insert mode
  persist_size = true,
  direction = 'horizontal',
  close_on_exit = true, -- close the terminal window when the process exits
  shell = vim.o.shell, -- change the default shell
  -- This field is only relevant if direction is set to 'float'
  -- float_opts = {
    -- The border key is *almost* the same as 'nvim_open_win'
    -- see :h nvim_open_win for details on borders however
    -- the 'curved' border is a custom border type
    -- not natively supported but implemented in this plugin.
    -- border = 'single' | 'double' | 'shadow' | 'curved' | ... other options supported by win open
    -- width = <value>,
    -- height = <value>,
    -- winblend = 3,
    -- highlights = {
    --   border = "Normal",
    --   background = "Normal",
    -- }
  -- }
}

function _G.set_terminal_keymaps()
  local opts = {noremap = true}
  vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-h>', [[<C-\><C-n><C-W>h]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-j>', [[<C-\><C-n><C-W>j]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-k>', [[<C-\><C-n><C-W>k]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-\><C-n><C-W>l]], opts)
end

-- if you only want these mappings for toggle term use term://*toggleterm#* instead
vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
```

**Comment by lleger** [comment]
Weird question, but do these steps only work if you have `terminal_mappings = false`? Without that, trying <kbd>C-\</kbd> just closes the terminal, so you can't get into normal mode to split another terminal.

**Comment by KarthikRaju391** [comment]
is it possible to have the new terminal session open as a tab at that level itself rather than a split?
