### ISSUE TITLE
`tabedit %` fails if current buffer has empty file name

### ISSUE THREAD

**Issue by zeertzjq** [akinsho/toggleterm.nvim#95]
Steps to reproduce:
1. Create a new empty buffer using `:new`
2. Run `:ToggleTerm direction=tab`
3. `Vim(tabedit):E499: Empty file name for '%' or '#', only works with ":p:h": tabedit %`

**Comment by akinsho** [comment]
Thanks for pointing this out @zeertzjq, tbh I don't think I know of a good solution for this 🤔

**Comment by QiBaobin** [comment]
@akinsho , can we you `tabnew` instead of `tabedit`?

**Comment by akinsho** [comment]
@QiBaobin unfortunately not, I actually ran through a few attempts to fix this including that but didn't document my findings here but having to do this by memory. I think that was one of the first things I tried, but the problem with that is that you can't do `tabnew %` if the buffer is unnamed, this will error all the same. One way round is to do `tabnew <name-of-buffer>` but you don't have access to the buffer name before the tab is opened and if there are no other tabs then `tabnew` on its own will create a buffer which won't be used and just add clutter to the bufferlist

**Comment by zeertzjq** [comment]
How about first `tabnew` and then setting `bufhidden=wipe` for that temporary buffer?

**Comment by akinsho** [comment]
Sorry only now got a chance to reply/look into your suggestion @zeertzjq, it seems to work 👍🏿 just pushed a fix with that change in. Not sure if I'm missing anything though 🤷🏿‍♂️ 😅
