### ISSUE TITLE
How to quit terminal?

### ISSUE THREAD

**Issue by kdurant** [akinsho/toggleterm.nvim#99]
I want to close a opend terminal, because I want to use  current path as terminal path when I use `ToggleTerm` command

**Comment by akinsho** [comment]
@kdurant you can close the terminal the same way you would close a terminal outside of nvim e.g. using `exit` or else you can delete the buffer using `:bdelete`. You can also change the directory of a terminal by using the terminal number e.g. `:2Toggleterm dir=my/path/to/thing` which should change the terminal's directory

**Comment by Agentzhao** [comment]
```
require("toggleterm").setup{
  size = 20,
  open_mapping = [[<C-\>]],
  direction = 'horizontal',
}

function _G.set_terminal_keymaps()
  local opts = {noremap = true}
  vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', 'jk', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-h>', [[<C-\><C-n><C-W>h]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-j>', [[<C-\><C-n><C-W>j]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-k>', [[<C-\><C-n><C-W>k]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-\><C-n><C-W>l]], opts)
end

vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
```
I've added this into my init.vim file but the key bindings in the function don't seem to work. Am I supposed to use <C-k> while in the terminal to move up?

**Comment by Agentzhao** [comment]
@akinsho Oh ok! I'll try to play around and see if it works. Can I just check if this line
```
vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-\><C-n><C-W>l]], opts)
```
means it's mapping Ctrl + l in terminal mode to Ctrl+\ Ctrl + n Ctrl + W?

**Comment by akinsho** [comment]
It's mapping <kbd>C-L</kbd> to <kbd>C-\\</kbd><kbd>C-N</kbd> which is the key sequence to leave terminal mode then the next keys <kbd>C-W</kbd><kbd>l</kbd> is the default window command to jump to the window on the right

**Comment by zsytssk** [comment]
I add some keymap to terminal as open_mapping. and toggleterm allways open a new terminal.
```lua
require("toggleterm").setup {
  direction = 'float',
  open_mapping = [[<c-\>]],
  on_open = function(term)
    vim.api.nvim_buf_set_keymap(term.bufnr, "t", "<c-\\>", "exit<CR>", { noremap = true, silent = true })
  end,
  close_on_exit = true,
}
```
